### ISSUE TITLE
Changing version scheme

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#1039]
Until now I didn't put much thought into the version scheme. The public (http) api can change between releases and I think this will very often be the case. I try to document it in the Changelog, but it's too much effort to maintain multiple api versions. With this in mind, the [semantic versioning scheme](https://semver.org) doesn't make much sense here and so instead I think using the [calendar version scheme](https://calver.org) is a better fit. That means the next version (after 0.26.0) will be something like `21.12`.

**Comment by wallace11** [comment]
Sounds great.
That way you don't tie the API schema version to Docspell version, so it can remain compatible across versions.
Let's hope that the next stable release will come before December ;)

**Comment by seijikun** [comment]
I don't understand what the problem is exactly, but isn't semantic versioning scheme the better choice here?
Rule 4 states:
```
Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
```
Meaning that there simply are no stability guarantees.

**Comment by eikek** [comment]
> Meaning that there simply are no stability guarantees at this stage of the development.

Yes exactly! It's all fine unless the major moves to 1. I just thought about when I would want to set the major version to 1 and what this means to me. And I figured I don't want to ensure a stable http api through versions. The web client will always be up to date and I'll try to move the dsc tool the same way with each release. Should there be third party tools, they must study the changelog when upgrading. The calendar-version scheme is essentially removing any guarantees from the version 😉 so it is like having a major version 0 for all time…

**Comment by seijikun** [comment]
Ah, so that's what you meant! But isn't an increase of the major version number exactly that (Documenting an API break)?
Only downside with the calendar scheme I see is that:
After a new version is released (like `0.26.0` now) ... [what version number do you set it to next](https://github.com/eikek/docspell/commit/9812b8f6c8d6d9aa64768ea38f3ad2bb9a8473f9)? And does that mean that there **will** be no release before december 2021, even if you need to fix a bug?

**Comment by eikek** [comment]
> But isn't an increase of the major version number exactly that (Documenting an API break)?

Yes, true. This means I would need to check for any api breakage before I know which version to use next. It would also look strange, if every new release increases the major version. Then there is no advantage in semantic versioning. I love semver for libraries, but for apps I'm not so sure … 🤔 


>  And does that mean that there **will** be no release before december 2021, even if you quickly need to release a bugfix?

Ah, no, of course not! This is a problem with calver - I need to use *some* date… although it doesn't make sense for the "not yet released version". The next version happens whenever it should and there is time. And it will get the name of the then current month. I chose 21.12 for the "next version" now because I'm hoping to do at least one release before the end of year :-). But this is indeed not a good one. In summary there are just no guarantees :)

But I'm also very fine with keeping the 0.x.y scheme! I just thought people might think when there is a 1.x version …

**Comment by seijikun** [comment]
I don't have a very strong opinion on it either way. I just wanted to know how you handle assigning a new version number after a release is out. :)

**Comment by eikek** [comment]
The same for me :) But if the calendar based scheme results in more confusion, it's probably better to just keep incrementing this middle number  :)

**Comment by eikek** [comment]
So after some days of not being really for this change, I'm going to just increment that number for a while :-)  The downside with calver is for me that it is not known which version will be next, as I don't have any schedule.
