### ISSUE TITLE
Can't start docker-compose on NAS

### ISSUE THREAD

**Issue by didiatworkz** [eikek/docspell#1058]
Hello together,
I want to install docspell on my Synology NAS system.
But I can't start all docker containers without a boot loop.
Here is the protocol: https://pastebin.com/RtKw7WrU

Can some help me here?
Btw: I checked the docs and I tried multiple time different options how I can install it.

Best
dididatworkz

**Comment by eikek** [comment]
Hi @didiatworkz 

This part
```
docspell-restserver | Caused by: java.net.SocketTimeoutException: connect timed out
docspell-restserver | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
docspell-restserver | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
docspell-restserver | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
docspell-restserver | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
docspell-restserver | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
docspell-restserver | 	at java.base/java.net.Socket.connect(Socket.java:609)
docspell-restserver | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
```
looks like it cannot connect to the database. I can't tell why - could you try to play with the settings a bit? Maybe try to figure out if the postgres container is really running and then whether the settings are correct (in `docspell.conf`).

**Comment by didiatworkz** [comment]
Hello @eikek 
I also thought that something is wrong with the Postgres database, but I see that the container starts but isn't reachable.
In this case, I changed nothing in the docspell.conf, but I think the address `db:5432/dbname`is not online.
I'm not a docker master but is there a way to test if this database reachable?
And does the docker-compose file not need a port forwarding for the db container?

**Comment by didiatworkz** [comment]
Hello @eikek 
after some other testings I found out that it was my Firewall settings in Synology.
After I changed the settings, it runs smoothly.
The issue can be closed.

Best

**Comment by eikek** [comment]
Hi @didiatworkz - ah nice to hear! The portforward in the compose file is necessary if you want to connect from outside the container. That would be an option to test from some other host, whether it is up and running. I think docker-compose puts by default all containers in the same network, so they can reach each other without any further configuration.
