### ISSUE TITLE
[Feature Request] Show info "Documents to be processed"

### ISSUE THREAD

**Issue by monnypython** [eikek/docspell#1069]
If I import some documents via the webui and then continue working with other documents (waiting for new documents from queue), it would sometimes be helpful to see how many documents still need to be processed without having to look in the "processing que". So you would not have to interrupt the current other tasks and could continue with the new documents e.g. if the marker is no longer visible.

This could be a small mark on the gear symbol, for example. At best with the number of items still to be processed.

![image](https://user-images.githubusercontent.com/42573701/133231959-ec87d94a-bc3e-4da1-9976-f7f9ca590edc.png)

**Comment by eikek** [comment]
Hi @monnypython , sorry for some reason I missed this issue. You're right - this would be a nice addition. The whole "processing" topic (ui wise) must be improved. It is still in its very first version :). There is an issue for this already (not that specific, just fyi):  #596.
