### ISSUE TITLE
Restserver does not connect to solr

### ISSUE THREAD

**Issue by r4tze** [eikek/docspell#1071]
When I try to use the search I can see Error 400 in the rest server log. 
```
Sep 17 11:43:09 docserver docspell-restserver[4199]: [io-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/search
Sep 17 11:43:09 docserver docspell-restserver[4199]: [io-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 400 Bad Request
Sep 17 11:43:09 docserver docspell-restserver[4199]: [io-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchStats
Sep 17 11:43:09 docserver docspell-restserver[4199]: [io-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 400 Bad Request
```

This is the configuration of the rest server.conf
```
  # Configuration of the full-text search engine.
  full-text-search {
    # The full-text search feature can be disabled. It requires an
    # additional index server which needs additional memory and disk
    # space. It can be enabled later any time.
    #
    # Currently the SOLR search platform is supported.
    enabled = true

    # Configuration for the SOLR backend.
    solr = {
      # The URL to solr
      url = "http://localhost:8983/solr/docspell"
      # Used to tell solr when to commit the data
      commit-within = 1000
      # If true, logs request and response bodies
      log-verbose = false
      # The defType parameter to lucene that defines the parser to
      # use. You might want to try "edismax" or look here:
      # https://solr.apache.org/guide/8_4/query-syntax-and-parsing.html#query-syntax-and-parsing
      def-type = "lucene"
      # The default combiner for tokens. One of {AND, OR}.
      q-op = "OR"
    }
  }
```
If I connect to solr by IP::8983/solr/ I can see the Solr side with my docspell core. But If I try to connect to http://IP:8983/solr/docspell with my browser I get an error 404 - not found.

**Comment by eikek** [comment]
Hi @r4tze , can you post the logs from solr as well? You could try to re-create the index using the command line tool from [here](https://github.com/docspell/dsc). What were your actions that lead to this? Maybe an upgrade?

**Comment by r4tze** [comment]
Hi @eikek, here is the solr output:

`17.9.2021, 13:11:10 | WARN false |   | CoreContainer | Not all security plugins configured! authentication=disabled authorization=disabled. Solr is only as secure as you make it. Consider configuring authentication/authorization before exposing Solr to users internal or external. See https://s.apache.org/solrsecurity for more info
17.9.2021, 13:11:10 | WARN false |   | MetricsCollectorHandler | Solr loaded a deprecated plugin/analysis class [org.apache.solr.handler.admin.MetricsCollectorHandler]. Please consult documentation how to replace it accordingly.
17.9.2021, 13:11:10 | WARN false | x:docspell | SolrConfig | solrconfig.xml: <jmx> is no longer supported,&#8203; use solr.xml:/metrics/reporter section instead
17.9.2021, 13:11:11 | WARN false | x:docspell | AbstractSpatialPrefixTreeFieldType | FieldType SpatialRecursivePrefixTreeFieldType does not allow omitNorms to be specified in schema,&#8203; hardcoded behavior is omitNorms=true
17.9.2021, 13:11:11 | WARN false | x:docspell | AbstractSpatialPrefixTreeFieldType | FieldType SpatialRecursivePrefixTreeFieldType does not allow omitTermFreqAndPositions to be specified in schema,&#8203; hardcoded behavior is omitTermFreqAndPositions=true
17.9.2021, 13:11:11 | WARN false | x:docspell | AbstractSpatialPrefixTreeFieldType | FieldType SpatialRecursivePrefixTreeFieldType does not allow termOffsets to be specified in schema,&#8203; hardcoded behavior is termOffsets=false
17.9.2021, 13:11:11 | WARN false | x:docspell | AbstractSpatialPrefixTreeFieldType | FieldType SpatialRecursivePrefixTreeFieldType does not allow termPositions to be specified in schema,&#8203; hardcoded behavior is termPositions=false
17.9.2021, 13:11:11 | WARN false | x:docspell`

Till now, I was not able to configure the dsc. But I can not recreate the index from GUI. 
I think it did not work from the beginning. I made a fresh install on a dedicated server without an upgrade.

**Comment by eikek** [comment]
Hi @r4tze - I don't see anything useful in the logs sadly :/. I never came across the `AbstractSpatialPrefixTreeFieldType` - it is not used in docspell, so this looks a bit suspicious. Are you using the docker setup? What solr version is this? Are these the logs at the time you made the search request?

If your wondering - i edited your posts (hope that's ok) to format the log output. Anything you want to show verbatim (like log output), put it inside three single quotes - like ` ``` <newwine> output <newline> ``` `

**Comment by eikek** [comment]
Regarding dsc, you can try running it this way (doesn't need a config file):

```
dsc -d https://your.docspell.url admin -a 'your-admin-secret' recreate-index
```
You need to add some secret to the config file to enable the "admin endpoint". More [here](https://docspell.org/docs/configure/#admin-endpoint).

**Comment by r4tze** [comment]
Thanks for editing! I'm still learning the proper ways to open issues in GitHub. :-)

I managed to execute the command. And I get a "success"as return.  
The log of the rest server:
```Sep 21 08:51:38 mydocs docspell-restserver[4199]: [io-compute-0] INFO  d.b.o.OFulltext - Re-index all.
Sep 21 08:51:38 mydocs docspell-restserver[4199]: [io-compute-0] DEBUG d.j.c.JoexClient - Notify joex at http://localhost:7878/api/v1/notify
Sep 21 08:51:38 mydocs docspell-restserver[4199]: [io-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/admin/fts/reIndexAll
Sep 21 08:51:38 mydocs docspell-restserver[4199]: [io-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK```

I made a fresh install without docker and installed solr from the .gz archive. Then I created a core with the `bin/solr create -c` command. I will search for the `AbstractSpatialPrefixTreeFieldType` error. Will see what I will find.
Thanks for your help! I really like your product!

**Comment by eikek** [comment]
> Thanks for editing! I'm still learning the proper ways to open issues in GitHub. :-)

No worries! 

When you run the admin command; does solr logs show more error messages? If you find some more stuff in solr logs, just post it here. Really strange right now to me :-/

**Comment by r4tze** [comment]
@eikek 
I think I found something useful to get to the root of the problem. this is the Solr Log, when I try to recreate the index.

[Solr.log](https://github.com/eikek/docspell/files/7232032/Solr.log)

**Comment by r4tze** [comment]
I solved the problem by recreating the solr-core. I did this in the solr user context. 
After that, everything works perfectly.

**Comment by eikek** [comment]
Hi @r4tze , thanks for the update! I would have proposed the same thing, as the logs didn't give me any better clue. Glad it's working now. Deleting and re-creating the core should always work, but it's right that you must do that as the solr user.
