### ISSUE TITLE
Download of multiple Documents by Webfrontend

### ISSUE THREAD

**Issue by Igel18** [eikek/docspell#1093]
As now it is possible to download a singel document. As well it is possible to get multiple documents by the cli. 
But it would be nice to download multiple documents (which are selected) by one click out of the UI. 
Perpaps as ZIP File to the Download folder. The ZIP could have multiple Folders like in Docspell defined.

**Comment by Igel18** [comment]
An other idea is to have a functionality to synchronize (one way) with an defined webdav server like nextcloud.

**Comment by bytec77** [comment]
The download of multiple files via the gui would be very nice.
