### ISSUE TITLE
"Major" Version upgrade

### ISSUE THREAD

**Issue by creatvty** [eikek/docspell#1130]
Hey everyone.

I have a docker docspell (love it) setup and I'm quite happy with how it's currently running. I imported already lots of documents there and it's running smoothly.
The issue is, my version is getting a little old (0.20.0) and I would like to update.

With the lots of changes though I would prefer to have a stable backup of the setup. I read a little around and there are some mentions of backing up the sql database but there is not a lot of information about how to do that or how to restore correctly.
Since I put a lot of work into maintaining this document base it is quite dear to me.

I would be glad if there would be some guidance - or a tool even - for myself (and probably others) to upgrade safely.

Thanks in advance for your help.

**Comment by creatvty** [comment]
Awesome, thanks a lot. I will try it out!

**Comment by eikek** [comment]
I added a "backup" section to the docker-compose docs [here](https://docspell.org/docs/install/docker/#backups) - The upgrade can then be done by stopping containers, starting only the db container, running the backup command and then upgrade.
