### ISSUE TITLE
Email import is broken

### ISSUE THREAD

**Issue by wallace11** [eikek/docspell#1140]
Hey there.
I'm using the email import feature with "Only import e-mail attachments" and no additional file filtering.
Running this on emails with pdf attachments, and the result is an .eml file that's being imported.
This used to work fine, but for some reason sometime around last month (September) it started acting like this. 
I'm using an all-Docker stack, so maybe an update to one of the containers screwed something up? 
Also on _some_ items I'm getting the following log error, and their status is "stuck":
```
BASE64Decoder: Error in encoded stream: needed at least 2 valid base64 characters, but only got 0 before padding character (=), the 10 most recent characters were: "=\r\n------="
```

Please let me know if there's any other information I need to provide.
Thanks.

**Comment by wallace11** [comment]
Thanks!
The imported item is a .eml file.
Firefox, for instance, is just prompting for downloading a file upon entering the item:
![image](https://user-images.githubusercontent.com/5497761/139509563-1f723c0b-4877-48ca-93a4-1b6d46976ec5.png)

**Comment by eikek** [comment]
Oh strange, it then could not get processed , maybe not even read. Do you maybe have a non-sensible example file to share?

**Comment by wallace11** [comment]
So I went to a government website and downloaded the first PDF that I could find and sent it to myself via email.
I tagged the email and initiated an import and... voila! An error!

The PDF is from the following URL: https://m.knesset.gov.il/Activity/Legislation/Documents/yesod6.pdf (please rename the file to "חוק-יסוד: הממשלה.pdf" before you send it to yourself, to make it extra "problematic").

This is the log of the import:

```
2021-11-03T19:29:00: ============ Start processing hello.eml ============
2021-11-03T19:29:00: Checking for duplicate files
2021-11-03T19:29:00: Creating new item with 1 attachment(s)
2021-11-03T19:29:00: Creating item finished in 17 ms
2021-11-03T19:29:00: Reading e-mail hello.eml
2021-11-03T19:29:00: Filtering email attachments with '*'
2021-11-03T19:29:00: Converting e-mail file...
2021-11-03T19:29:00: Job 7TLSm94hf.../wallace/process-item/Low execution failed. Retrying later.: BASE64Decoder: Error in encoded stream: needed at least 2 valid base64 characters, but only got 0 before padding character (=), the 10 most recent characters were: "0KJSVFT0Y="
```

Thanks!

**Comment by tobru** [comment]
I'm seeing the same error with 0.28.0. My workflow is to scan from a Brother ADS-2700W to E-Mail and let it import by Docspell. This used to work quite well, but now I also got this `BASE64Decoder` error.

It happens with all scans, tried several documents, but all fail.

**Comment by eikek** [comment]
Oh noes. I haven't had time to look at it sadly :/. You are also using the scan/import mailbox task? Or is it send "directly" (like using an internal smtp) to docspell?

**Comment by tobru** [comment]
It's the "Scan Mailbox" task.

**Comment by eikek** [comment]
Ok, I can reproduce it with the pdf from knesset.gov.il (tried some other test files where I couldn't reproduce it). I'll need to investigate, as I currently have no clue what's going on.

**Comment by eikek** [comment]
Hm… I think I fixed it. It only seems not possible that it worked in 0.27.0 - because this version also contains the bug. If you could test the nightly that is available shortly that would be great!

**Comment by wallace11** [comment]
@eikek Thanks for addressing this issue.
Unfortunately, I can't seen to get email scanning to run on nightly. Maybe it's because my nightly instance doesn't have ssl.
I guess we'll have to wait for the stable release, then :)

**Comment by eikek** [comment]
@wallace11 thanks for trying! no worries, I'll make a release soon and we see if it is fixed or if I have another take at it.

**Comment by wallace11** [comment]
@eikek 
I can confirm this issue is now resolved. 
I managed to import emails I couldn't import before.
Thank you :)
