### ISSUE TITLE
Migration issue on startup 'ERROR: relation "collective_password" already exists'

### ISSUE THREAD

**Issue by TheAnachronism** [eikek/docspell#1149]
I've already found this issue here: #1015 but I'm not sure if I should really just delete collective_password.

Also I have the stable releases for everything so I'm even more confused.

**Comment by TheAnachronism** [comment]
Error message in the logs of restserver

```
Exception in thread "main" org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1.27.0__collective_passwords.sql failed
--------------------------------------------------
SQL State  : 42P07
Error Code : 0
Message    : ERROR: relation "collective_password" already exists
Location   : db/migration/postgresql/V1.27.0__collective_passwords.sql (/opt/file:/opt/docspell-restserver-0.28.0/lib/com.github.eikek.docspell-store-0.28.0.jar!/db/migration/postgresql/V1.27.0__collective_passwords.sql)
Line       : 1
Statement  : CREATE TABLE "collective_password" (
  "id" varchar(254) not null primary key,
  "cid" varchar(254) not null,
  "pass" varchar(254) not null,
  "created" timestamp not null,
  foreign key ("cid") references "collective"("cid") on delete cascade
)
```

**Comment by eikek** [comment]
This is really strange. I don't understand why flyway fails when you only migrate from stable to stable versions.

I think you can drop this table - it would contain passwords to use for decrypting pdf files. Even if there would be some data in there, you probably have them somewhere else (all assuming you are the only/main user :)).

I would drop this table and then remove the corresponding changeset from the table `flyway_schema_history` (`delete from flyway_schema_history where version = '1.27.0'`). And then start one container and let it run the migrations. Flyway uses postgresql's advisory locks, so it shouldn't be a problem to run both containers, but to be more on the secure side, I'd start only one in this scenario. hth!

**Comment by TheAnachronism** [comment]
I did this but now I get the same error for the relation `item_share`
Did something completely go wrong with the migrations?

**Comment by Lucki** [comment]
> [ah, yes remove the entry analog to 1.27.0 and drop the "item_share" table](https://matrix.to/#/!XPBQozyvvbElwZbbOO:gitter.im/$6zjNiWNh5zGdjbIbcs1s0YdTigukA7V6LJ4lyMcCl8s?via=gitter.im&via=matrix.org&via=tbrnt.ch)

> [`drop table "collective_password"; delete from "flyway_schema_history" where "version" = '1.27.0';`](https://matrix.to/#/!XPBQozyvvbElwZbbOO:gitter.im/$e8tg1HKQ0ixFUeMnIihK7TQdCscVyCy4gQ2aQ-W1Sqo?via=gitter.im&via=matrix.org&via=tbrnt.ch)

I had the same problem. I know for sure I've updated the joex a few days before the restserver. Maybe that's why it has failed for me and is some kind of race condition.

Anyway, the second command I used was: `drop table "item_share"; delete from "flyway_schema_history" where "version" = '1.27.1';` adapted from the first error message to the second one.

**Comment by TheAnachronism** [comment]
mhh ok
But I wonder what is stored in item_share?
I don't want to delete tables were important data about my documents is stored.

**Comment by eikek** [comment]
the `item_share` table holds shared documents - a new feature in 0.28.0. If you haven't used it yet, it is probably empty anyways. 

Could it be that you updated just one container at some point? Both always should be the same version.

**Comment by TheAnachronism** [comment]
Might be possible but I'll delete the table too and see where it takes me^^

**Comment by TheAnachronism** [comment]
Mhh ok after deleting that table too everything seems to work again
Might have really been incompatible versions of two different containers, but I can't remember how that happened.

**Comment by eikek** [comment]
Yeah, it's not a good feeling when the migrations fail like that! I can't explain it. I tested with a few databases here, but the "real" data out there is always a bit different. The goal is definitely to make transitions from one stable version to the other work out of the box. I also try to do so for the nightlies, but it can happen that these are incompatible at times. Another thing to keep in mind is, that you can only ever go forward. For example: If you update to a later version (like the nightlies), and later going *back* to a stable release may corrupt the migration table. This must then be resolved as you did now, by reverting the changes and resetting the migration history table.
