### ISSUE TITLE
after standard installation in docker: docspell-consumedir container cannot connet to docspell-restserver

### ISSUE THREAD

**Issue by sir-andreas** [eikek/docspell#1161]
Hi, 

after installing docspell with the docker standard installation everything worked fine with one exception: The upload of documents over the consume directory creates an error. The docker log shows the following error:
`
Cmd: Watch: Uploading failed: An http error occurred: An error was received from http://docspell-restserver:7880/api/v1/open/integration/checkfile/scan_20211103_0007.pdf/9dbf79d6db75a476bc2ed8e71bd99b60c8b5b3128cc08bb9bfad05437517b199: HTTP status client error (404 Not Found) for url (http://docspell-restserver:7880/api/v1/open/integration/checkfile/scan_20211103_0007.pdf/9dbf79d6db75a476bc2ed8e71bd99b60c8b5b3128cc08bb9bfad05437517b199)!!
`

I can reach the server with a 
`ping docspell-restserver`

but when I curl to the mentioned URl the result is "Forbidden"

Any idea what could be the problem?

Thank you and best regards,
Andreas

**Comment by eikek** [comment]
Hi @sir-andreas , you need to create a sub-directory inside the consume directory with the name of your collective - this could have caused this error. Otherwise the tool doesn't know for which collective the upload is. If it's not this, we need to look again :)

**Comment by sir-andreas** [comment]
> Hi @sir-andreas , you need to create a sub-directory inside the consume directory with the name of your collective - this could have caused this error. Otherwise the tool doesn't know for which collective the upload is. If it's not this, we need to look again :)

This was exactly the problem. Thanks for the support!

**Comment by eikek** [comment]
I'm cosing these issuse, I think they are done from your side? If not, never hesitate to reopen or create new issues!
