### ISSUE TITLE
[Feature Request] notifications: allow custom field boolean in-/exclude

### ISSUE THREAD

**Issue by davidclemens** [eikek/docspell#1174]
We keep track of the state of our invoices via custom fields (booleans). For example: `is paid`, `is submitted to insurance`, `is refunded`, etc..

It'd be great to get notifications of invoices that will be due within +7 days where `is paid` is false (or is excluded, using the current terminology).

I hope this makes sense via this example.

Thanks for your work!

**Comment by eikek** [comment]
Makes absolutely sense, I'm using something similar with tags. I'm about to add a notification option that allows to specify any query, so you can define what you need.

**Comment by davidclemens** [comment]
That is great news! 
Thanks for the prompt reply as well.
