### ISSUE TITLE
[Feature Request] Allow saving filtered views

### ISSUE THREAD

**Issue by davidclemens** [eikek/docspell#1175]
The filters are powerful. I find myself using them a lot. I also often use the same combinations of filters. If I filter on many meta data fields it becomes tedious to reselect all the right combinations every time I need to.

I'd be great if one could save a such a filtered view (with a descriptive name) and be able to come back to it later by just clicking on  the name in the sidebar.

For example:
The saved filtered view called `invoices pending payment` could be defined with:
`Tag` == invoice AND `Concerning` == me AND custom field `is paid` == false.

This could also make notifications more versatile: E.g. notify if a document has a due date within +7 days and is part of the saved filtered view `invoices pending payment`.

This would also solve #1174 in a more general way.

Thanks for your work on Docspell!

**Comment by eikek** [comment]
Thanks, yes this is a feature that will come at some point!

**Comment by davidclemens** [comment]
Thanks for the swift reply. Looking forward to your implementation! Thanks again for the great work.
