### ISSUE TITLE
[Enhancement] Folder and Recursion support for mail importer

### ISSUE THREAD

**Issue by seijikun** [eikek/docspell#1197]
Hey! I'm currently looking into the mail importer functionality.
I have a large mail account with a recursive folder structure into which I sort my mails.

At the moment, the mail importer is implemented such that he directly takes the Folder-List provided in the ScanTask, and passes each of them to the server, to search for mails in it. For recursive folder structures, like:
```
Inbox
 |- Shops
   |- Amazon
     |- Computer
     |- Other Stuff
```

this function therefore surfaces implementation details of the mail server used. Since, due to the IMAP specification, mail servers can use different path separators (which is something that's normally abstracted by the mail client).

An example: The `dovecot` mail-server uses `.` as path separator, whereas `outlook` e.g. uses `/`. So the `Inbox/Shops/Amazon/Computer` folder from the shown folder structure would look like this in both servers:
- Dovecot: `Inbox.Shops.Amazon.Computer`
- Outlook: `Inbox/Shops/Amazon/Computer`

So it may make sense for docspell to abstract over this (enforce `/` and match against the paths the server returns?).
What I would personally also need is to support recursion. So: Passing the folder `Inbox/Shops` to the ScanTask, and let him import the entire folder structure filled with emails.

The easiest way to achive the latter is to download the list of mailboxes (folders) from the server, and interpret the folders the docspell-user specified in the ScanTask as regex, to match against the flattened paths from the server.
**Example:** A `dovecot` mailserver would return the following mailbox list for the structure above:
```
Inbox
Inbox.Shops
Inbox.Shops.Amazon
Inbox.Shops.Amazon.Computer
Inbox.Shops.Amazon.Other Stuff
```
So if folders provided in the ScanTask are interpreted as regex, the folder `Inbox\.Shops\..*` would match all of the paths below the Shops folder.

I grabbed a buddy of mine who knows Scala, and we're currently testing our luck. :)

**Comment by eikek** [comment]
Hi, that's awesome!

I think you're right regarding the folder separator for imap. I have to find out, how to determine it and then we can allow a few characters (for backward compat).

Regarding recursive folders: I can see the use for this. I also think we can get the complete list of folders to match against. Maybe it's better to use a glob pattern (there is already a `Glob` impl available). This is usually a bit easier to use than regexes, but less powerful ofc. It should also be backward compatible (giving just a folder matches exactly this string), like the regex.

If you have any other questions regarding code etc, you can ping me on matrix/gitter or here.

**Comment by seijikun** [comment]
> I think you're right regarding the folder separator for imap. I have to find out, how to determine it and then we can allow a few characters (for backward compat).

As far as I know, IMAP allows the separator to be different for each folder, so you can request a list of folders, and then it gives you a list of `<folder, separator>` pairs. Thus, JavaMail also provides this `getSeparator()` getter on `Folder` instances: [JavaMail API-Doc](javaee.github.io/javamail/docs/api/javax/mail/Folder.html#getSeparator--)

We are currently implementing a folder listing API in emil.

**Comment by eikek** [comment]
>Thus, JavaMail also provides this `getSeparator()` getter on `Folder` instances: [JavaMail API-Doc](https://javaee.github.io/javamail/docs/api/javax/mail/Folder.html#getSeparator--)

Thank you for the pointer! That's really nice, it can be added to emil easily then, I think. It wouldn't need a change it docspell. We can allow `.` and `/` for example and replace them with the actual separator



> The regex suggestion was only a cheap implementation suggestion. I think a simple "Recursive" checkbox, that tells docspell to traverse the folder tree, might make more sense. What do you think?

Good point. I actually like the flexibility of the glob, but it might be strange to other people and the most use case will be recursively traversing a folder. So I think a checkbox is the better choice. We can use a glob underneath, though. For example, use a glob for the api but a checkbox in the ui. wdyt?



> We are currently implementing a folder listing API in emil.

That's great! Already saw the pr, thanks!
