### ISSUE TITLE
viewerjs preview not updated after switching to next document in edit view (mobile devices) 

### ISSUE THREAD

**Issue by alpha197** [eikek/docspell#1210]
Good morning,

I am just testing docspell in latest docker version (coming from paperless-ng).  Great piece of software!

I noticed that the pdf preview (using viewerjs) doesn´t update on my Ipad (Chrome) and on my Android smartphone (also using Chrome) when you switch between documents with the arrow buttons in edit view. That means that I can switch between the documents but viewerjs still shows the first opened document.

On my laptop (Chrome) the preview updates as expected.

Thank you for your efforts!
alpha197

**Comment by eikek** [comment]
Hi @alpha197 thank you for reporting this. Unfortunately, I cannot reproduce this on my android device using my stock browser :( Which android version are you using? Did you try a different browser, like is this special to chrome?

**Comment by alpha197** [comment]
On my android device (Xiaomi Mi9Lite) I can reproduce this with Android 11 using latest Chrome. I can´t test another browser on this phone because I have deinstalled other browsers...
On my Ipad (iPadOS 15.1) I observe the problem with Chrome AND Safari. With both browsers the preview stucks on the firstly edited document.

**Comment by eikek** [comment]
Thank you, I'll try to find another device or browser.

**Comment by davidclemens** [comment]
I can confirm this behaviour on my desktop as well:

OS: macOS 10.15.7 (Catalina)
Browser: Safari 15.1
Docspell: 0.29.0

I use the browsers native PDF viewer.

In addition to what alpha197 reported the preview also does not update if I go back to the overview page and click on another document to see its detailed view.

Additional observations:
- The correct preview is shown again, if the page is reloaded.
- When I download the PDF from the detailed view page, it downloads the correct PDF even though the wrong preview is shown.
- All other metadata is also correct even though the wrong preview is shown
- This behaviour occurs for all three settings available (`User Settings` > `UI Settings` > `Item Detail` > `Browser-native PDF preview`
- Clearing the browsers cache does not help
- First occurred after upgrading to 0.29.0
- I also have Chrome installed and there it works flawlessly

Thanks for looking into this!

**Comment by eikek** [comment]
> In addition to what alpha197 reported the preview also does not update if I go back to the overview page and click on another document to see its detailed view.

Oh no! This is getting worse. I don't understand why the browser is not updating its view, when the url of the embed element change. On firefox and chromium I cannot reproduce it.

If someone has an idea, why some browsers don't update, please let me know.

@davidclemens Are you sure this worked in 0.28.0? In this version I exchanged `iframe` for `embed` in the pdf view (#1099 ) which _could_ be related.

**Comment by davidclemens** [comment]
> @davidclemens Are you sure this worked in 0.28.0? In this version I exchanged `iframe` for `embed` in the pdf view (#1099 ) which _could_ be related.

Good call. I rechecked and I actually skipped `0.28.0`. So the issue did not exist for me in `0.27.0`.

**Comment by eikek** [comment]
Thank you! I'll look into it and see what can be done. I found now a device (some older tablet) where I can reproduce it at least.

**Comment by bytec77** [comment]
Here is the same problem on Safari in IOS and MacOS Newest release is installed.

**Comment by eikek** [comment]
Looked at it a bit. It seems to be a browser bug that is affecting the `embed` element. Safari on OSX doesn't work with `embed`, but it works with `iframe` and `object`. Firefox and chrome work on my machine without problems. In #1099 we changed from `iframe` to `embed` for better compatibility with firefox. I don't know if using `object` is a good idea in general. It seems to work on browsers that I tested. I think I'll first change the "fallback view" to be an iframe. This allows the user to at least choose. For the general solution, I'm currently not sure - I'm sure I don't want to have browser-dependent code.

I added a simple html file that you can use to test this on your device, if you want.
[switch-pdf.html.gz](https://github.com/eikek/docspell/files/8092685/switch-pdf.html.gz)

**Comment by kgatz** [comment]
I have the same issues on my iPhone/iPads. 
The attached switch-pdf.html seems not to be a good show case - it works on the very same mobile browser.

**Comment by eikek** [comment]
Oh that is really strange. I tried it on a macbook with safari. But mobile is probably a bit different. Thank you for the feedback!

**Comment by eikek** [comment]
For safari and other browsers with that bug, it is now possible to use the option "cross browser view", which uses pdfjs and an iframe.

**Comment by kgatz** [comment]
I just updated to 0.33 but unfortunately I still can reproduce the issue on my iPad.
Even though I changed to cross-browser mode ...

**Comment by eikek** [comment]
Oh that's unfortunate. I don't have an ipad, so I can't look at this. I tried with a macbook and some samsung tablet that showed the same behavior using stock browser (works fine with firefox / chromium etc). One little hope: could be the browser cache be an issue? Would be good to know whether the element is `embed` or `iframe`.

**Comment by kgatz** [comment]
Just want to update - my bad, updated one instance and tested on the other.
It was working fine right from the beginning - layer 8 issue. 
Sorry for the confusion

**Comment by eikek** [comment]
No worries! Thanks for the update, glad it's working.
