### ISSUE TITLE
Add TZ=Europe/Berlin to restserver service

### ISSUE THREAD

**Issue by nekrondev** [eikek/docspell#1234]
There is a discrepancy between `restserver` and `joex` service configuration in the current `docker-compose` example file (https://github.com/eikek/docspell/blob/6613da92a4c3ac0bd983848eacd82fa33b452e28/docker/docker-compose/docker-compose.yml#L47).
`joex` service sets timezone to `Europe/Berlin` (UTC+1) whereas `restserver` service uses default UTC (no timezone set).

If you import and edit a document item the meta data for `created` and `last modified` will show normalized timestamps (UTC) but due to different service timezones used the `last modified` normalized timestamp will be UTC-1.

![image](https://user-images.githubusercontent.com/13854802/147267699-41679215-1e90-44fd-aefb-0166610dfa99.png)

**Comment by eikek** [comment]
Oh good catch, thank you! We should set it to some value for both.
