### ISSUE TITLE
Question: Multilanguage support?

### ISSUE THREAD

**Issue by stepanov1975** [eikek/docspell#1240]
Hi.
First of all, I just installed Docspell and I want to say that it looks very impressive, with a lot of interesting functions.
I used paperless and it is nice, but development seems to be stagnant. So, I want to move to Docspell.
I went over documentation but it is unclear regarding language support. I found documents language can be set under collective settings, but what if I have documents in multiple languages?

**Comment by eikek** [comment]
Hi @stepanov1975 , thank you! Multi-language documents are possible, the language can be specified each time when uploading a file. if it is not given, then the default language set in the collective settings is used. For example, on the upload page in the webapp. Or you can create upload URLs (under _Collective Profile -> Sources_) and set the language per upload URL. The you can use different URLs for different languages.
