### ISSUE TITLE
consumedir 404

### ISSUE THREAD

**Issue by woessmich** [eikek/docspell#1253]
Hi

I am seeing a similar 404 error as in #984 and #1244:
```
Got: /opt/docs/admin/test.pdf
Cmd: Watch: Uploading failed: An http error occurred: An error was received from http://docspell-restserver:7880/api/v1/open/integration/checkfile/admin/73b317a9647d2d61e051f1fd24a19445cbe165caa4ba23fbed83b32f76e1ce50: HTTP status client error (404 Not Found) for url (http://docspell-restserver:7880/api/v1/open/integration/checkfile/admin/73b317a9647d2d61e051f1fd24a19445cbe165caa4ba23fbed83b32f76e1ce50)!!
```

Logs in restserver also show the error:
```
level=INFO  thread=io-compute-0 logger=o.h.s.m.Logger message="HTTP/1.1 GET /api/v1/open/integration/checkfile/admin/73b317a9647d2d61e051f1fd24a19445cbe165caa4ba23fbed83b32f76e1ce50"
level=INFO  thread=io-compute-0 logger=o.h.s.m.Logger message="HTTP/1.1 404 Not Found"
```

I am using admin/admin as collective/user and I have created the subfolder admin in /opt/docs/
This is where the files are.
I noticed that it worked well and all of a sudden it does no longer after it once tried to upload a hidden directory @eaDir sitting in the folder instead of a file. (Not usre it is related, though). I am using docker on a Synology diskstation.

I tried dsc v0.5.0 as well as latest, it does not make a difference here.

Edit:
One more thing: I found that (I believe it is by default) the setting "Enable integration endpoint" in the collective settings is off.
I now activated it and the files are now uploaded.
Is this related?

And:
Thank you so much for this great tool. It does everything I was looking for after trying mayan and a couple of others. So, I am really looking forward to using it...

**Comment by eikek** [comment]
Hi @woessmich thank you! So you found exactly the problem: a 404 indicates that the integration endpoint setting is not active. The hidden directory is not related. It's a bit inconvenient with having first to activate this endpoint explicitely, but I figured it's better as a default than have it enabled without "knowing" it.

**Comment by woessmich** [comment]
Hi @eikek OK, thank you for the quick reply and confirmation.
From the error message and manual it is really hard to deduct that this is the problem. On top of that, it worked for me in the beginning without this being active. I have no clue why.
Maybe the next used will find this entry ;-)
Thank you again for the fantastic work!

**Comment by eikek** [comment]
Hi @woessmich thanks for getting back! I guess this was a bug when it was working without being active. And you are right, this can be improved - at least within the docs! I'll add a note in the docs later. On a second thought, it might also be ok to have this active by default - the user still needs to enable it globally in the config file.
