### ISSUE TITLE
"Group by Month" has no effect in fulltext-search-results

### ISSUE THREAD

**Issue by monnypython** [eikek/docspell#1255]
As already discussed in #980, the results of the full text search (content:SearchString) are not grouped.
I had forgotten it again and was a bit confused when I expected this by activating the new "Group by Month" checkbox until I remembered it again.
Since the option here has no effect to the Results (except for the display of the "Results" header) it should be hidden or deactivated in this situation.

![image](https://user-images.githubusercontent.com/42573701/148217095-32e5027d-5a29-4772-9842-da3df2f23433.png)

**Comment by eikek** [comment]
Ah right, thank you! I constantly forget about this, because I'm not using it a lot :)
