### ISSUE TITLE
[Feature Request] Add information to E-Mail notifications

### ISSUE THREAD

**Issue by davidclemens** [eikek/docspell#1258]
As I stated before, I'm loving the new notification capabilities.

Right now, I'm mostly relying on E-Mail and set up several queries that I want to get notified about each morning.

The general template of those mails is:
```
Subject: Your items

Hello <user>,

this is Docspell informing you about your next items.

<list of documents matching the query>

Sincerely yours,

Docspell
```

For me I noticed that this is not enough information to know what the items listed in that mail have in common: Are the all due within X days? Are the all invoices that have not been payed yet? Are the all the `Inbox` items? You get the gist...

So it would be nice, for a start, to maybe add the `Summary` that's entered in the notification definition in `User Settings > Notifications > Webhooks/Due Items Query/Generic Queries > <some query> > Summary` to the E-Mail subject or body.
I hope this is relatively easy to add. 

As a next step, it would maybe be possible to edit the default E-Mail template for each query using variables.

Thanks for your work on this!

**Comment by eikek** [comment]
Yes, I can totally understand! I knew that there has to be some way to customize this at some point. I was too lazy to really think about it back then and just started with a simple approach. I like the idea with a summary field that is injected into the mail! This can be inserted right after the "Hello user", replacing the current sentence. An editable template would also be nice of course, but it is then also more difficult to use (and more work :)).
