### ISSUE TITLE
[feature request] nested exports

### ISSUE THREAD

**Issue by mtettke123** [eikek/docspell#1262]
Hi,

trying to understand the export command and having a discussion [here](https://github.com/eikek/docspell/issues/1259), this is to write down how I wish exports would be possible. My objective is to generate a (nested) directory structure, that is easy to sync and can be accessed without docspell, something like

`"{correspondent}/{document_type}/{created_year}-{created_month}-{created_day} {title}"`

1. For this, there should be an export mode like `with-structure="{correspondent}/{category:document-type}/..."` where you can specify how exactly documents are exported using the placeholders like in searches.
2. As I don't need the metadata (DB is backuped anyway), an option `--without-metadata` would also be helpfull to don't export data I don't need here.
3. An option like `--no-subdir-on-single-file` (or maybe `--flat` or `--direct-link-on-single-file`?) could link entities, that have only one PDF attached (>90% in my use case) directly.
4. As far as I understand the documentation, only the original files, not the processed PDF/A-files are exported. A switch to change this behaviour would be great.

Just ideas and wishes here.

**Comment by eikek** [comment]
Thank you - this all makes sense and would be a nice addition! All points can be addressed individually, if someone likes to pickup some of them, would be great! Note that this concerns the [dsc](https://github.com/docspell/dsc) command line utility, which is written in Rust.

**Comment by eikek** [comment]
Hey! I created single issues in the docspell/dsc repository, so I'm closing this one. Thanks again for your input!
