### ISSUE TITLE
Improve working with notifications

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#1293]
Currently, the settings for a notification "channel" must be supplied on each notification task. Then one task can only send to one notification channel. I think it would be better, to manage channels separately (like it's done for e-mail connection settings) and then allow a task to select multiple channels.

**Comment by TheFehr** [comment]
I'd love if we could support more channels as well.
Another project I use, used this: https://github.com/caronc/apprise for adding many many more notification receivers. Sadly it is in python so not a plug-n-play solution with scala but I found this: https://github.com/caronc/apprise-api which offers a rest API for the apprise code.

**Comment by eikek** [comment]
Hi @TheFehr - this project looks really nice, thanks for sharing! Would you mind to create a separate issue? In general I'm open to add other notification channels (admittedly I'm not much in favor for adding proprietary/closed services). If the rest api is easy to use (and it seems so from quick checking the readme), it isn't hard to add.
