### ISSUE TITLE
[documentation] Alternative upload directly from the browser or email client

### ISSUE THREAD

**Issue by gandy92** [eikek/docspell#1295]
I've just tried to configure the firefox webextension as suggested in the documentation. For some reason I couldn't get it running and I didn't want to install firefox-esr just for more tests. Instead, an alternative approach came to mind that at least works on a Linux system. In case this is interesting for others and in lack of a more appropriate channel, I'd like to share it here.

1. Create and activate a source in your collective (in this example MYCOLL); note that path to the file upload (the one with `/api/v1/open/upload/item/`)
2. Create a file `docspell-upload-MYCOLL` with the following content (replace `UPLOAD_PATH` with the actual path): 
```
#!/bin/bash
logger -t docspell_upload -- Docspell upload to MYCOLL: "$*" $(
curl -s -XPOST -F file=@"$1" UPLOAD_PATH
)
``` 
3. Make it executable: `chmod 755 docspell-upload-MYCOLL`
4. Create a file named `docspell-MYCOLL.desktop` with the following content (note that you need the full path to `docspell-upload-MYCOLL`): 
```
[Desktop Entry]
Exec=PATH_TO_docspell-upload-MYCOLL %F
MimeType=application/pdf;application/x-zip;application/x-zip-compressed;application/zip 
Name=Docspell Upload (MYCOLL)
NoDisplay=true
Type=Application
```
5. Place the file `docspell-MYCOLL.desktop` in `$HOME/.local/share/applications/`
6. Configure your browser or mail-reader actions for pdf and zip: They should always ask what to do rather than opening a link or attachment with the standard application or save it to disk by default. Actually, always opening a pdf in the browser is fine, if this allows to later save the viewed file.

Now, when clicking on a file link or attachment, the browser or email client should ask what to do. You then should be able to choose "Docspell Upload (MYCOLL)" from the list, which will upload the file to your collection. 

If anything goes wrong, you can monitor the server response with the command `journalctl -f -t docspell_upload`

**Comment by eikek** [comment]
Hi @gandy92 thank you very much! I think it's best to remove the firefox extension alltogether. I stopped using it myself a long time ago I have to admit. I'm now using `dsc watch` on all our notebooks. So we simply download something in the watched directory and it will be send to docspell. Your way here is very neat. You could replace `curl` with `dsc` for a slightly nicer command (only nitpicking here). The firefox extension was created very early before this cli tool existed. 

I pinned this issue for better visibility. But your point about a missing appropriate channel for things like this is also valid! I think we could for example create a section on the website, like "Tips & Tricks" - or a better title where pages could be added like in a blog. wdyt?

**Comment by wallace11** [comment]
+1 for using `logger` and `curl`. I think it's a great alternative to `dsc` for people like myself who like to keep the number of programs on their system as small as possible.

I think that @eikek 's idea for creating a tips&tricks section on the website is a good idea also. It can potentially bring in more tinkerers who fancy the added value that Docspell brings to the table with its awesome API. I truly think we have the better edge here over other self hosted solutions "competing" in the same space.

**Comment by vakilando** [comment]
@gandy92 Indeed a cool feature!
I got it working with Thunderbird and Firefox.
Vivaldi - my preferred browser - just opens a _"save as_" and "_open_" option and then wants to download the pdf-file.

Another method is to (also) put the _docspell-MYCOLL.desktop_ file on the desktop an just drag'n drop the file on the icon!

Nevertheless I mostly prefer to use the watch folder (dsc) as @eikek and the automatic e-mail import.
In the watch folder I have structured directories, so in case my docspell crashes (yes I have regular backups of the files and the database) and should not be recoverable I have most documents stored in an "old fashion way".... 

The idea to create a tips & tricks section on the website is nevertheless a good idea!

**Comment by eikek** [comment]
> I think it's a great alternative to `dsc` for people like myself who like to keep the number of programs on their system as small as possible.

Absolutely agree, I also try to keep things I need at a minimum. Wanted to mention it mostly for completeness and because the ff extension is so old it didn't exist back then. But using curl is of course great!

Thanks all for comments; it is always interesting to hear how others are using docspell and organize their documents in general. So I will remove the firefox extension and create a section on the website - or do you prefer a wiki directly on github? I for one don't care that much; tending to prefer slightly the website because it is then in git and all in one place. Creating new posts shouldn't be hard, just do a PR against `current-docs` branch. It will be deployed by github once it is merged. But it's probably still a bit more involved than editing a github wiki…

**Comment by wallace11** [comment]
> So I will remove the firefox extension and create a section on the website - or do you prefer a wiki directly on github?

Since the website is also open source, then I think it'd be better to do it there. 
Creating multiple sources of documentation always tends to confuse people.

**Comment by gandy92** [comment]
I also vote in favour of the website - this at least allows for you to perform some moderate moderation :smile: - while hopefully not adding too much to your workload.
And indeed, while I use my proposed method with curl to add documents I receive by email or download from online sources, I also heavily utilize the watch-folder. Mostly for (finally) adding all my historic paper documents, but due to how my scanner works, I have to have a rather large delay on the watch-folder. Thanks @vakilando for the hint on drag'n'dropping, sounds like an interesting variant for sure!

**Comment by eikek** [comment]
Hi @gandy92 - I added this on your behalf to the new "blog" on the website: https://docspell.org/blog/alternative-upload-from-browser/ I hope that is ok, let me know otherwise. Of course, feel free to add more or do corrections :)

**Comment by gandy92** [comment]
Thank you @eikek I like that!
