### ISSUE TITLE
Excessive events while editing custom_field

### ISSUE THREAD

**Issue by gandy92** [eikek/docspell#1299]
I am currently experimenting with processing documents externally, e.g. to split up a multi-document PDF that has already been submitted to docspell. The basic idea is to have a separate piece of software (a python script) subscribe to a gotify channel that receives `SetFieldValue` from docspell whenever a custom_field is changed. If the custom_field has a certain designator, e.g. "split_document", the field value would be interpreted as an instruction on how to split up the document, e.g. "1-2,3-4,5-10" would result in 3 new documents with pages 1-2, 3-4 and 5-10, which then would be submitted to docspell.

For starts, I implemented a simple websocket client that listens to gotify and AFAICT every information I need to perform the task is present in the received message events. However, I noticed that while typing in the page ranges using the webclient, an event is sent following almost every keystroke (and I already tried to type faster than usual):
```
/home/andy/prg/pydocspell/venv/bin/python /home/andy/prg/pydocspell/docspell/automate.py
{"id":512,"appid":2,"message":"*Dokument zerlegen*  was set to '1' on [`Dokument 1-2.pdf`](http://localhost:7880/app/item/2UnF4jVUigW-cD22BzgGx9M-sYdFq8cK9ph-LTYMSy1vVsj).","title":"SetFieldValue (by *andy*)","priority":0,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-01-19T14:48:51.306258882Z"}
{"id":513,"appid":2,"message":"*Dokument zerlegen*  was set to '1-' on [`Dokument 1-2.pdf`](http://localhost:7880/app/item/2UnF4jVUigW-cD22BzgGx9M-sYdFq8cK9ph-LTYMSy1vVsj).","title":"SetFieldValue (by *andy*)","priority":0,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-01-19T14:48:56.477252785Z"}
{"id":514,"appid":2,"message":"*Dokument zerlegen*  was set to '1-2' on [`Dokument 1-2.pdf`](http://localhost:7880/app/item/2UnF4jVUigW-cD22BzgGx9M-sYdFq8cK9ph-LTYMSy1vVsj).","title":"SetFieldValue (by *andy*)","priority":0,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-01-19T14:48:57.000330372Z"}
{"id":515,"appid":2,"message":"*Dokument zerlegen*  was set to '1-2,' on [`Dokument 1-2.pdf`](http://localhost:7880/app/item/2UnF4jVUigW-cD22BzgGx9M-sYdFq8cK9ph-LTYMSy1vVsj).","title":"SetFieldValue (by *andy*)","priority":0,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-01-19T14:48:57.661721753Z"}
{"id":516,"appid":2,"message":"*Dokument zerlegen*  was set to '1-2,3-' on [`Dokument 1-2.pdf`](http://localhost:7880/app/item/2UnF4jVUigW-cD22BzgGx9M-sYdFq8cK9ph-LTYMSy1vVsj).","title":"SetFieldValue (by *andy*)","priority":0,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-01-19T14:48:58.886409706Z"}
{"id":517,"appid":2,"message":"*Dokument zerlegen*  was set to '1-2,3-4' on [`Dokument 1-2.pdf`](http://localhost:7880/app/item/2UnF4jVUigW-cD22BzgGx9M-sYdFq8cK9ph-LTYMSy1vVsj).","title":"SetFieldValue (by *andy*)","priority":0,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-01-19T14:48:59.372436758Z"}
{"id":518,"appid":2,"message":"*Dokument zerlegen*  was set to '1-2,3-4,' on [`Dokument 1-2.pdf`](http://localhost:7880/app/item/2UnF4jVUigW-cD22BzgGx9M-sYdFq8cK9ph-LTYMSy1vVsj).","title":"SetFieldValue (by *andy*)","priority":0,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-01-19T14:49:00.173132721Z"}
{"id":519,"appid":2,"message":"*Dokument zerlegen*  was set to '1-2,3-4,5-' on [`Dokument 1-2.pdf`](http://localhost:7880/app/item/2UnF4jVUigW-cD22BzgGx9M-sYdFq8cK9ph-LTYMSy1vVsj).","title":"SetFieldValue (by *andy*)","priority":0,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-01-19T14:49:02.628843854Z"}
{"id":520,"appid":2,"message":"*Dokument zerlegen*  was set to '1-2,3-4,5-10' on [`Dokument 1-2.pdf`](http://localhost:7880/app/item/2UnF4jVUigW-cD22BzgGx9M-sYdFq8cK9ph-LTYMSy1vVsj).","title":"SetFieldValue (by *andy*)","priority":0,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-01-19T14:49:03.27805907Z"}
```
Obviously each of the events originates from the webclient issuing a call to the docspell Rest-API. 

In my external tool, I can work around this easily, I'm just wondering if it is the intended behaviour or if it should be fixed, e.g. by calling the Rest-API only after the input field looses it's focus or when the enter-key is pressed. - Not that I'd know how to fix it, I'm still struggling with that base_path topic :roll_eyes:

**Comment by eikek** [comment]
Hi @gandy92 this sounds really awesome! 

Sadly this is the current state - but I'm not happy with this. The server sends this notification on each call of the endpoint (which is ok I think) and the client has some throttling but only 200ms ([here](https://github.com/eikek/docspell/blob/44e599dc86669e2f36373493f2e2b190136373d5/modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm#L1776)). But maybe it's not working correctly, it shouldn't fire on every stroke actually. Perhaps we can increase the delay more and additionally save when pressing enter…?

On another note: for this task maybe using a "HTTP Request" channel is better? It will give you a JSON payload that is more convenient to parse and use in programs. But then you need a server instead of the websocket client… 🤔

**Comment by gandy92** [comment]
Hi @eikek you're right, I was so enthusiastic with that gotify approach I didn't even think of first looking at the other webhooks. The json structure is much more suitable of course. And I have no trouble setting up a miniature webserver accepting the HTTP Request.  Thanks for pointing this out :smile:
