### ISSUE TITLE
Improve the sorting of tags on the menu on the left side

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#1318]
When searching for documents with specific tags by clicking on a tag in the dropdown on the left side, the tag gets a check (tick mark) and stays visible almost on top in dependency of the quantity of documents with this tag (right?). Thats OK.
When then clicking on that tag again it gets excluded from the search and mostly disappears in dependency of alphabetical order and quantity of documents with this tag (right?).
Now it's a bit difficult to remove the exclude mark, because one has to search (filter) for this tag to find it again.
It would be better if the order of tags is as follows:
1. checked tags
2. excluded tags
3. tags with items that share one of the checked tags ordered by quantity
4. tags with items that do not share one of the checked tags ordered by quantity

**Comment by eikek** [comment]
Thanks! Yes this is indeed very strange behavior, I think it is an regression, have the impression it was a bit different at some point.

**Comment by eikek** [comment]
It very likely is a consequence of #856. Before it simply kept the initial ordering, which I think is not bad, least surprising imho. I think point 3 and 4 are not possible given the data. I only know the overall usage count of a tag.

**Comment by vakilando** [comment]
> I think point 3 and 4 are not possible
That's ok.
Point 1. and 2. are most important.
