### ISSUE TITLE
[Bug] E-mail notification customised message not shown in UI

### ISSUE THREAD

**Issue by davidclemens** [eikek/docspell#1324]
The custom e-mail message that one is now able to add to notifications (thanks for that feature!) seems to be saved but is not shown in the UI when the same notification (generic query) is edited again.

<img width="1242" alt="Screenshot 2022-01-28 at 20 48 32" src="https://user-images.githubusercontent.com/43437141/151611962-23d28705-a74f-4da2-a651-f1aa0df1e158.png">

Thanks for looking into this!

**Comment by eikek** [comment]
Ah yes, this has been fixed already in #1317 - you can test with the nightly docker images if you want

**Comment by davidclemens** [comment]
Sweet, thank you!
