### ISSUE TITLE
Login with docker-compose only possible if collective equals username

### ISSUE THREAD

**Issue by cwilhelm** [eikek/docspell#1333]
I have used the docker-compose setup with traefik as reverse proxy. Creating users via frontend is working, the user and collective is created in the database. However a followup login is only possible if the collective is equal to the username.
I also tried with adding a user to the collective later on, I cannot login with this user.

**Comment by eikek** [comment]
Hi @cwilhelm , how do you login with a user that is not equal to the collective name? Do you use `<collective-name>/<user-name>` pattern for the login?

**Comment by majso** [comment]
Thanks, I was going mad why log in is not working. There is no message saying that Collective ID have to be the same as username.

**Comment by eikek** [comment]
Oh no, this is not the case. The collective and user name don't need to be the same.  The quickstart states that you should name them equally to get started quickly, but there is more to it which can be found in the docs. Your login name is `collective/user`. So if your collective is named `family` and your user in that collective is `max` then you need to login with `family/max` (and your password). But in case both names _are_ the same, you can omit one. It is explained here: https://docspell.org/docs/intro/#collective

**Comment by cwilhelm** [comment]
You are right, sorry about that. collective/user is working.
