### ISSUE TITLE
Add Polish to document languages

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#1345]
Original request: https://github.com/eikek/docspell/issues/488#issuecomment-1030413213

In order to recognize dates, I need the Polish date pattern(s) used in documents. I also need spelled out month names. Here are two issues for other languages as an example: #948 and #679

**Comment by eikek** [comment]
Hi @maciekb since you opened the original request: may I ask you for some information? I would need
- Polish date patterns that are used most on documents
- Polish month names
Thanks!

**Comment by mimek** [comment]
Hi @eikek ,
https://www.localeplanet.com/icu/pl-PL/index.html

Most used polish date patterns are Date.3 and Date.1 (second one quite rarely).
Polish months names are also there.

Thanks for all the job!
