### ISSUE TITLE
[UI] - Long text in dashboard-card

### ISSUE THREAD

**Issue by monnypython** [eikek/docspell#1357]
As you can see, there is a UI-problem in new dashboard card when it is set to small for long Text.

Maybe you could truncate the text to fit the space available like **"ThisIsAveryLongT..."**.
![image](https://user-images.githubusercontent.com/42573701/153061388-3a52a066-0b2a-478f-88a0-a9e2eca06db9.png)

**Comment by eikek** [comment]
Thanks! I think we can just let it wrap or truncate it and print dots `…`. Also I think the number of columns should be reduced for mobile. Maybe just render the first two and last column on small screens.

**Comment by eikek** [comment]
Do you have long organization names without any whitespace? I saw that it breaks but only on word boundaries. It is possible to use break-all so it doesn't try to preserve these boundaries, but this also doesn't look so nice. But I guess a solution to be safe.

**Comment by monnypython** [comment]
As far as I can see, all long organizational names have whitespace.

Some examples (c&p from docspell webui):
- Versorgungsanstalt des Bundes und der Länder
- Thüringer Landesamt für Bodenmanagement und Geoinformation
- Industrieverband Haus- und Versorgungstechnik Niedersachsen und Bremen e.V.

**Comment by eikek** [comment]
Ah interesting. When i tried with longer names and whitespace it was wrapping on space. But "Versorgungsanstalt" is already quite long :) Now it uses "break-all", it should now break more aggressively.
