### ISSUE TITLE
Bug Report: In some situation content search results will less than page size and "Load more" button won't show up

### ISSUE THREAD

**Issue by ohagene** [eikek/docspell#1363]
Hi, i found out that when using content search if SOLR search results have some items with discriminator = 'item', then the rest-server will ignore them and just return items with discriminator = 'attachment'. So this will lead to a small results than "page size ( default is 60)" in web UI, in these situation, the "Load more" button won't show up, and user have no way to see other search results.

I think we can just set SOLR search param fq with "discriminator:attachment" to fix this bug.

**Comment by eikek** [comment]
Thank you for the report! I'm currently not sure if these results should be really ignored. But I see that there is no load-more button for any fulltext only search.

**Comment by ohagene** [comment]
@eikek Hello again! After I upgraded to 0.34, and changed full text search engine to postgresql. A similar bug occurred again. 

This time, it is because postgresql search result doesn't have distinct item_id (both item itself and it's attachement will in sql search result). So, the web ui will show a smaller results than "page size ( default is 60)", and again the "Load more" button won't show up.
