### ISSUE TITLE
zip files as several documents

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#1366]
Hi,

I have documents bundled in a zip file. I would like to get one document per file in the zip container, but i get one document containing all files of the zip. 

1. Is this possible? 
2. Am i missing a checkbox?
3. Can i split a document with multiple files into multiple documents?

Cheers
eresturo

**Comment by eikek** [comment]
This is not possible yet, but I think a good thing to add! Splitting is also not implemented, only the inverse (merging).
