### ISSUE TITLE
Cannot change tags color

### ISSUE THREAD

**Issue by lucson312** [eikek/docspell#1378]
Not sure if I'm missing something in the docs, but I can't find where to change the tags/tags category color.

![image](https://user-images.githubusercontent.com/1076687/154126207-2a181d41-bcc5-4d1f-86e0-a7247f419c65.png)

**Comment by eikek** [comment]
Look in *User Profile -> User Settings -> Tag Category Colors*. In 0.32.0 you can define them for the whole collective and/or specific to a user.

**Comment by lucson312** [comment]
@eikek  Thank you, really great app btw.
