### ISSUE TITLE
Add other file backends

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#1379]
It should be possible to allow more backends for storing files, i.e. S3 as a popular distributed file storage would be nice to have. Then the filesystem can also be added.

**Comment by andreklug** [comment]
Having set up a backup for my SQL database I see how huge it is - the compressed archive is well over 2.5GB for ~700 documents. As I am going to further import files I see the database growing to 20GB or more, which becomes a pain to handle, puts unnecessary wear on the SSD and so on.
It would be great to have an option to use the filesystem as the PDF storage.

**Comment by eikek** [comment]
Yes, you can do this [now](https://docspell.org/docs/configure/file-backends/) - filesystem or s3. It has been added in the last version.
