### ISSUE TITLE
Reverse Proxy error? No document preview

### ISSUE THREAD

**Issue by andreklug** [eikek/docspell#1381]
Hi @eikek

Today I managed to install docspell without docker in a Linux Debian. I have set up nginx as a reverse proxy. Following your example from the docs I created and adapted the site configuration fopr nginx, I also double checked with the nginx conf you provide in the raspi-scripts:

```
server {
    listen 0.0.0.0:80 ;
    listen [::]:80 ;
    server_name docs.home ;
    location /.well-known/acme-challenge {
        root /var/data/nginx/ACME-PUBLIC;
        auth_basic off;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 0.0.0.0:443 ssl http2 ;
    listen [::]:443 ssl http2 ;
    server_name docs.home ;
    location /.well-known/acme-challenge {
        root /var/data/nginx/ACME-PUBLIC;
        auth_basic off;
    }
    ssl_certificate /etc/nginx/ssl/docs.home.crt;
    ssl_certificate_key /etc/nginx/ssl/docs.home.key;
    ssl_trusted_certificate /etc/nginx/ssl/homelab.local_CA.crt;
    access_log /var/log/nginx/docs.home.access.log;
    error_log /var/log/nginx/docs.home.error.log;
    ssl_protocols TLSv1.2;
    ssl_dhparam /etc/nginx/dhparam.pem;
    ssl_ecdh_curve secp384r1;
    ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
    ssl_session_timeout  10m;
    ssl_session_tickets off;
    #ssl_stapling on;
    #ssl_stapling_verify on;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    resolver 192.168.11.1 valid=300s;
    resolver_timeout 5s;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

 location / {
     proxy_pass http://127.0.0.1:7880;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection $connection_upgrade;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forwarded-Proto $scheme;
     proxy_set_header X-Forwarded-Host $host;
  }
}


```

When I start nginxI am getting the error "nginx: [emerg] unknown "connection_upgrade" variable".
Starting nginx without this line works, but I don't see previews, not sure if this is related. This is how the network tab looks then, I am getting this single HTTP/400 Error:

<img width="1284" alt="grafik" src="https://user-images.githubusercontent.com/13343357/154156720-cfe3f092-01d6-4000-86b7-e1e66cbc8fd6.png">
 

Is this variable needed in a non-docker environment? Am I missing something different?

**Comment by eikek** [comment]
Hi @andreklug 

I think nginx miht not have this variable by default. I have just checked my config and there it is declared like this (in the `http` section):
```
# $connection_upgrade is used for websocket proxying
map $http_upgrade $connection_upgrade {
     default upgrade;
     ''      close;
}
```
Guess we should add this to the docs. It could be that it is sometimes prepared in the default conifg of some distributions. I think I never really added this myself :-). This is used to forward the websocket connection. Docspell currently uses this websocket connection only to notify when a document has been processed. So it should not affect the previews, I would say.

**Comment by andreklug** [comment]
You are right, I didn't check see the top of that file. Thank you!
