### ISSUE TITLE
save imported files outside the docker container?

### ISSUE THREAD

**Issue by marcert** [eikek/docspell#1383]
Hi,
great project- I really like it!
Is it also possible to store files after they have been imported to docspell outside the container? (background: I am running truenas with a VM in which Ubuntu is running with the docker engine and that VM has not so much space therefore I want to have the files outside the container on a NFS folder that it will be stored directly from truenas).
Or is it possible and I was to blind to find it in the documentation?

Many thanks and Kind Regards
Marco

**Comment by eikek** [comment]
Hi @marcert , thank you :)!

It's not possible for now. You can store the data outside the container, by mounting an external directory into the database container. Currently it is not possible to store files separately. I'm currently exploring #1379 - at some point it will be, but currently you would need to put the complete database at some other disk (which I would do anyways).
