### ISSUE TITLE
Question regarding SOLR configuration

### ISSUE THREAD

**Issue by andreklug** [eikek/docspell#1384]
Hi @eikek 

I am trying to set up SOLR on my docker-free install in a Debian VM. 

Apache SOLR 8.11.1 is running and I can access the web interface. However, when trying to create the core I am running into the following error:

`root@docs:/var/solr/data# curl -s "http://localhost:8983/solr/admin/cores?action=STATUS"
{
  "responseHeader":{
    "status":0,
    "QTime":0},
  "initFailures":{"docspell":"org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Could not load conf for core docspell: Error loading solr config from /var/solr/data/docspell/conf/solrconfig.xml"},
  "status":{}}
`

I tried to find the the needed schema.xml and solrconfig.xml in the raspy setup script, but wasn't successful.

Would you please tell me how to set up the docspell core in SOLR properly?

Also. I have written down all my installation steps and would happily contribute a step-by-step howto for everyone who prefers direct installation over Docker (as soon as I have this and the previews working).

Thanks in advance!
KR André

**Comment by andreklug** [comment]
Okay, I solved it while trying to reproduce what I did before:

`su solr -c '/opt/solr-8.11.1/bin/solr delete -c docspell'
su solr -c '/opt/solr-8.11.1/bin/solr create -c docspell'
curl -XPOST -H "Docspell-Admin-Secret: my secret" http://localhost:7880/api/v1/admin/fts/reIndexAll`

Thanks anyway :)

**Comment by eikek** [comment]
Nice!! Yes, I can also remember that it is important to act as the `solr` user to get the permissions right. A step-by-step guide would be very neat! Thank you - you can choose a spot in the documentation, somewhere around "Install" i guess - not easy :-)
