### ISSUE TITLE
Previews not working

### ISSUE THREAD

**Issue by andreklug** [eikek/docspell#1385]
Hi @eikek 

I cannot figure out why I am not seeing any preview in the document window:

<img width="979" alt="grafik" src="https://user-images.githubusercontent.com/13343357/154475522-f1241028-075e-4640-9273-78dbd6862a48.png">

Thumbnails are being generated and visible in the search results. I tried different formats of source files, but anyway they are all being converted to PDF anNginx doesn't log any error. The only thing I see is this in the console, not sure if this is related.

`Feb 17 12:15:19 docs docspell-restserver[1465]: level=INFO  thread=io-compute-121 logger=o.h.s.m.Logger message="HTTP/1.1 GET /app/assets/docspell-webapp/0.32.0/docspell-query-opt.js.map"
Feb 17 12:15:19 docs docspell-restserver[1465]: level=INFO  thread=io-compute-121 logger=o.h.s.m.Logger message="HTTP/1.1 404 Not Found"
Feb 17 12:15:19 docs docspell-restserver[1465]: level=INFO  thread=io-compute-114 logger=o.h.s.m.Logger message="HTTP/1.1 GET /api/v1/sec/folder?q=&sort=name"
Feb 17 12:15:19 docs docspell-restserver[1465]: level=INFO  thread=io-compute-114 logger=o.h.s.m.Logger message="HTTP/1.1 200 OK"

`

Do you have any further hints where to look?

Thanks as always :) 
André

**Comment by eikek** [comment]
Hi @andreklug , 

hm this is strange. Can you open "developer tools" in the browser and look at the "Networking" tab? You should see there which request fail. The logs you showed look good to me. The 404 is about a file that doesn't exist, but browsers try to load them. Sometimes a browser cache is not invalidated, try with a hard reload if not already done so.

**Comment by andreklug** [comment]
And there we go: I didn't see an error in Safari's networking tools, but Firefox was more verbose and told me that loading of the attachment was block by a header set wrong in Nginx. It has to be "add_header X-Frame-Options SAMEORIGIN;" but I set it to "DENY".

Works now. 

Thanks!
