### ISSUE TITLE
[Bug] Filtering items by "Tag Categories" with blank category does not work (empty result)

### ISSUE THREAD

**Issue by arittner** [eikek/docspell#1402]
Hi!

Filtering by "Tag categories" is a nice feature, but it works only, if a category is given. I've some tags without categories (and docspell shows the amount of items with these tags), but if I filter it, no document will be displayed:

![grafik](https://user-images.githubusercontent.com/5605065/154961838-693ef20d-365a-4b3d-9db0-cf4490119d06.png)

Filtered:

![grafik](https://user-images.githubusercontent.com/5605065/154962005-36381114-d151-4071-936e-6cb527119818.png)

This is a little bit unexpected :-D

**Comment by eikek** [comment]
Thanks! I don't use empty categories so I never saw it :-). Searching for "not in a category" is not supported. The entry shouldn't occur actually.

**Comment by arittner** [comment]
> The entry shouldn't occur actually.

Agree. I think this makes sense, if the query is not supported. :)
