### ISSUE TITLE
Processing queue hangs on ocrmypdf step 

### ISSUE THREAD

**Issue by mtonnie** [eikek/docspell#1417]
I have this problem with different files when I have uploaded a few files with web interface processing starts but it hangs randomly on step ocrmypdf. 

![image](https://user-images.githubusercontent.com/7443153/155517997-ff1c158d-0711-4eb3-9f58-001049b8e6cc.png)

I can execute the corresponding ocrmypdf command inside a shell of the docker container an it will finish in a few seconds.
But I can't cancel the current processing step, the only possibility I figured out is, restarting the joex docker container.

After that the same file will be processed like all the other files in a few seconds.

Any idea?

**Comment by eikek** [comment]
Hi @mtonnie - it could be a out of memory error. Is there anything interesting in the logs of joex? What system are you running this on?

**Comment by mtonnie** [comment]
I'm using an rpi4 with 4GB and there are just an two other docker Containers running (portainer and nginx-proxy-manager).
I have installed the headless image on an ssd and setup a swap file with 2GB, the thing which is strange to me is, when it hangs i can attach a shell in the running container and copy & paste the command an it works. And when I restart the container it will work as well.

Any hints concerning log entries, what to look for?

**Comment by eikek** [comment]
Hm, this is strange! If there are errors, you should see them in the logs (from the container). If there is nothing, then I don't really know. Here are some random thoughts: docspell writes many temporary files (ocrmypdf as well), I think it is good to mount an external temp directory on the ssd into the joex container. My first suspicion was that ocrmypdf crashes, but if it is working separately, it doesn't fit…. Maybe still try to disable ocrmypdf in the config to see if this helps or the error occurs somewhere else. Maybe with some luck, the logs show something.

**Comment by mtonnie** [comment]
I tried it again with an extra volume mapping for /tmp but it seems to be the same.
I can't find any problem inside the log it will end with external command ...
![image](https://user-images.githubusercontent.com/7443153/155704580-83f69e93-d995-4374-beb1-552d4cc9a311.png)

Memory is used but it seems to be still free memory to be used...
![image](https://user-images.githubusercontent.com/7443153/155704704-1282021b-7049-4cee-9a35-4dfb1bc9edef.png)

 Probably I'll try to disable with another data volume and put the same files.

**Comment by eikek** [comment]
Hm, is there any ocrmypdf process running? If not, it seems to be crashed, killed or exited normally even - I don't know :-). Are there any directories in `/tmp` that could be related to a killed ocrmypdf process? Really strange that the parent java process is not notified when ocrmypdf was terminated. 

If you disable ocrmypdf in the config - is something like this happening on other commands? It could be an indication whether it is only happening for ocrmypdf or in general when running external programs.

**Comment by mtonnie** [comment]
I had a look to the processes running, there is no ocrmypdf thread running when it "hangs".
When it comes to CPU usage 0% there is no process, for the jobs before the ocrmypdf process is shown in top -H or pstree.

**Comment by mtonnie** [comment]
Is it possible to set something like a timeout for ocrmyodf step?
In case of the timeout is reached the step will fail?

**Comment by eikek** [comment]
That's strange. So the process is gone, but the java parent somehow is confused. Yes good idea playing with the timeout, you found the correct setting! 

Maybe a thread dump (when hanging) can give a hint. When you connect to the docker container, try to run `jstack -le <pid>` - that produces a lot of stuff. Would be great to have this as a text file. The pid must be from the joex java process.

**Comment by mtonnie** [comment]
@eikek I have send you the dump by mail. 
The timeout setting doesn't change anything, I even can't cancel the job manually (button has no effect... )

**Comment by eikek** [comment]
Thank you! I think this one here is the problem:

```
"io-compute-6" #27 daemon prio=5 os_prio=0 cpu=10120.70ms elapsed=4458.77s allocated=342M defined_classes=360 tid=0x0000007f6b7fe000 nid=0x5e runnable  [0x0000007f69ddb000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ProcessImpl.forkAndExec(java.base@11.0.14/Native Method)
	at java.lang.ProcessImpl.<init>(java.base@11.0.14/ProcessImpl.java:340)
	at java.lang.ProcessImpl.start(java.base@11.0.14/ProcessImpl.java:271)
	at java.lang.ProcessBuilder.start(java.base@11.0.14/ProcessBuilder.java:1107)
	at java.lang.ProcessBuilder.start(java.base@11.0.14/ProcessBuilder.java:1071)
	at docspell.common.SystemCommand$.$anonfun$startProcess$4(SystemCommand.scala:106)
	at docspell.common.SystemCommand$$$Lambda$3905/0x0000000100f40040.apply(Unknown Source)
	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:588)
	at scala.concurrent.package$.blocking(package.scala:124)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:951)
	at cats.effect.IOFiber.autoCedeR(IOFiber.scala:1372)
	at cats.effect.IOFiber.run(IOFiber.scala:131)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:520)
```
It looks like the native method never returns, although the process is gone. The cancel button doesn't work, because the thread can't respond to anything.

Hm. I have not really an idea. It might be worth trying a different base image for arm - or in general. I think openjdk11 on alpine is not officially supported by OpenJDK (at least that what the readme says on dockerhub). If you find some time, maybe you can try this? A first try could be with `eclipse-temurin:11-alpine` - so the remaining Dockerfile probably doesn't need much change.

**Comment by eikek** [comment]
Hi! No sadly no idea - forgot to look at the architecture - sorry for giving you a false hint here! We could try with a debian base image. It will be much larger (I think ~400M). But if that is working I would consider to bite this… wdyt? (I once played with debian base images and could share a starting point of docker-files, if you are interested. just let me know).

**Comment by bbieberle** [comment]
Hi! I have the same issue on rpi4/4GB!

**Comment by mtonnie** [comment]
@bbieberle any solutions or workarounds?

I have made a few additional test, one idea was to use the webservice wrapper from ocrmypdf docker image (https://hub.docker.com/r/jbarlow83/ocrmypdf) and call a simple wrapper script that uses curl to call the service.

`
#!/bin/sh

args=$@
infile=$(echo "$args" | sed -n "s/^.*\(S*\/tmp\/docspell-convert.*\/infile\).*$/\1/p")
outfile=$(echo "$args" | sed -n "s/^.*\(S*\/tmp\/docspell-convert.*\/out.pdf\).*$/\1/p")
opts=$(echo "$args" | sed "s# $outfile##" | sed "s# $infile##")
cd ${infile/infile//}
curl -F "params=$opts" -F 'file=@infile;filename=infile.pdf' http://docspell-ocrmypdf:5000/ -o out.pdf
`
But I ended up with the same issue

**Comment by bbieberle** [comment]
Well I am not very familiar with the inner working of docspell yet. My solution is to restart the Joex container periodically. For my it is able to get though 1-5 documents before it gets stuck...
I assigned it 2G of memory and it does not make a difference if you use nlp.mode full or basic. I am using German a the processed language. Maybe this info helps...

**Comment by mtonnie** [comment]
I‘m using german as well, but as far as I understood the nlp step comes after ocrmypdf step. 
I guess it‘s worth to build a image with openjdk java as base image, just to see if we face the same issue. 

Because it‘s definitely related to java or the implementation of this external program call.
As i mentioned before, I have already change tested it with a script to call curl and the webservice from oyrmypdf docker image. 
and it happened again…

**Comment by bbieberle** [comment]
You are probably right. I just tested a docx file and unoconv hangs as well.

` 2022-03-03T22:03:59: Running external command: unoconv -f pdf -o /tmp/docspell-convert/docspell-unoconv10241106252105276449/out.pdf /tmp/docspell-convert/docspell-unoconv10241106252105276449/infile`

**Comment by mtonnie** [comment]
I tried to build a image based on openjdk base images, not jet finshed.
But I had an additional idea, we could probably use the image from amazoncorretto:11-alpine3.15-jdk as an alternative to the alpine image. 

@eikek What do you think about testing amazoncorreto image and do you the change of java version maybe 8 oder 17 could solve the issue?

**Comment by mtonnie** [comment]
I have made a really quick and dirty image which seems to fix it based on openjdk base image, atm not healthy an a really dirty hack. 

Feel free to test ... mtonnie/docspell-restserver:nightly & mtonnie/docspell-joex:nightly

I have feed about 20 documents in a row without a problem, ...

**Comment by eikek** [comment]
Hi! So great - thank you all for looking at this! Good to know that it's not only ocrmypdf but rather something in general with running external commands. I also suspect some jvm weirdness happening here. I'm fine with testing out anything that works. Docspell should run on java 17,

The corretto variant would also work - I'm not sure if they also have arm/v7 base images? Then when using alpine, I think currently only 3.14 works or we have to install wkhtmltopdf manually (or use a replacement, which would require a config change only, but still might be confusing).  I would prefer the openjdk base image if that's possible - they seem to have good suppor for architectures. But also not a strong opinion and they don't have images for arm/v7 it seems… 🤔 

I don't think it is the java version per se that has the issue, but more a variant/build for arm on alpine. Currently I think it doesn't matter which version exactly (as long as >= 11) - more trying out a different distribution.

I tried yesterday with debian:slim and other base images. But I couldn't get python to install on arm (I'm crossbuilding via buildx - might have a broken setup as well…). It was failing for all kind of base images I tried. I'm really happy to seet hat you have something working @mtonnie  - however "hacky" it might be 😄 . Btw which openjdk image did you use?

**Comment by mtonnie** [comment]
feel free to have a [look ](https://github.com/mtonnie/docspell/blob/6717158bffd72b7a66b0ecb6d839b57c57ad9bab/docker/dockerfiles/joex.dockerfile#L1).

BTW, I guess we won't see image for arm64 with corretto ... https://github.com/corretto/corretto-docker/issues/46

**Comment by mtonnie** [comment]
Maybe the simple sollten is, to use openjdk8 for linux/arm64 as well?
What Kind of disadvanteges du you expect with Java8?
Or otherwise we should work on get wkhtmltopdf installed manually

**Comment by eikek** [comment]
Thank you! I tried this file on my setup, but it fails to install (failing to install python-minimal), too. I also had to add some spurious symlinks (for `dpkg-split` and some other tools, that were looked up in the wrong place) in order to get there. That means that something is fishy on my setup here. Really annoying. I will do it via github actions. But I would say if you find the arm image is working - I would go with openjdk base image. Might need to drop arm/v7, though, or keep the old dockerfile for it. But tbh, maintaining this docker stuff is so annoying that I would rather remove it 🤷🏼

**Comment by eikek** [comment]
> Maybe the simple sollten is, to use openjdk8 for linux/arm64 as well? What Kind of disadvanteges du you expect with Java8? Or otherwise we should work on get wkhtmltopdf installed manually

Yes right, this is a very good idea! 

Regarding java 8, two things come to mind: I'm using jdk11 when developing. I'm not using java "the language", so the risk is very low that I use APIs not present in Java8, but it exists. There is a tiny amount of java code that is compiled with java8 as target - a error in the build file could be problematic (and I won't notice this). Then Java8 is just old. I would assume, newer JVMs have better performance in general. The G1GC would be important to have, which was added in java11, but also backported to java8. I would feel more comfortable with java11, but given that this is actually broken for arm, these arguments are rather irrelevant.

Would you mind testing this image on your RPI4 (I don't have one to test with atm). If that is working, I could use it for the next release.

**Comment by mtonnie** [comment]
I have done it with github actions as well.
I guess we could also think about replacing wkhtmltopdf with weasyprint.
Looks like there is an alpine package as well ... https://pkgs.alpinelinux.org/packages?name=weasyprint&branch=v3.15

**Comment by eikek** [comment]
Yes exactly, I just wanted to take a look at it first. I tried only with 2 filesfor now, and the output looks almost identical. So I think this is good to use (but want to try some more files :)). It would be possible to change the command in the reference config and also in the docker-compose file.

**Comment by mtonnie** [comment]
Any hint how to set ARGS as environment variable?

with DOCSPELL_JOEX_CONVERT_WKHTMLPDF_COMMAND_ARGS='["--encoding","{{encoding}}","{{infile}}","{{outfile}}"]' 

I get: Expected type LIST. Found STRING instead.

It doesn't matter if i use single quotes or not ....

**Comment by eikek** [comment]
Oh sorry, arrays are not supported to specify as env vars, I'm afraid. 

I played with weasyprint a bit more. I found it not working so well, tbh. I had some HTML mails where lots if text was not present in the resulting PDF. (Wkhtmltopdf produced 60 pages and weasyprint only 2)

I pushed new nightly images with openjdk8 for arm64.

**Comment by mtonnie** [comment]
@eikek I have tested the nightly build, I have uploaded about 40 documents and all the documents have been processes in a row.

Looks good for me! Thanks!
One remark, guess it's not necessary to replace the java version for restserver image as well but I guess it's ok to do it as well.

**Comment by eikek** [comment]
Oh thank you, really great to hear that! I included the change already in the current release (0.33.0). I thought taht it is probably better anyways, since the openjdk site on docker-hub says that openjdk11 is not supported on alpine. So even better that it seems to fix this issue. I also changed to openjdk8 for the restserver for the same reason: don't want to run into issues there as well. Though you are right that it is not really necessary - but it was easier to do, too :).

**Comment by mtonnie** [comment]
Thanks @eikek I have seen it and upgraded to 0.33.0. 
I have process another batch with about 100 documents without any problem, I'll close this issue

**Comment by gerroon** [comment]
I have the same issue I think. I added around 100 files. All are just waiting, and no real processing is done. I was able to add individual documents one by one.

**Comment by eikek** [comment]
Hi @gerroon are you running on a Raspberry Pi with the arm64 docker images? What version are you running?

**Comment by gerroon** [comment]
> 

I am using it on Debian Testing x64. I restarted the docker compose stack and it worked this time, it remembered the queue and started and finished all one by one.

**Comment by eikek** [comment]
Ok, this issue here is only applicable to the arm64 images. You can open a new issue if you encounter more problems.
