### ISSUE TITLE
Watch read only or remote directory

### ISSUE THREAD

**Issue by stephanvierkant** [eikek/docspell#1457]
I'm using docspell on my Synology using Docker. It works great!

Not sure if this is a feature request or a support question, but I'd like to organise my documents that are already on my Synology. I've put some files in the docs/{collection} directory and they get deleted. What if I want to use a directory in my NAS as the source?

**Comment by eikek** [comment]
I think you can do this, if I understand correctly. You can instruct `dsc` to not delete uploaded files - look into the `docker-compose.yml` there is the container running `dsc` and you'll see the used options. It reacts on changes in the directory but will not upload files that are already in docspell (so you can move things around/rename). If you just want to upload all files in the directory once, you can do this via `dsc upload --traverse …`.
