### ISSUE TITLE
Migrations not executing in order

### ISSUE THREAD

**Issue by JaCoB1123** [eikek/docspell#1465]
Hey eikek,

I just tried migrating from the legacy docker-images to the new ones.
So that means I'm coming from 1.23 straight to 1.34.

When starting I get the following error:
```
SQL State  : 42703                                                                                                                        
Error Code : 0                                                                                                                            
Message    : ERROR: column "file_id" does not exist                                                                                       
  Position: 36                                                                                                                            
Location   : db/fixups/postgresql/V1.33.0__fix_reorganize_files.sql (/opt/file:/opt/docspell-joex-0.34.0/lib/com.github.eikek.docspell-sto
b/fixups/postgresql/V1.33.0__fix_reorganize_files.sql)                                                                                    
Line       : 37                                                                                                                           
Statement  : with                                                                                                                         
  missing_ids as (                                                                                                                        
    select file_id from filemeta                                                                                                          
    except                                                                                                                                
    select file_id as file_id from valid_file_ids)                                                                                        
insert into obsolete_files (file_id)                                                                                                      
  select file_id from filemeta                                                                                                            
  where file_id in (select file_id from missing_ids)                                                                                      
```

The latest entry in `flyway_schema_history` is this though:
| installed_rank | version | description | type | script | checksum | installed_by | installed_on | execution_time | success |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| 41 | 1.23.0 | clientsettings | SQL | V1.23.0__clientsettings.sql | 1152128793 | dbuser | 2021-05-30 02:03:55.677365 | 196 | 1 |

I tried manually renaming the id column to file_id, but then I get an error when the 1.26-migration is applied.

**Comment by eikek** [comment]
Ouch! I knew I missed something when adding this fixup migration 🤯  

I think the easiest way is to first upgrade to 0.33.0 and start docspell, then stop it and update to 0.34.0 and start it again. I will add a check for the fixups to only start when the current db version is >1.33

**Comment by JaCoB1123** [comment]
I had to go back all the way to 1.29.0 because of a non-existant column "name" in "notification_channel_mail". I tried adding it, but got an error because of a non existent entry in useremail. I got it to work again now, so it's not an issue for me anymore.

Anyways, I've really been missing out by not updating my docker-compose file. Really loving the new features, keep up the work!
