### ISSUE TITLE
Search for "name or notes" only works with lower-case entries

### ISSUE THREAD

**Issue by Skyr** [eikek/docspell#147]
While experimenting, I discovered that the moment I enter a capital letter in the "name or notes" field, my search result is empty. With the corresponding lowercase letter, everything works as expected.

**Comment by Skyr** [comment]
Just realized that you continued to work on the code since my efforts to understand what was happening here... and you already fixed it :blush:

**Comment by eikek** [comment]
Oh, I'm sorry! Yes, I just realized it yesterday while I was working on improving the search feature.

**Comment by Skyr** [comment]
Nothing to be sorry about - I never mentioned I had a look at that issue :wink: Though I have a bit of Scala experience, it's my first contact with "real" functional Scala (and Cats), so I had no idea if I would get anywhere :wink:
Thanks again for your work!
