### ISSUE TITLE
Consumedir not.wirking with multi-page documents

### ISSUE THREAD

**Issue by dominformant** [eikek/docspell#1473]
Since the last update, multi-page documents uploaded Form Scanner via DSC watch are not uploaded correctly and only show "preview not available" in Docspell. I think ist related to the Scanner saving the Individualität pages, however it used to work until I updated docspell. I already tried to downgrade to DSC v0.7.0 without success.

**Comment by eikek** [comment]
Hi @dominformant ,

I'm not sure what you mean with "multi-page documents". Did you upgrade docspell server or dsc - it's not very clear from your statement. It could be that documents are send too early you could try to increase `--delay` a bit. Can you post logs from joex maybe it helps to see what's happening.

**Comment by dominformant** [comment]
Thank you so much for your quick response and sorry for the unprecise explanation. First, increasing the `--delay` for `dsc watch` solved the problem, so you were right, that the document is sent too early.

To answer your other questions, even if the problem is solved ore at least worked around, I updated both dsc and docspell server and since than, scanning documents with more than one page to a SMB share, that is watched by dsc stopped working. You find the joex log below.

As the problem seemed to result from the delay of dsc, did the default value change with the update?

However, thank you very much for your response and the provided solution.

```
Sa.. 26. März 2022, 12:32: Starting text extraction for 1 files
Sa.. 26. März 2022, 12:32: Extracting text for attachment scan.pdf
Sa.. 26. März 2022, 12:32: Trying to strip text from pdf using pdfbox.
Sa.. 26. März 2022, 12:32: Stripping text from PDF resulted in an error: Missing root object specification in trailer.. Trying with OCR.
Sa.. 26. März 2022, 12:32: Running external command: gs -dLastPage=10 -dNOPAUSE -dBATCH -dSAFER -sDEVICE=tiffscaled8 -sOutputFile=%d.tif -
Sa.. 26. März 2022, 12:32: Command `gs -dLastPage=10 -dNOPAUSE -dBATCH -dSAFER -sDEVICE=tiffscaled8 -sOutputFile=%d.tif -` finished: 0
Sa.. 26. März 2022, 12:32: Closing process: `gs -dLastPage=10 -dNOPAUSE -dBATCH -dSAFER -sDEVICE=tiffscaled8 -sOutputFile=%d.tif -`
Sa.. 26. März 2022, 12:32: Cannot extract text: null. Try with converted file
Sa.. 26. März 2022, 12:32: Cannot extract text
Sa.. 26. März 2022, 12:32: Extracting text for attachment scan.pdf finished in 346 ms
Sa.. 26. März 2022, 12:32: Storing extracted texts …
Sa.. 26. März 2022, 12:32: Extracted text stored.
Sa.. 26. März 2022, 12:32: Updating SOLR index
Sa.. 26. März 2022, 12:32: Text extraction finished in 423 ms.
Sa.. 26. März 2022, 12:32: Creating preview images for 1 files…
Sa.. 26. März 2022, 12:32: Creating preview images failed, continuing without it.: Missing root object specification in trailer.
Sa.. 26. März 2022, 12:32: Retrieving page count for 1 files…
Sa.. 26. März 2022, 12:32: Error obtaining pages count: Missing root object specification in trailer.
Sa.. 26. März 2022, 12:32: Starting text analysis
Sa.. 26. März 2022, 12:32: Storing tags: List(RAttachmentMeta(Ident(7bQ7TmnNujk-BkJm9VHFjAv-fk6T5okxV2S-o1QwWLYTJk7),None,List(),MetaProposalList(List()),None,Some(German)))
Sa.. 26. März 2022, 12:32: Guessing tags for 6 categories
Sa.. 26. März 2022, 12:32: Guessing label for tagcategory-Ausgabentyp …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Guessing label for tagcategory-Dokumententyp …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Guessing label for tagcategory-Einnahmetyp …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Guessing label for tagcategory-Konto …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Guessing label for tagcategory-Steuerjahr …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Guessing label for tagcategory-Versicherungen …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Guessing label for correspondentorg …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Guessing label for correspondentperson …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Guessing label for concernedperson …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Guessing label for concernedequip …
Sa.. 26. März 2022, 12:32: Guessed: <none>
Sa.. 26. März 2022, 12:32: Text-Analysis finished in 336 ms
Sa.. 26. März 2022, 12:32: Starting find-proposal
Sa.. 26. März 2022, 12:32: Looking up classifier results: List()
Sa.. 26. März 2022, 12:32: Storing proposals
Sa.. 26. März 2022, 12:32: Storing attachment proposals: MetaProposalList(List())
Sa.. 26. März 2022, 12:32: Starting linking proposals
Sa.. 26. März 2022, 12:32: No value for CorrOrg
Sa.. 26. März 2022, 12:32: No value for CorrPerson
Sa.. 26. März 2022, 12:32: No value for ConcPerson
Sa.. 26. März 2022, 12:32: No value for ConcEquip
Sa.. 26. März 2022, 12:32: No value for DocDate
Sa.. 26. März 2022, 12:32: No value for DueDate
Sa.. 26. März 2022, 12:32: Starting setting given data
Sa.. 26. März 2022, 12:32: Set item folder: 'None'
Sa.. 26. März 2022, 12:32: Set tags from given data: List()
Sa.. 26. März 2022, 12:32: Job execution successful
```

**Comment by eikek** [comment]
Hi, thanks for all the info! The logs support that the file is not fully written at the time of uploading.  I have no idea why this changed for you with the update. I also scan multiple pages and didn't see this here (I'm using the default for `--delay`) 🤔  There was no changes related to this, as far as I can see. The default value for the `--delay` did not change either. For dsc, the libraries where updated, this could be a cause, since I'm using a library that provides the filesystem events. But I don't find it very likely, tbh.  I would suspect that this is not related to the docspell server, it should be somewhere in dsc - but you already tried an older version… so unfortunately I have no idea 🤷🏼

**Comment by dominformant** [comment]
Sorry for the late reply, if nothing changed with docspell, the problem most probably comes from my network or setup, even if I don't know what changed. However, using the larger delay, it works again, so thank you very much for your support and in general for your work at docspell.

**Comment by eikek** [comment]
You're welcome! Should you run into problems again, just open another issue.
