### ISSUE TITLE
How long does Auto-Tagging take - unable to stop it

### ISSUE THREAD

**Issue by andreklug** [eikek/docspell#1484]
Hi @eikek,

I started autotagging for currently > 600 documents that are in my library, set the max amount to 0 for this. Running 0.34.0

It's taking ages, and the job log is a loop of the following, roughly every 2 minutes:

```
Mi.. 30. März 2022, 20:15: Learn classifier for tag category: Finanzen
Mi.. 30. März 2022, 20:15: Learning from 500 items.
Mi.. 30. März 2022, 20:15: Splitting raw data into test/train data. Testing with 0 entries
Mi.. 30. März 2022, 20:15: Training classifier from HashMap(maxNGramLeng -> 4, useSplitPrefixSuffixNGrams -> true, splitWordsTokenizerRegexp -> [\p{L}][\p{L}0-9]*|(?:\$ ?)?[0-9]+(?:\.[0-9]{2})?%?|\s+|., splitWordsIgnoreRegexp -> \s+, intern -> true, splitWordShape -> chris4, minNGramLeng -> 1, useSplitWords -> true)
Mi.. 30. März 2022, 20:15: Trained with result TrainResult(NaN,ClassifierModel(/tmp/docspell-analysis/trainclassifier17784009375347712895/model.ser.gz))
Mi.. 30. März 2022, 20:15: Storing new trained model for: tagcategory-Finanzen
Mi.. 30. März 2022, 20:15: New model stored at file Ident(FKTs2iy9YrMX31gykyEtS11M6q7C9qucDqjnNQfotTh)
Mi.. 30. März 2022, 20:15: Deleting old model file Ident(GJZMcDrAYc12YWAt1auU4YaYGm26iYuDx1CiMEhD9yEp)
Mi.. 30. März 2022, 20:15: Found 0 obsolete model files that are deleted now.
Mi.. 30. März 2022, 20:15: Deleted 0 model files.
Mi.. 30. März 2022, 20:15: Learn classifier correspondentorg
Mi.. 30. März 2022, 20:15: Learning from 612 items.
Mi.. 30. März 2022, 20:15: Splitting raw data into test/train data. Testing with 0 entries
Mi.. 30. März 2022, 20:15: Training classifier from HashMap(maxNGramLeng -> 4, useSplitPrefixSuffixNGrams -> true, splitWordsTokenizerRegexp -> [\p{L}][\p{L}0-9]*|(?:\$ ?)?[0-9]+(?:\.[0-9]{2})?%?|\s+|., splitWordsIgnoreRegexp -> \s+, intern -> true, splitWordShape -> chris4, minNGramLeng -> 1, useSplitWords -> true)
```

Maybe I am not patient enough, after some time I tried to stop that job without success. Even rebooting the machine doesn't kill it, the learning process just started again, always with "tag category: Finanzen."

Any ideas?

EDIT: looking at these lines: 

Mi.. 30. März 2022, 20:17: New model stored at file Ident(5HJGY5eQeQhwoF6mnZE28Ztexjuramvancn9cXyFcQhz)
Mi.. 30. März 2022, 20:17: Deleting old model file Ident(8x8uBFrg67fekGU8an1AAj7Bo31Y1szBUGuM4XnWPZwc)
...
Mi.. 30. März 2022, 20:18: New model stored at file Ident(5MpopLXNKJq8njfTsFuKsL86ys51g8h1xrxA1F7Bti3X)
Mi.. 30. März 2022, 20:18: Deleting old model file Ident(5HJGY5eQeQhwoF6mnZE28Ztexjuramvancn9cXyFcQhz)
...
Mi.. 30. März 2022, 20:20: New model stored at file Ident(5K7nMCeQ2qAAux6UCSWHLHpp4oQ3RX2WHcsWUwthVYje)
Mi.. 30. März 2022, 20:20: Deleting old model file Ident(5MpopLXNKJq8njfTsFuKsL86ys51g8h1xrxA1F7Bti3X)

the new model gets deleted in the next run.

Also it seems like the process is running twice, after I stopped it the first time, set the file limit from 0 to 500 an started it again? Maybe the two interrupt each other again and again?

**Comment by eikek** [comment]
Hi! This learning can take a while, but not "ages" of course…. I would say it could easily take some minutes on some machines. So I'm not sure - the logs look okish to me. If you restart joex, it will pick up the last job it was working on. However, there shouldn't be two same jobs running at the same time. If a job can't be stopped it could mean that the whole process is not responding (maybe it's an out of memory error), or the current step doesn't allow to be interrupted. 

One way to remove the job "forcefully": stop joex, run `delete from joblog; delete from job;` sql against the db and then start joex. Now there is no job to run.

What hardware are you running on - a rather beefy machine? To rule out memory problems, I would try to set the limits very low, for example set `classification.item-count = 10` and `text-analysis.max-length = 100` just to see if that terminates like expected. If this still seems to hang, I think I need a stack trace of the jvm.

**Comment by andreklug** [comment]
thank you as always for your helpful reply. 
The VM has 4 cores, 6GB RAM assigned. It ran for a few minutes, then started again, deleted the previous results and repeated the whole thing. For hours, blocking other tasks like email import.

I am wondering if there is a way to figure out what's causing this, are there any logs I can have a look at or share with you except the task info?

Good to learn how to remove the job. This allows me to try again and then kill if it needed. 

Could there be any limitations to the tags, maybe German umlauts? Also I have a lot of tags that aren't in any category. What I saw in the activity that it was trying to process the category "Finanzen" and also was working on the correspondents. The latter just let's me think if they might have some constraints, like empty fields or bad characters?

Have a great weekend!

**Comment by eikek** [comment]
Hi! you're welcome! I'm not aware that special characters would influence running time so much. From your logs above, it seems to hang on learning the classifier for the correspondent-org. Additional to the logs from the task, you can look at the logs of the joex process, they should contain more information.

If it hangs "forever" I suspect an out-of-memory error, this could crash the jvm. If you are using the docker-compose setup or the debian packages, it could be that the process is being restarted after it died and then it repeats :/ 

If you can forcefully clear the job queue and then restart with very low classification settings, it would be interesting if it works then.

Wish you a nice weekend, too!
