### ISSUE TITLE
Support migrating from H2 to Postgres

### ISSUE THREAD

**Issue by vs49688** [eikek/docspell#1519]
When evaluating Docspell, I first used a H2 database. Now, I would like to migrate to Postgres (for many reasons - performance, file locking, etc.), however I can't seem to find any resources or documentation on how to do this?

Is this unsupported (i.e. I'll have to recreate everything), or am I blind?

**Comment by eikek** [comment]
Hi, I don't think there is a straightforward way to do this. You could try to search for migrating between h2 and postgres, it's not special to Docspell. TBH if you don't have a lot of data, I would start fresh. But I guess it is somehow possible.

One way could be creating a dump using H2's `Script` tool. You need to download the correct version (should be [this](https://h2database.com/h2-2019-10-14.zip)) and then run this command:
```
java -cp h2/bin/h2-1.4.200.jar org.h2.tools.Script -url "jdbc:h2:///path/to/a/file.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE" -user "user" -password "pass"
```

This creates a `backup.sql` file in the current directory. Now this contains schema and data, and I don't think the schema creation works in postgres. So you could try to use `sed` or other tools to filter them out. Then start docspell on an empty database in postgres. This will create the schema. Then you could try to import the tweaked backup.sql into postgres via
```
psql -h localhost -U user dbname < backup.sql
```

If that is too difficult, maybe H2 can dump the data as CSV, postgres can also import CSV files… Sorry don't have more than that.

**Comment by vs49688** [comment]
No worries. I've just spent a few hours exporting and patching the SQL, but it's too finicky. I'm just going to start from scratch and re-import everything.

Thanks for the help!
