### ISSUE TITLE
Postgres path

### ISSUE THREAD

**Issue by poltrian** [eikek/docspell#1525]
I installed Docspell without docker. If I accept the configuration as it is delivered, everything works. If I enter url = "jdbc:postgresql://localhost:5432/docspelldb" in the two config files, I can no longer upload any documents. What am I doing wrong there? Postgred database, user and password are correct

**Comment by eikek** [comment]
I don't see anything wrong looking at the uri. Are there any error messages? I think the logs from the restserver could help, can you post them here? 

Is only uploading a file failing? Can you reach the web ui and login and do other stuff?

**Comment by poltrian** [comment]
There is no logfile. I can not also update files. I guess my postgres setup is worng i followed the Debian manual

**Comment by eikek** [comment]
On a Debian system, you should see logs via `journalctl -efu docspell-restserver` - does this work? Can you login in the webapp?

**Comment by poltrian** [comment]
Got it. I had a special character in the postgres password. Without it works. so i guess special characters should be ulen

**Comment by poltrian** [comment]
Thamks for the greate pice of software!
