### ISSUE TITLE
Nextcloud & Docspell

### ISSUE THREAD

**Issue by poltrian** [eikek/docspell#1527]
Is there a possibility to connect wiith Nextcloud Folders?

**Comment by eikek** [comment]
I never used Nextcloud, so no idea what a "Nextcloud Folder" is :/. I guess it's not possible. If you can expose files via cifs or other ways, it could work.

**Comment by TheFehr** [comment]
I have used webdav mounts for other projects. Nextcloud does not like files being moved that way though from my experience. And afaik docspell **needs** to copy a document to use it. So you'd be duplicating your files.

**Comment by TheFehr** [comment]
@poltrian what is your goal by using a nextcloud folder? Easier upload? Access to the pdfs through nextcloud?

**Comment by poltrian** [comment]
Access to pdf on Nextcloud and easier upload. And all documents in one folder. So I have my documents on Nextcloud.

**Comment by eikek** [comment]
Yes, docspell always copies documents into its own storage. There is no builtin way to access files via webdav. If you want all documents in one folder on your nas, I think the best way currently is to somehow watch this folder - best is directly on the machine where the files are physically localted. The dsc tool can be started on the machine running nextcloud, for example, I assume that nextcloud creates its folders soemwhere in the filesystem. And … live with the duplicated data.

**Comment by TheFehr** [comment]
One option might be to use a mounted webdav folder as the directory where docspell puts the files.

But then any changes from nextcloud would be a terrible idea.

But that would solve the duplication error.
And upload would need to be a seperate folder watched either by the nextcloud server or via another synced directory. This would be a lot slower though than just opening docspell and drop it in there I'd say.

**Comment by TheFehr** [comment]
The easiest solution. Though not a direct connection is to use the external sites app. With that you can add a custom navigation item to nextcloud aka your docspell

**Comment by TheFehr** [comment]
#1649 could be what is needed to make the connection to Nextcloud easier / viable

**Comment by eikek** [comment]
But wouldn't it be essentially the same thing as running the export right now? The files are still duplicated in that they exist in docspells internal sotrage and also on the filesystem. I'm not sure that #1649 would make really a difference to using dsc and periodically run the `export` command 🤔 ?

**Comment by TheFehr** [comment]
Very true, I mean I don't fully understand the use case for the link to Nextcloud myself either.
I am happy with it being it's separate app/tab. It just thought that #1649 would make the use case as I understand it easier.
