### ISSUE TITLE
Not clear how to stop signup on docker

### ISSUE THREAD

**Issue by PietroMB** [eikek/docspell#1530]
Hello everyone, is not clear to me how to block new user registration on default docker installation, someone can write me where I must put the "config file"?

Thx

**Comment by eikek** [comment]
You can use an env var for this. The setting is called "signup mode". Add this to the compose file:

```
- DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=closed
```

Other possible values are `invite` and `open` (the default). All available env vars are listed [here](https://docspell.org/docs/configure/main/#environment-variables). I think we can add this one to the docker-compose file - it is something that should be changed probably
