### ISSUE TITLE
[UI] italic Dashboard-Card-Header

### ISSUE THREAD

**Issue by monnypython** [eikek/docspell#1531]
Hi!
No big deal though: is it necessary that the header is in italics?
I also like emojis here and they look a bit strange.
Perhaps the text could be displayed in bold instead of in italics?

![image](https://user-images.githubusercontent.com/42573701/165719501-784727d3-7a4c-42c0-baf5-9da6c2f17f0e.png)

**Comment by eikek** [comment]
I have no strong opinion - can certainly make it bold instead of italic :-) 

What do you mean with the icon?

**Comment by eikek** [comment]
Ah, but how did you get an icon in there???

**Comment by monnypython** [comment]
I put it from clipboard or in Windows from emoji-picker (Windows + .). Nothing special. I think the emojis looks pretty cool in dashboard.
