### ISSUE TITLE
Adding Lithuanian language to document processing 

### ISSUE THREAD

**Issue by PovilasID** [eikek/docspell#1540]
Could Lithuanian language be added? tesseract ocr shot code is lit

These would be the month names:

English - Lithuanian short (with the dot at the end)

January - sausis - saus.
February - vasaris - vas.
March - kovas - kov.
April - balandis - bal.
May - gegužis - geg.
June - birželis - birž.
July - liepa - liep.
August - rugpjūtis - rugp.
September - rugsėjis - rugs.
October - spalis - spal.
November - lapkritis - lapkr.
December - gruodis - gruod.

In Lithuanian language nouns have forms that change the end of the word so 'sausis' == 'sausio' == 'sausį' == 'sausyje' each word transforms differently.  The two most common ways to list month names is in form I named in the way they are listed in https://www.localeplanet.com/icu/lt-LT/index.html 
Regarding the date format, the most widely used short date format would be y-MM-dd and long format y 'm'. MMMM d 'd'.  ('m' is short for 'metai' 'year'  and 'd.' is short for 'diena' 'day'
Lithuania also uses 'military time' 18:00

**Comment by eikek** [comment]
Thank you for the details!
