### ISSUE TITLE
Recovery quite old instance

### ISSUE THREAD

**Issue by TheAnachronism** [eikek/docspell#1553]
I've recently found a backup of an installation that is a few months old (version 30.0 or something) and I'd like to recover the data from it. The problem is, that I can't remember what the password of the only account on it is. I know the collective, as I can just query the database directly.

Is there some process for this?
My end goal is just to get the .pdf files out of it again not the rest of the data.

**Comment by eikek** [comment]
Yes, you could use the `dsc admin reset-password` command to reset the password of the account. Then a `dsc export …` can export all the files to some directory. HTH!

**Comment by TheAnachronism** [comment]
Yeah, but how do I get the admin secret?

**Comment by eikek** [comment]
This is in the config file ("admin" meaning the person that installs it and has access to the machine :)). See [here](https://docspell.org/docs/configure/admin-endpoint/). You need to start the rest-server (joex is not needed).

**Comment by eikek** [comment]
Another note: there is a [script](https://github.com/eikek/docspell/tree/master/tools/start-local) that might help to start up some version locally. (you might need to edit it to include your db credentials)

**Comment by TheAnachronism** [comment]
OK, I finally got it.
Got the files back I wanted.
Thank you very much and awesome tool^^
