### ISSUE TITLE
Scan Mailbox with shared Office365 mailboxes

### ISSUE THREAD

**Issue by derrey** [eikek/docspell#1555]
I am able to connect with Microsoft Office365 main mailbox via IMAP but when I try to connect to a shared mailbox the system provides a failed authentication error. I have tested all credentials and confirmed via the MS testing tool: https://testconnectivity.microsoft.com/tests/O365Imap/input

Using "Basic authentication" (Non-OAuth Method)

They use the name of the shared folder after the user name.
e.g. IMAP user id: user@maindomain.com\shared-mailbox 
and the password of the main account.
______

Exchange Configuration Info from MS Forum:

  USER EMAIL: user@maindomain.com
  PASSWORD: password

  SHARED MAILBOX: shared@anotherdomain.com      (could also be @domain.com, of course)
  SHARED MAILBOX ALIAS: shared-mailbox

Note: Please make sure to create the UNIQUE alias always with the mailbox, because it creates the user [alias]@maindomain.com. In this case shared-mailbox@maindomain.com

Settings for IMAP Configuration:
  EMAIL ADDRESS: shared@anotherdomain.com (shared mailbox)
  IMAP SERVER: outlook.office365.com
  SMTP SERVER: smtp.office365.com
  USERNAME: user@maindomain.com\shared-mailbox  (user\shared mailbox alias)
  PASSWORD: password (user's password)`

**Comment by eikek** [comment]
Hi @derrey - I'm afraid I can't help you here, I have no experience with MS Office/Exchange at all. But perhaps someone chimes in with some tips. What you could try is enabling "mail debugging" - it is a setting in joex config file `mail-debug = true` - but be aware that this will generate lots of logs :) maybe it helps to identify the problem.

**Comment by derrey** [comment]
> Hi @eikek, Sorry, but I am a newb on this new system. Just installed using docker and am not sure where the joex config file is. I did try searching... but after a bit of google and searching... I thought I would finally ask :)

**Comment by eikek** [comment]
No worries, if you are using the provided docker-compose file, it can be configured using env variables (described [here](https://docspell.org/docs/configure/defaults/#environment-variables). Try setting this:

restserver:
```
DOCSPELL_SERVER_BACKEND_MAIL__DEBUG=true
```

joex:
```
DOCSPELL_JOEX_MAIL__DEBUG=true
```

Since you are probably only interested in the IMAP functionality, setting joex should be enough.
