### ISSUE TITLE
Duplicates not ignored

### ISSUE THREAD

**Issue by mirisbowring** [eikek/docspell#1575]
Hi,

i accidently uploaded a file from Smartphone twice and it got imported twice.
There is no sign that marks the document a duplicate or something like this (with an identical hash, a Document should also be skipped right?)

Regards :)

**Comment by eikek** [comment]
Hi - oh that is not intended of course! Does it happen only from the phone or also when you upload the file twice via web?

**Comment by eikek** [comment]
Ah never mind. I see the issue. The android client is not sending any metadata with the upload and the default behavior is `skipDuplicates = false`. This is probably to stay backwards compatible when it was added 😄.

I think a saner default is to skip duplicates by default. However, there are cases where it may be surprising. For example, when you upload a zip file it  then skip all entries that already exist and you may then see not all the files as attachments. I would like to have the possibility for the android client to specify metadata anyways (in the future). I think it's good to add a default set of metadata and say explicitly to skip duplicates.

**Comment by mirisbowring** [comment]
What metadata should be specified by the app? Shouldn't the metadata be read by the server? Or are you talking about the docspell metadata? :)

In which case would you like to keep a duplicate (e.g. uploading a zip). Even then i would expect to skip the file.
Or if you need to add additional tags, a behaviour could be to mark the file as non approved again and then it will popup in dashboard again.

**Comment by eikek** [comment]
> What metadata should be specified by the app? Shouldn't the metadata be read by the server? Or are you talking about the docspell metadata? :)

You can send metadata with the request. https://docspell.org/docs/api/upload/#metadata



> In which case would you like to keep a duplicate (e.g. uploading a zip). Even then i would expect to skip the file.

It could be that the duplicate is based on a file added longer time ago and then you might wonder why it was removed . It happened to me :). But it can be easily specified by clients, dsc for example has this as default (to skip duplicates). 



> Or if you need to add additional tags, a behaviour could be to mark the file as non approved again and then it will popup in dashboard again.

I don't think I understand what you mean with that?

**Comment by eikek** [comment]
Changed it quickly in the android app, and released it.

**Comment by mirisbowring** [comment]
Thank you for the quick fix!

> I don't think I understand what you mean with that?
I meant the case you've specified above (added document long time ago, added it twice and it didn't appear).
Since the second upload of the document could have another context, therefore additional tags would be neccessary, my proposal would be to keep the file unique, but docspell could take the old (alread, approved) file and mark it as non approved or as "updated" or something like this.

In the Dashboard you could see the new old document and modify the metadata.

**Comment by mirisbowring** [comment]
Are you releasing the 0.9 on f-droid too? :)

**Comment by eikek** [comment]
> I meant the case you've specified above (added document long time ago, added it twice and it didn't appear). Since the second upload of the document could have another context, therefore additional tags would be neccessary, my proposal would be to keep the file unique, but docspell could take the old (alread, approved) file and mark it as non approved or as "updated" or something like this.
> 
> In the Dashboard you could see the new old document and modify the metadata.

That's a nice idea! I think I would just keep both files and somehow mark them as duplicates. The user can then change metadata and/or delete one of them. It is a little more complicated due to that an item can have multiple attachments and so multiple different duplicates may occur. I know that "handling duplicates" is a topic in a dms, but I didn't think about this yet for docspell, tbh.


> Are you releasing the 0.9 on f-droid too? :)

Sure. This is done automatically by f-droid from each `v*` tag. It may take 2 days or two weeks sometimes until it appears.
