### ISSUE TITLE
mail sending failed: invalid adresses

### ISSUE THREAD

**Issue by swoop124** [eikek/docspell#1578]
Hello,

i just installed docspell in a docker conatiner.
it works just fine, but when i want to send a document as email with an address like "name.name@doamin.tld" then i get "mail sending failed: invalid adresses" but when i send it to "name@domain.tld" then it is working just fine.

regards

**Comment by swoop124** [comment]
hey guys,

it seems the problem was related to https://github.com/eikek/docspell/issues/1460 
After i encountered this E-Mail-Problem i stumbled over the problem with search.
So i did the sugested in the thread and waited overnight.
Now it is working, at least docspell says "E-Mail was sent."

**Comment by eikek** [comment]
Hi @swoop124 glad that the problem is resolved. I first thought it could be related to #1565 ? I looked at #1460 I can't see anything related to e-mail sending at - only regarding search problems.

**Comment by swoop124** [comment]
Hi @eikek,

thank you for your answer. I discovered when i send mails to my domain, they are working well.
I tested also my other domains and e-mailadresses on hotmail, but not all are working. 
I don't know why but all domains not on my DNS are getting this errormessage from post1.

I found this messages in restserver conatinerlog:
```
2022.06.04 11:37:55:0000 [io-comp...] [WARN ] jakarta.mail.Session.loadResource - expected resource not found: {0}
2022.06.04 11:37:54:0002 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 POST /api/v1/sec/email/send/domain.tld/CcbHxt2NDGG-sQBDG5KM3sA-6GZoU5J1jHi-hTyK6vNEKmj
2022.06.04 11:40:09:0000 [io-comp...] [WARN ] jakarta.mail.Session.loadResource - expected resource not found: {0}
2022.06.04 11:40:09:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 POST /api/v1/sec/email/send/domain.tld/CcbHxt2NDGG-sQBDG5KM3sA-6GZoU5J1jHi-hTyK6vNEKmj
```
All ohter Dockerlogs have nothing unexpected.

What could be the problem?
Where do i get more Logs so i can investigate further?

**Comment by swoop124** [comment]
Is there in the Config something related to only sent to??

**Comment by swoop124** [comment]
Maybe i found the Problem, it may be relaytet do the sending Mailserver.

**Comment by swoop124** [comment]
yes, the problem was with the sending Mailserver, this time.
After i checked the logs there, i found out that these domains got a relay access denied.
So i had to configure it there.
thanx for your help ;-)

**Comment by eikek** [comment]
Great that you found it! Just for your info: Check the [default config](https://docspell.org/docs/configure/defaults/) and search for `MAIL__DEBUG` (if you use env variables, like with docker-compose) or `mail-debug` (when you use a config ifle). Setting this to true results in very verbose logs regarding mail sending/receiving.
