### ISSUE TITLE
Unable to process/store PDF due to incorrect datetime value for suggested due date

### ISSUE THREAD

**Issue by justsomebody42** [eikek/docspell#158]
I have uploaded a PDF file that is since stuck in the processing queue.

Error message:
2020-06-25T9:06:37: Job 8RYNuoXTR.../.../process-item/High execution failed. Retrying later.: (conn=6796) Incorrect datetime value: '2090-12-03 00:00:00' for column `docspell`.`item`.`duedate` at row 1

I wonder, where the due date comes from and how I could get the document into the system without it.

**Comment by eikek** [comment]
Oh, no that's weird! It might be that the date is too far in the future – some dbms have very specific rules when it comes to timestamps and I might have used the wrong data type here. The logs should show more details. The due date comes from guessing it using the extracted text (which sometimes is just wrong). I guess it would be sensible to apply some limit here, mabe a few years only …. What database are you using?

Docspell does some retries and when it finally fails, the document will be created nevertheless, just without any help from the processing. So the document should show up in the list with empty proposals and you can manually attach metadata.

The number of retries and time in between can be configured, so the time can be reduced for these cases, too.

**Comment by justsomebody42** [comment]
I use MariaDB.
And of course I aborted it after 3 retries, thinking it would never succeed with the exception in the logs..
Would the stacktrace help?
I didn't see any thing useful in it besides the error message itself...
I'll upload again and wait for it to be created after all retries.

Thanks a lot for your fast response!!

**Comment by eikek** [comment]
Ah, yes aborting the processing is also something to improve. It currently aborts the whole job - this includes creating the item itself. While it does create the item if it finally fails…. This is not intuitive and I'll change this for the next release. And you're right, retrying doesn't make sense in this case and the error message already is quite clear, so the stacktrace is not necessary. I'll first try to reproduce it and I already have some suspicion.

You could set `docspell.joex.scheduler.retries = 1` to workaround long wait times for now.

Thank you for reporting this!

**Comment by justsomebody42** [comment]
Wow, that was fast!
Thanks a lot!

**Comment by eikek** [comment]
You're welcome!
