### ISSUE TITLE
Various Timeout formats wrong documented (for docker)

### ISSUE THREAD

**Issue by Snify89** [eikek/docspell#1612]
If you use docker-compose, you should NOT quote environment variables.

In the documentation it says e.g. 
DOCSPELL_JOEX_EXTRACTION_OCR_UNPAPER_COMMAND_TIMEOUT="5 minutes"

However it is expected:
DOCSPELL_JOEX_EXTRACTION_OCR_UNPAPER_COMMAND_TIMEOUT=5 minutes

Logs from JOEX
2022.06.28 13:12:23:500 io-compute-1 INFO docspell.config.ConfigFactory.default:44
    Using config from environment variables!
pureconfig.error.ConfigReaderException: Cannot convert configuration to a docspell.joex.Config. Failures are:
  at 'docspell.joex.convert.ocrmypdf.command.timeout':
    - (properties) Cannot convert '"30 minutes"' to Duration: format error "30 minutes". (try a number followed by any of ns, us, ms, s, m, h, d).
  at 'docspell.joex.convert.tesseract.command.timeout':
    - (properties) Cannot convert '"30 minutes"' to Duration: format error "30 minutes". (try a number followed by any of ns, us, ms, s, m, h, d).
  at 'docspell.joex.convert.unoconv.command.timeout':
    - (properties) Cannot convert '"30 minutes' to Duration: For input string: ""30". (try a number followed by any of ns, us, ms, s, m, h, d).
  at 'docspell.joex.convert.wkhtmlpdf.command.timeout':
    - (properties) Cannot convert '"30 minutes"' to Duration: format error "30 minutes". (try a number followed by any of ns, us, ms, s, m, h, d).
  at 'docspell.joex.extraction.ocr.ghostscript.command.timeout':
    - (properties) Cannot convert '"30 minutes"' to Duration: format error "30 minutes". (try a number followed by any of ns, us, ms, s, m, h, d).
  at 'docspell.joex.extraction.ocr.tesseract.command.timeout':
    - (properties) Cannot convert '"30 minutes"' to Duration: format error "30 minutes". (try a number followed by any of ns, us, ms, s, m, h, d).
  at 'docspell.joex.extraction.ocr.unpaper.command.timeout':
    - (properties) Cannot convert '"30 minutes"' to Duration: format error "30 minutes". (try a number followed by any of ns, us, ms, s, m, h, d).
  at 'docspell.joex.house-keeping.cleanup-downloads.older-than':
    - (properties) Cannot convert '"7 days"' to Duration: format error "7 days". (try a number followed by any of ns, us, ms, s, m, h, d).

**Comment by eikek** [comment]
Oh right, thank you!

**Comment by eikek** [comment]
I just had a look again and I think it's correctly written 😄 

The env variables are listed in the configuration page and do not relate to docker or whatever tool being used. The transition from the config section to the tool of choice must still be, of course. I guess in case of docker-compos it is more a yaml based issue/reason why you need to omit quotes. Maybe we could add a note to the docker compose section of the manual… but usually people know their tools and things like this could become outdated. 🤔
