### ISSUE TITLE
Partial word or Fuzzy search

### ISSUE THREAD

**Issue by JPVenson** [eikek/docspell#1636]
Testing docspell for my giant paper mountain, I found a very annoying bug/missing feature.

When searching though my invoices I sometimes only have parts of text I am looking for, like a invoice number. For example I a looking for an invoice `#20220705_1755`. When I am searching for only `20220705` or `1755` the document does not show up, but only when typing in the whole word.

Otherwise looks the software very promising.

**Comment by eikek** [comment]
I think you should be able to use the `*` wildcard, like `20220705*` in your search?
