### ISSUE TITLE
Bulk Remove Tag

### ISSUE THREAD

**Issue by JPVenson** [eikek/docspell#1641]
It would be very nice to Bulk remove tags from selected documents the same way you can add them via selection and Multi-Edit.

**Comment by eikek** [comment]
I think this is possible, when in multi-edit mode you can click on the tiny icon on the right, above the input field and cycle through modes add -> remove -> replace.

**Comment by JPVenson** [comment]
Ahh yes then please change the description or at least the icon, it is very misleading.

**Comment by eikek** [comment]
what change do you propose? There is a description about it here: https://docspell.org/docs/webapp/multiedit/#tags

**Comment by JPVenson** [comment]
In the easiest way, just display all 3 icons for all 3 mods and highlight the one that is active.
