### ISSUE TITLE
Estonian language for OCR

### ISSUE THREAD

**Issue by lesu1** [eikek/docspell#1646]
Hi, is there any way you to add the Estonian language for OCR, please?
Thanks in advance!

**Comment by eikek** [comment]
Sure. Could you please provide necessary information, similar to #1540 ?

**Comment by lesu1** [comment]
Yes, sure

Monts we have:

English - Estonian short  (March, Mai, June and July used as is in long form)

January - jaanuar - jaan.
February - veebruar - veebr.
March - märts - märts
April - aprill - apr.
May - mai - mai
June - juuni - juuni
July - juuli - juuli
August - august - aug.
September - september - sept.
October - oktoober - okt.
November - november - nov.
December - detsember - dets.

Timezone: GMT+2

Date formats:
Example: 10. juuli 2022
Pattern: d. MMMM y

or

Example: 10.07.22
Pattern: dd.MM.yy
Local Pattern: dd.MM.yy

Let me know if anything else is needed and I would be happy to help.
Thanks,
lesu1
