### ISSUE TITLE
Base-URL not used for scheduled mails

### ISSUE THREAD

**Issue by JaCoB1123** [eikek/docspell#1739]
Hi eikek,

I've had wrong Links my notification mails for a while. Docspell keeps using "main.example.local:7880" as the hostname in mails instead of the configured "docs.example.com". Interestingly I get correct mails when I invoke the send manually, but when it's sent from the planned "Due Items Query", it's wrong.

Do you have any idea, what I might have configured wrong? 

I'm on docspell 0.38 running via docker. My config starts with the following, which should be the only relevant option according to the docs.

```
docspell.server {
  base-url = "https://docs.example.com"
  internal-url = "http://restserver:7880"
}
```

Thanks 👍

**Comment by eikek** [comment]
Hi @JaCoB1123 - this could be an outdated job data in the database. When a background job is sending mails, it gets the url from its arguments that are saved each time you save the task. Maybe try to edit the task and save it again - or create the task anew. It should then get the same base-url stored in the db that is used when you trigger it manually.

**Comment by JaCoB1123** [comment]
Yes, that did it. Thanks a lot 😃
