### ISSUE TITLE
How can i add a collective

### ISSUE THREAD

**Issue by Nollknolle** [eikek/docspell#1748]
Hey,
i registered my user.
How can I add collectives and add them to the user

**Comment by eikek** [comment]
Currently it is the other way around: you can add users to a collective. The collective represents a group of users with equal access rights to the data. So you can register more collectives if you want separate data. You can add more users to a collective to allow access to more people.

**Comment by Nollknolle** [comment]
Thanks for that quick answer.

But how can I add more Collectives? Only via API?

**Comment by eikek** [comment]
Not sure if I understand - you could just signup a new account, like on `/app/register` page, no? How did you register your first account?

**Comment by Nollknolle** [comment]
Ah ok so if I closed signups then I cannot add a new collective without API

**Comment by Nollknolle** [comment]
Thanks 🙏

**Comment by eikek** [comment]
If signup is closed in the config file, it should not work at all - not via api and not via the page 😕

**Comment by Nollknolle** [comment]
ok thank you very much 👍

**Comment by eikek** [comment]
you're welcome!
