### ISSUE TITLE
Cannot extract text from file mail.converted: unsupported format text/html; charset="UTF-8". Try with converted file.

### ISSUE THREAD

**Issue by Nollknolle** [eikek/docspell#1749]
Hey,
i get this error/warning on my mail import.

`Di.. 20. September 2022, 19:59: Cannot extract text from file mail.converted: unsupported format text/html; charset="UTF-8". Try with converted file.`

![grafik](https://user-images.githubusercontent.com/62543404/191353117-d1168fb7-ff55-4371-ba71-25f2f6f1d0a2.png)

**Comment by eikek** [comment]
Ah this is not an error, but more a "fat info" :) Text extraction from html is not done, because for a good result, one needs to interpret the html (and possibly css) - and so the text extraction is done from the converted pdf file instead. Errors are printed in red (this is some yellow-orange…).

**Comment by Nollknolle** [comment]
So there is nothing wrong with it?
then I am reassured

**Comment by eikek** [comment]
Correct, it is expected for html files (which often times applies to a mail body)
