### ISSUE TITLE
Import metadata from PDFs (especially keywords)

### ISSUE THREAD

**Issue by Skyr** [eikek/docspell#175]
I'm thinking about a workflow for getting rid of paper at home; it will most likely involve some smartphone scanning app. Most of these apps allow adding some tags which end up as keywords in the PDF metadata. It would be great to have these imported and - if the strings match - automatically assigned as tags to the imported item.

**Comment by eikek** [comment]
Ah yes, nice idea! I was playing around with "OpenNoteScanner" the other day that seems to do this as well (not really tried with keywords but found some settings and was wondering what this is for…). It would also be great to have a little android app that does post requests to the docspell server and that hooks into the "share with" menu. I think this would be great for getting receipts quickly into docspell.

To your proposal: you mean to get all keywords from the pdf metadata and all that match existing tag names in the database are then associated?

**Comment by Skyr** [comment]
Yes, matching given keywords against the database were my first (and main :wink: ) idea.

I know too little about the information gathering heuristics of DocSpell, but perhaps the rest of the PDF's metadata (unmatched keywords, other entries) can be useful for that, too. That's why I chose a more generic title when creating this issue :-)

**Comment by eikek** [comment]
Yes, this data is definitely useful. Maybe it could also be added to the extracted text, so it would be searchable. Matching keywords with tags shouldn't be too hard to add and it would be really useful. I would consider this for the 0.10.0 release which is (right now in my head :-)) concerned with the topic "custom processing", so it fits in there anyways. Thank you a lot for your input!

**Comment by eikek** [comment]
This is now in master and will be available in the upcoming 0.9.0 release (it wasn't so much work). Keywords from PDF metadata will be matched against tags in the database. And some other metadata (title, author, etc) is appended to the extracted text so that it is indexed and also can be a candidate in matching correspondents.
