### ISSUE TITLE
Mails got imported multiple times

### ISSUE THREAD

**Issue by Nollknolle** [eikek/docspell#1755]
Hey,
my mails got imported multipley times?
How can that happen?

![grafik](https://user-images.githubusercontent.com/62543404/191823030-866e51e6-ff1c-42dc-af75-b732ffab6c41.png)

**Comment by eikek** [comment]
I'm not sure. How did they get into docspell - are they imported by scanning a mailbox periodically? If so, at what schedule do you let this happen and are there multiple joex workers? The check if a document already exists only works for processed files, not for those that are still being processed. So it could happen if two joex workers would pickup the same file. This can happen if you leave the mails in the mailbox for example and they are read in on the next scan-mailbox-job while the first is still processing stuff. But all guesses :) Need more info on your setup.

**Comment by Nollknolle** [comment]
I have one importer that only start at the first of the month. 
He should import all mails.

**Comment by eikek** [comment]
It is likely this bug #1397  - as a workaround you need to move/delete mails out of the way.

**Comment by Nollknolle** [comment]
When I move it then it works

**Comment by emhl** [comment]
I have a similar, or the same issue. I added a second joex and now every email get's imported twice. if I disable the second joex everything works fine

**Comment by eikek** [comment]
@emhl do you move the imported mails out of the way? And do you see two running jobs for the same mailbox at the same time although you only have one job configured?

**Comment by eikek** [comment]
> When I move it then it works

Then this is most likely a duplicate to #1397
