### ISSUE TITLE
Search with numeric custom field says "No number given"

### ISSUE THREAD

**Issue by Fredo70** [eikek/docspell#1756]
I have a numeric custom field to indicate the tax year. When I want to search for documents and select this field, enter the year, the message "No number given" remains and it does not filter by year.
Is this a bug or have I not understood the idea of the numeric custom field correctly?

**Comment by eikek** [comment]
Hi @Fredo70 this sounds like a bug, but I cannot reproduce it. Did you press ENTER to initiate the search and it still says "No number given"? I suppose you are using the left search menu right?

**Comment by Fredo70** [comment]
I am ashamed. Press Enter to initiate the search. Why didn't I think of that myself? Sorry for wasting your time. I close this issue.

**Comment by eikek** [comment]
No worries 😄 those things happen to me, too! Also when updating fields, you don't need to press ENTER, this could be the cause of confusion. But for searching I chose an explicit initiation, it otherwise fires too many (more expensive) requests

**Comment by Fredo70** [comment]
Maybe a small error anyway. On my mobile phone (android) I don't get an enter key. The enter key is change to "next" ("weiter" in german). Then the number is not taken over. But the cursor leaves the field. No chance to "enter". I use the Microsoft SwiftKey keyboard.

**Comment by eikek** [comment]
Ah, interesting! It works on my android phone. But you're right, there is no mobile equivalent to initiate the search.
