### ISSUE TITLE
Deb file links are broken on docs page

### ISSUE THREAD

**Issue by dontlaugh** [eikek/docspell#1770]
Here is the page in question: https://docspell.org/docs/install/download-run/

The releases page .deb file download links work :)

**Comment by eikek** [comment]
Thank you for reporting this!

**Comment by dontlaugh** [comment]
Of course. Docspell is really impressive stuff. Well architected and nice docs. docker-compose whet my appetite right away, but if I'm going to run something for real, I like to deploy constituent compoenents individually, without docker.

**Comment by eikek** [comment]
@dacog I don't know either … this is sometimes a bit confusing. I remember trying to fix this in the past (first it was a markdown list item). I think safest thing is to put the whole list into a shortcode template, maybe one for the deb files and one for the zip files.

**Comment by dacog** [comment]
@eikek ok. I'll spend a bit more time trying to fix this and if I can't I'll try what you are suggesting. Either solution is ok for you?

**Comment by dacog** [comment]
@eikek all good! I'm happy this is already fixed 😃 

I managed to research a bit but it was not a waste of time.  Do not worry.  

When I get some time I'll check if there are other issues where I can help ;)
