### ISSUE TITLE
FR: Correct OCRed extracted content

### ISSUE THREAD

**Issue by knobunc** [eikek/docspell#1775]
I scanned some hand-written notes and the OCRed extracted content is gibberish.

I would love to either be able to blank it all out.  Or ideally, I would like to be able to type it in manually.

There are other times when the OCR is close, but there are small errors I would like to correct.

Obviously, updating the text layer in the PDF is not likely to be possible... but at least allowing the user to manually correct the extracted content and then re-indexing it would be awesome.

**Comment by eikek** [comment]
Yes that is something I wanted to add anyways. 👍🏼
