### ISSUE TITLE
OIDC authentik login fails

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#1781]
Original issue was raised in this comment: https://github.com/eikek/docspell/issues/1545#issuecomment-1268116223

When using authentik and logging in with a collective that is different than the username, a failure occurs where the collective and user is tried to insert again into the db.

**Comment by mirisbowring** [comment]
DId you had already time to investigate further? Do you need additional feedback? :)

**Comment by mirisbowring** [comment]
Take your time, thanks for the support!

**Comment by eikek** [comment]
Hey @mirisbowring , so I finally got around to give this a try. I use my local dev setup of docspell and authentik via docker compose. My oidc for docspell looks like this:
```
{ enabled = true,
       display = "Authentik"
       provider = {
          provider-id = "authentik",
          client-id = "566bc60b04d4ac2cda0c4a877cbb68b13600f33f",
          client-secret = "901348d8288e…2",
          scope = "profile openid email",
          authorize-url = "http://localhost:9000/application/o/authorize/",
          token-url = "http://localhost:9000/application/o/token/",
          #User URL is not used when signature key is set.
          user-url = "http://localhost:9000/application/o/userinfo/",
          sign-key = ""
          sig-algo = "RS256"
        },
        collective-key = "fixed:demo",
        # The username to use for the docspell account
        user-key = "preferred_username"
      }
```

I'm using a fixed collective and logging in with `akadmin`. Unfortunately, I cannot reproduce the problem this way. Do you have anything else in your setup that might be related?

**Comment by mirisbowring** [comment]
Hi @eikek thanks for the support. A fixed collective is working too. But i want to lookup the collective that relates to a user.

e.g. Person A & B are using Collective#1 and Person C & D are using Collective#2, etc.

In this scenario, a fixed collective is not feasable. The users are grouped in authentik (collective#1,collective#2,etc.) I even tried setting the collective_key on a user basis in authentik :)

**Comment by eikek** [comment]
I see, now that is really strange! Can you share your authentik config or guide me on how to configure authentik in order to reproduce it? (i have no experience with authentik, I just copied some rather large docker compose file).

**Comment by mirisbowring** [comment]
If the fixed and user part was working for you, it should be already in a good state.

The "easy" case
Under Admin > Directory > Users I select the user, and add the collection details:
```yaml

preferred_username: my-username-in-collective
docspell_collective: my-collective
```
Know we need to create the scope:
Under Admin > Customisation > Property mappings
1. Create a new `Scope Mapping`
2. Fill the details:

| Property | Detail |
| :--- | :--- |
| Name | Docspell Collective |
| Scope name | docspell_collective |
| description | anything |
| Expression | `return { "docspell_collective":request.user.attributes.get("docspell_collective", request.user.username),}` |

3. Admin > Applications > Providers
4.  Edit Docspell OIDC Provider
5. Under `Advanced protocol settings` Also select the "Docspell Collective" Property to be part of the selected mappings

My Docspell Config looks like this:
```
openid = [ 
		{ 
			enabled = true,
        		display = "Primboard Auth"
        		provider = {
          			provider-id = "authentik",
          			client-id = "f12799acf6a048b8d9d68cb240e9212a1f496e5b",
          			client-secret = "00f0342f3825110533532640be322a2491f28d3eb0f848926b35aa7c0c58299d3abef8669ec2b3cc0b6a1a0d2cd99b6bdfe8ecf2d10480a5ac0058f0ff297641",
          			scope = "docspell_collective profile openid email",
          			authorize-url = "https://auth.primboard.de/application/o/authorize/",
          			token-url = "https://auth.primboard.de/application/o/token/",
				user-url = "https://auth.primboard.de/application/o/userinfo/",
				sign-key = "",
				sig-algo = "RS256"
        		},
        		collective-key = "lookup:docspell_collective",
        		user-key = "preferred_username"
      		}
	]
```

Know you can test it with e.g. postman:

1. Create a new Get Request to `https://auth.primboard.de/application/o/userinfo/`
2. Goto Tab `Authorization` (directly below the url) 
3. Select type `OAuth 2.0` and "add authorization data to" to `Request URL`
4. Configure a new Token on the right side
    4.1. Token Name `Authentik`
    4.2. Grant Type `Authorization Code`
    4.3. Callback URL should be grayed out
    4.4. activate the checkbox `Authorize using Browser`
    4.5. Auth URL `use the one from docspell config`
    4.6. Access Token URL `use the one from docspell config`
    4.7. ClientID `use the one from docspell config`
    4.8. ClientSecret `use the one from docspell config`
    4.9. Scope and State should be grayed out
    4.10. Client Authentication `send as basic auth header`
5. Now you can press the `Get New Access Token` which will redirect you to the browser where you have to log in to the authentik and are beeing redirected to postman (enable popups if asking).
6. Scroll up in Postman and select the Token to be used  during authentication `Access Token` and Header Prefix `Bearer`
7. Now the Request should work and Postman is imitating the docspell application.
8. When hitting the Send Button on the top right to `https://auth.primboard.de/application/o/userinfo/` you will get the response in the body below:
```json

{
    "docspell_collective": "my-collective",
    "email": "<email>",
    "email_verified": true,
    "name": "<Real Name>",
    "given_name": "<Real Name>",
    "family_name": "",
    "preferred_username": "my-username-in-collective",
    "nickname": "<loginname in authentik - could also be used as preferred username>",
    "groups": [
        ...
        ...
    ],
    "sub": "sefhwuw784378fg368gf76234gf287gf928hf982hf894fhg9237g4f937gf"
}
```

**Comment by eikek** [comment]
Thank you very much for the excellent guide (only needed the first part)!! Unfortunately… it works here 😱 I added the scope as you described. I even dropped my db, started everything from scratch and tried multiple logins with the same user. I also added a second user under the same and a different collective. Hm, currently I'm out of ideas. Are you using the newest version of docspell?

**Comment by mirisbowring** [comment]
Strange! Somehow my Instance is messed up...

I stopped the instance with docker compose, copied the exact same docker-compose.yml and docspell.conf to a new folder and started the instance again. Now i am able to log in with oidc...

Any Idea on how to tidy up the original instance? I have multiple collectives with around 10k documents in the database - i don't want the users to manual migrate those documents. :)

**Comment by mirisbowring** [comment]
Ha! I got it working!

You'll see this problem if the user has been created und used before the OIDC connection only!
Most Users did already exist within docspell before i connected it to authentik.
In the User Table, the is the source column which was set to local!

I assume that docspell tried to select the userid from user_ where source = "openid". But there have been no user for openid since they are all mapped to local. Now docspell wanted to create those users (not existing) but the constraint of collective and login name created the duplicate error!

Conclusion: Existing Users must be manually updated in the db in order to switch from local to oidc. This does also mean (i tested it right now), that "local" Login is not possible anymore.

I am not sure if this is the best behavior regarding user experience but we should document it :)
I think, the coeistance between local and openid / any other of the same user should be there, probably the source column could be migrated to an array which contains the possibilities?

**Comment by eikek** [comment]
Oh wow, amazing! Yes indeed, I totally forgot this one! Obviously this is a horrible user experience 😆 At least it should give a meaningful error message so one can act on it somehow, even if it is running some SQL commands. But this case was not considered really. I think automatically converting between local and remote user sources can also lead to confusion and might be a security concern. So I think I would try to improve the error message and certainly update the docs for this case, I'd assume it is still a rather rare case after all. Sorry it took so long to resolve!

**Comment by mirisbowring** [comment]
No Problem! and thank you for your patience! 😄 

I don't think that the local login is a security concern. Within our company we have some applications with same approach. Generally we are logging in via SSO (which does the hardware security key verification) and a "backup local login". Imagine, the SSO Provider is down for some reasons. As soon as you have multiple users, they still need to be able to log in.
Indeed, this would be different credentials and would only work if they've set local credentials after signing up with the SSO Provider.

**Comment by eikek** [comment]
Yeah kind of agree that automatically converting between local and remote could be fine. The user installing docspell just needs to be aware of how it works (maybe configurable), so it wouldn't accidentally mix up accounts. I think for now I will add a "account already exists" error to be resolved manually, due to lack of time, but we can have this in the backlog for later maybe.

**Comment by eikek** [comment]
@mirisbowring if you agree, I'd close this issue and track the cause of the problem here #1827

**Comment by mirisbowring** [comment]
We fixed / discovered the issue and mentioned the current workaround - we can close this here and track it in your new issue :)
