### ISSUE TITLE
S3 Compatible File Storage, Broken Previews, OCR Only

### ISSUE THREAD

**Issue by tankerkiller125** [eikek/docspell#1797]
When using an S3 compatible file storage system (in this case Backblaze) I get the following two errors:

Conversion/OCR Issue:
```
Sun, October 23rd, 2022, 2:52: Converting file Some(CIS_Controls_Community_Defense_Model_2.0___Online_2022_0307.pdf) (application/pdf) into a PDF
Sun, October 23rd, 2022, 2:52: Storing input to file /tmp/docspell-convert/docspell-ocrmypdf2209036863655243553/infile for running ocrmypdf
Sun, October 23rd, 2022, 2:52: Trying to read the PDF using 0 passwords
Sun, October 23rd, 2022, 2:52: PDF conversion failed: Error: Header doesn't contain versioninfo. Go without PDF file
Sun, October 23rd, 2022, 2:52: Starting text extraction for 1 files
Sun, October 23rd, 2022, 2:52: Extracting text for attachment CIS_Controls_Community_Defense_Model_2.0___Online_2022_0307
Sun, October 23rd, 2022, 2:52: Trying to strip text from pdf using pdfbox.
Sun, October 23rd, 2022, 2:52: Stripping text from PDF resulted in an error: Error: Header doesn't contain versioninfo. Trying with OCR.
```

Preview Issues:
```
Sun, October 23rd, 2022, 2:57: Creating preview images for 1 files…
Sun, October 23rd, 2022, 2:57: Creating preview images failed, continuing without it.: Error: Header doesn't contain versioninfo
Sun, October 23rd, 2022, 2:57: Retrieving page count for 1 files…
Sun, October 23rd, 2022, 2:57: Error obtaining pages count: Error: Header doesn't contain versioninfo
```

Preview Issue Docker Log:
```
docspell-joex | 2022.10.22 22:57:09:0000 [io-comp...] [ERROR] docspell.scheduler.impl.LogSink.logInternal:49 - >>> 2022-10-23T02:57:09.289690Z Error 23PBb7ekS.../matthew/process-item/High: Creating preview images failed, continuing without it.java.io.IOException: Error: Header doesn't contain versioninfo
docspell-joex |         at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:221)
docspell-joex |         at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1311)
docspell-joex |         at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1288)
docspell-joex |         at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1269)
docspell-joex |         at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1252)
docspell-joex |         at docspell.extract.pdfbox.PdfLoader$.$anonfun$readBytes1$1(PdfLoader.scala:18)
docspell-joex |         at delay @ docspell.extract.pdfbox.PdfLoader$.readBytes1(PdfLoader.scala:18)
docspell-joex |         at use @ docspell.joex.Main$.$anonfun$run$8(Main.scala:44)
docspell-joex |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex |         at modify @ fs2.internal.Scope.close(Scope.scala:262)
docspell-joex |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex |         at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
docspell-joex |         at as @ docspell.joex.Main$.$anonfun$run$10(Main.scala:49)
docspell-joex |         at get @ fs2.internal.Scope.openScope(Scope.scala:281)
docspell-joex |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
```

Any help/assistance would be awesome, so far, I haven't been able to pin down the exact reason this is happening. And I haven't yet found any way to debug the actual S3 layer to see the headers, API request, etc. to see if maybe it's the way Backblaze is responding.

**Comment by eikek** [comment]
The s3 code in docspell uses the [minio](https://min.io/docs/minio/linux/developers/java/minio-java.html) library. Maybe you can try to turn logging on for `io.minio` package (to debug or even trace) in the config file to get better insights. Are you sure the file is ok? It's just that I got this error for corrupted pdf files - then pdfbox (java library for pdf) would error but some other tools could deal with it to some extent.

**Comment by tankerkiller125** [comment]
So I ended up resolving this issue by mounting the b2 storage with the docker rclone plugin. I'm still not sure why exactly Backblaze S3 was causing these issues. My best guess after a while of debugging is that Backblaze is providing the file in a different way than Minio would send it.

**Comment by timawesomeness** [comment]
I'm experiencing the same issue, except I am using an instance of Minio I'm hosting as my s3 provider. I get the same `Header doesn't contain versioninfo` errors on every file I upload, whether it's a PDF or a docx or odt file that Docspell converts to PDF. I can download and open the converted PDF file just fine from Docspell (or from minio directly), so it's not like the resulting PDF is corrupt, it's just an issue during processing.

**Comment by eikek** [comment]
Update: I could finally find the cause I think, it was a bug affecting loading from minio in some cases. An update of the related library (binny) should fix this.

**Comment by tankerkiller125** [comment]
@eikek Is there an easy way to update the binny library on the docker container to test this? If there is I'd be happy to try that out.

**Comment by eikek** [comment]
@tankerkiller125 yes, the library has been updated automatically this morning and the current snapshot version contains it. You could test with the docker nightly images for example, or the snapshot release (zip files).
