### ISSUE TITLE
FR: Simplify login?

### ISSUE THREAD

**Issue by knobunc** [eikek/docspell#1800]
Right now I need to specify a collective/user when logging in... but I set both to the same.  If that is a fairly common pattern, perhaps if a / were not specified it would assume they are the same name.  e.g. if my username and collective were both foo, and I entered foo, the system would treat it as if I typed foo/foo.

But I have no idea how common it is for the two to be the same.

**Comment by TheFehr** [comment]
If your collection and user name are the same.
As they are for the first user you can just use the username for the login.

**Comment by eikek** [comment]
Exacty. This is already the case. You can type just `foo` meaning `foo/foo`. It's mentioned here: https://docspell.org/docs/#collective
