### ISSUE TITLE
Error on Compiling css stylesheets

### ISSUE THREAD

**Issue by Pressyd** [eikek/docspell#1805]
Can you please help on the following issue?

[info] Compiling css stylesheets…
[info] Running npx postcss /root/docspell/modules/webapp/src/main/styles/index.css -o /root/docspell/modules/webapp/target/scala-2.13/resource_managed/main/META-INF/resources/webjars/docspell-webapp/0.39.0-SNAPSHOT/css/styles.css --env production
[error] Unexpected identifier
[error] java.lang.RuntimeException: Unsuccessful return: 1
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at docspell.build.Cmd$Result.throwIfNot(Cmd.scala:13)
[error]         at docspell.build.Cmd$.run(Cmd.scala:22)
[error]         at docspell.build.StylesPlugin$.postCss(StylesPlugin.scala:106)
[error]         at docspell.build.StylesPlugin$.$anonfun$stylesSettings$6(StylesPlugin.scala:55)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (webapp / stylesBuild) Unsuccessful return: 1

**Comment by eikek** [comment]
I couldn't reproduce it here on my machine 🤔  What os do you use and which npm version?

**Comment by Pressyd** [comment]
npm: '6.14.4'
Ubuntu 20.04.5 LTS

**Comment by eikek** [comment]
I'm using npm 8.11.0 - maybe it requires a newer version, not sure.

**Comment by Pressyd** [comment]
Thank you i will try

**Comment by Pressyd** [comment]
Yes, the npm version was a problem, at npm: '8.19.2', building gone smoothly.
Thank you for your fast reply.
