### ISSUE TITLE
Merging selected items leaves the deleted items still selected

### ISSUE THREAD

**Issue by coderbot16** [eikek/docspell#1809]
This is a bit unexpected - my expectation would be that once I've merged two selected items into one, the selection would only contain that single item, rather than containing the single merged item as well as a "phantom" deleted item.

**Comment by eikek** [comment]
This is really not nice atm. I was thinking to clear the selection althogether after merging items? (That would be my expectation :)). I think I'll see in how much work it is.

**Comment by coderbot16** [comment]
Clearing could also work, but I feel like that would be inconsistent with the other operations on selections (linking, etc) that leave the selection intact. Your call though!
