### ISSUE TITLE
Docker image for joex 0.39.0 contains a broken ocrmypdf

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#1850]
The docker image of version 0.39.0 unfortunately contains a broken ocrmypdf. Docspell worksi without it, but some PDFs may miss a text layer now.

**Comment by taenzerme** [comment]
Is this the reason ocr processing / batch processing is so slow with 0.39.0?

Btw, migrating from Mayan to Docspell right now (10.000+ existing documents ready to be migrated). Love your work!

**Comment by eikek** [comment]
Actually, I would assume the opposite in some cases 😅  ocrmypdf runs tesseract which can take quite long. But in case it fails, docspell might run tesseract itself then. So it depends on the file format mostly. But do you see any specific performance decline compared to the 0.38.0 version? (this is only relevant to the docker images - just for clarification :)).

**Comment by eikek** [comment]
I fixed the image and re-published both images under the same tag (latest). So you need to remove your local images and pull them again.
