### ISSUE TITLE
wkhtmltopdf depends on insecure version of qtwebkit

### ISSUE THREAD

**Issue by antifuchs** [eikek/docspell#1873]
I recently tried updating my nixpkgs to the 22.11 release, and that has failed to build with a pretty scary-sounding security warning: 
> Known issues:
>   - QtWebkit upstream is unmaintained and receives no security updates, see https://blogs.gnome.org/mcatanzaro/2022/[11](https://github.com/antifuchs/home/actions/runs/3625647463/jobs/6113911308#step:4:12)/04/stop-using-qtwebkit/

Looks like joex uses wkhtmltopdf, which in turn depends on qtwebkit from qt5, and that hasn't been updated in several years. It also seems that wkhtmltopdf isn't maintained either: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/5160.

Overall, this is a pretty unfortunate situation, especially because I know of no good alternative tool off-hand.

**Comment by eikek** [comment]
Yes that's right. It has been unmaintained for quite a while now. As of the latest version of docspell, you can use `weasyprint` instead, but the results are way poorer than wkhtmltopdf. The docker compose files use weasyprint as default now.

For now I _personally_ don't care that much about the security concerns in wkhtmltopdf wrt how I use it on joex, so I will keep using it for now. FWIW docspell strips the input html a bit using [this jsoup based whitelist](https://github.com/eikek/docspell/blob/master/modules/joex/src/main/scala/docspell/joex/extract/JsoupSanitizer.scala). But of course, if there is a good alternative, I'd like to switch as well.

**Comment by antifuchs** [comment]
Ah, that makes sense - as docspell/joex is currently not installable on 22.11 due to this, would it make sense to adjust the module to use `weasyprint` instead, despite the lower quality?

**Comment by antifuchs** [comment]
(Oops, you can already customize what thing to use instead of wkhtmltopdf, with the [`joex.convert.wkhtmltopdf` module](https://github.com/eikek/docspell/blob/master/nix/modules/joex.nix#L1208-L1240). Oops.

**Comment by eikek** [comment]
Ah right, you can configure it currently by overwriting the settings for the wkhtmltopdf. But… it seems I forgot to add new settings regarding weasyprint 😅  

Also thanks for the link using chromium. It looks interesting but can also be quite heavy maybe

**Comment by VTimofeenko** [comment]
@antifuchs do you happen to have a config with weasyprint instead of wkhtmltopdf?

The warning can be suppressed by adding `qtwebengine` as in the Docspell nix flake check [here](https://github.com/eikek/docspell/blob/master/nix/checks/solr.nix#L10).

**Comment by antifuchs** [comment]
Thanks for the link, allowlisting the package does seem to work - but I would much rather just disable HTML conversion entirely (all my documents go into docspell as PDFs). I haven't been able to do so yet - it seems that whenever I override any attribute in the wkhtmltopdf attribute set, it invalidates all other attributes around it, for example:

``` console
error: attribute 'orcmypdf' missing

       at /nix/store/d4xhri3h3jbnm9ym3yn7jvdwgs2p0vgv-source/nix/modules/joex.nix:1370:25:

         1369|               });
         1370|               default = defaults.convert.orcmypdf;
             |                         ^
         1371|               description = ''
       Did you mean ocrmypdf?
```

**Comment by eikek** [comment]
@antifuchs I think you should be able to set `wkhtmlpdf.command.program` to something non-existing and this would cause html->pdf conversion to fail.

**Comment by VTimofeenko** [comment]
> error: attribute 'orcmypdf' missing

Oh, this is a typo in the module. I created a PR to fix it.

**Comment by eikek** [comment]
> > error: attribute 'orcmypdf' missing
> 
> Oh, this is a typo in the module. I created a PR to fix it.

Thank you!
