### ISSUE TITLE
Is it safe to remove attachment source files?

### ISSUE THREAD

**Issue by dbobak** [eikek/docspell#1893]
I'm using Docspell to quickly fuzzy search in quite huge collection of pdf files (~8000 files, ~50GB on disc). I'm using filesystem backend to store the files. Is it safe to remove the file located in the ./attachmentsource directory? As I understand, that is the place where Docspell stores original version of files. And, in fact, I don't need them, they're just waste of disc space. So I would be happy to delete them.

**Comment by eikek** [comment]
Docspell is not prepared for these files to be missing. But I think if you can live with a few things not working correctly, you can delete them. For example, you will get an error when downloading the original file and reprocessing will probably also fail. This directory contains the original uploaded file, but the webui by default shows the converted pdf file. Not sure if/what other things are affected - you need to try it out maybe. In general I would assume that most things will still work.

**Comment by dbobak** [comment]
Thank you! I will experiment.
