### ISSUE TITLE
pls. update docker images on docker hub

### ISSUE THREAD

**Issue by papaloewe** [eikek/docspell#1901]
I wanted to update my docpsell instance and realized that the images on docker hub are already 2 years old.
Sure, you can build them yourself, but it's easier for me to use the ones from docker hub.
Please push your current images once up.

Thank you....

**Comment by eikek** [comment]
I'm not sure if I understand, the docker images from the latest release were created and pushed a month ago and are pretty recent in my eyes.

**Comment by papaloewe** [comment]
sorry, my fault. I was still on the old repository.

**Comment by eikek** [comment]
Ah right, no worries! You can switch to the new repo and still stay on the old docspell version; v0.23.0 is on both repos.
