### ISSUE TITLE
Rendering problem with some PDFs

### ISSUE THREAD

**Issue by crane-denny** [eikek/docspell#1905]
### Short
Some PDFs are imported with broken thumbnails. When looking at the details of the import, the PDF can't be displayed and it's just a blank page, but this happens only in Firefox. Chrome, Safari and even Edge are able to render the PDF. 
![2023-01-04_14h03_54](https://user-images.githubusercontent.com/5427654/210561120-6c058dc9-b195-443e-938b-7841192188cf.png)

### Long
I am using a ScanSnap iX1600 and the software ScanSnap Home to scan my documents. Sometimes a document produces reproducable kinda broken PDFs as output when being scanned. I say kinda broken because it is only acting weird when using Firefox as a PDF viewer.

What I can say because I tried to find the root cause:
- It is OS independent, I have the same results on Windows as on macOS
- I get the same results when using the file import via the import folder as when importing it with the web UI
- When using VueScan as scanning software the PDF looks good everywhere
- The problem stays even when docspell is configured to use the cross-browser fallback for PDF preview. Then I am getting a short nonsens error message, but also only in Firefox:
```PDF.js v2.12.313 (build: a2ae56f39)
Message: 
Stack: putBinaryImageData@http://192.168.178.3:7880/app/assets/pdfjs-dist-viewer-min/2.12.313/build/minified/web/pdf.viewer.js:22:81838
paintInlineImageXObject@http://192.168.178.3:7880/app/assets/pdfjs-dist-viewer-min/2.12.313/build/minified/web/pdf.viewer.js:22:111951
paintImageXObject@http://192.168.178.3:7880/app/assets/pdfjs-dist-viewer-min/2.12.313/build/minified/web/pdf.viewer.js:22:111241
executeOperatorList@http://192.168.178.3:7880/app/assets/pdfjs-dist-viewer-min/2.12.313/build/minified/web/pdf.viewer.js:22:87094
_next@http://192.168.178.3:7880/app/assets/pdfjs-dist-viewer-min/2.12.313/build/minified/web/pdf.viewer.js:22:66261
__webpack_modules__</_scheduleNext/<@http://192.168.178.3:7880/app/assets/pdfjs-dist-viewer-min/2.12.313/build/minified/web/pdf.viewer.js:22:66091
```

## Steps to reproduce
Take the attached PDF and throw it into docspell.
[2023-01-04-13-55-36.pdf](https://github.com/eikek/docspell/files/10344335/2023-01-04-13-55-36.pdf)

## Expected result
A clean imported PDF

## Actual result
A not clean imported PDF

If you like I am also available for debugging sessions via E-Mail. :)

**Comment by eikek** [comment]
I think the pdf contains a very large image and docspell has some limits in place for this to avoid blowing the heap. It is interesting that pdfjs in firefox cannot display it! Can you try maybe to lower the dpi/size of the scan a bit and try again?

The cross-browser fallback is not working, because it uses the same code as firefox does, but bundled in the application. This allows to display the PDF even if a browser doesn't have support for this (i.e. mobile browsers).

**Comment by crane-denny** [comment]
I tried now by lowering the DPI and this indeed worked and fixed the problem. 
Thumbnails are shown correctly and the PDF renders normaly fast.

But I am still not sure why this happens in first place. The document itself is only text. And I would be really suprised by it if there would be any image embedded.

**Comment by eikek** [comment]
I think the document contains a quite large image that was produced by the scanner. Well it is only gray and can be compressed to a very low size, but when processing it (when doing the preview for example) it will be loaded fully into memory at some point. But you can increase the max allowed size for joex (in number of pixels), there are two `max-image-size` options to set, one for ocr and one for preview. You could try to increase it. The example file above has an image of 9936x13960 so 138706560 pixels. The default limit is 14000000.
