### ISSUE TITLE
Postgres Authentication for non-docker Server

### ISSUE THREAD

**Issue by FCUnlimited** [eikek/docspell#1918]
Hi,

I would like to use my existing postgres installation together with the Docker setup.
I got everything working except one point:
docspell has to authenticate at the postgres server. In the container the config file looks like this:
pg_hba.conf:
_local   all             all                                     trust_
this is fine since it is running in the docker environment.

But for the external server I have to change local to a IP address.
Because of this I would like to use md5 password encrypted authentication to keep my server secure.
It looks like docspell does not support this kind of authentication.

Am I right or have I got something wrong?

**Comment by eikek** [comment]
If I understand correctly you should be able to do so. Docspell allows to set the database user, ip and password via its config. Here is the config page: https://docspell.org/docs/configure/database/ maybe it helps?

**Comment by FCUnlimited** [comment]
Sorry looks like it was my fault. But I want to say Ive read the docs ;)
Several stones met my way. Maybe someone else meets them also:
- Webmin does not a restart of postgres on setting changes
- You have to save the user password with the right authentication mode already set? No idea, maybe there was also a copy paste error...

And nice to know: 
Im using linux and to connect to an existing db from a docker container you have to use the following url:
`DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:postgresql://172.17.0.1:5432/docspelldb`

In the postgres pg_hba.conf I added the following line
`host docspelldb docspell 172.19.0.0/16 md5`

*The ip gets changed easy to see if you use `docker logs docspell-restserver`

**Comment by eikek** [comment]
No worries, nice that it works now! This was more a postgres config issue so the docspell docs don't help there :)
