### ISSUE TITLE
jansi-2.4.0* files filling /tmp until disk is full

### ISSUE THREAD

**Issue by andreklug** [eikek/docspell#1937]
Basically what the title says.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/13343357/215330990-2094c938-4b13-4d0f-8e3f-262dc92fa01d.png">

I have for now created a cron job to delete the files ever ten minutes. But would like to understand what's happening here because 30GB every few days is unneccessary wear on the SSD.

**Comment by eikek** [comment]
Hm, that's weird - I don't see this on my machine. What system are you using and what kind of installation (docker) and docspell version?

**Comment by andreklug** [comment]
It’s the last release on debian bullseye without docker.

**Comment by eikek** [comment]
Thanks! What java version are you using (sorry forgot that)?

**Comment by andreklug** [comment]
***@***.***:~# java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb11u1, mixed mode, sharing)

**Comment by eikek** [comment]
Really strange. I think the only depenency bringing in this library is the logging library. In the current snapshot version of docspell the logging library has been updated and it doesn't include jansi anymore.

I don't know why it creates so many copies of the c library, that is really strange and looks like a bug. I think what you can try is change the logging format. It should only need jansi for the "fancy" format, to print all this fancy colors. Try change it to  one of the other options, like `Plain`. Might be even better if you run it through systemd/journald.

**Comment by andreklug** [comment]
Thank you! Where can I change the logging options?

**Comment by eikek** [comment]
You can define it in the config file for each component.
```
docspell.[server|joex] {
  logging.format = "Plain"
}
```

https://docspell.org/docs/configure/defaults
https://docspell.org/docs/configure/main/#logging

**Comment by eikek** [comment]
Hey @andreklug - could you solve this problem with a different log setting? I tend to close this, because the jansi library is not included anymore in the current code.

**Comment by andreklug** [comment]
Hi @eikek - I didn’t change it yet. Please go ahead and close, I will reopen if needed.
