### ISSUE TITLE
Issue with deleting users

### ISSUE THREAD

**Issue by Burny92** [eikek/docspell#1941]
Hi there,
i have tried a few dms systems and have to say, i will stick to docspell. I really like it, big thanks to all devs!
While trying and playing with docspell, i have found out, that i cannot delete created users. I can disable them, but i'am not able to remove them. If i try to, i'll get an error message "not found".
So the question is: How can i remove the users, i want to delete?
Another question regarding this topic: Is it possible, to delete not even users, but collectives, too?
And something offtopic: Is it possible, to set a default timezone and language?
Thank you in advance!

I have deployed docspell via docker compose, if you need anymore information, just let me know.

With kind regards,
Marc

**Comment by eikek** [comment]
Hi @Burny92 , thank you for your kind words!

Deleting a user: this should work - if it doesn't then it's a bug 😞 

Deleting a collective: this is not possible at the moment via the api or webui. I could find some SQL statements that you need to run against the database directly. All users should be removed before using the webui or api. But this sadly is not working atm.  So currently, also not possible.

Default timezone and language: You can set a default for both in the collective settings (if you mean the ones used in the ui). 

So, I will fix the user deletion bug as soon as I can. Thanks for pointing it out!

**Comment by eikek** [comment]
Hi @Burny92 I fixed the delete user problem. In some time the nightly release will be updated. If you want you can test it with this version.

**Comment by Burny92** [comment]
Good morning,
thank you for the quick response and fix!
Sure, if you have anything to test, just let me know :)
To the default timezone and language: Yes, i meant the UI settings. I cannot set them per collective, there i can only set the document language for OCR.
It think it would be really nice, if i could set a default timezone and language for all users and collectives systemwide, so even the Login Screen would be in default language. But it's nothing important, only for some family members it would be helpful i guess.
Thanks again for your help!

With kind regards,
Marc

**Comment by eikek** [comment]
You can test deleting users with the current nightly docker images, if you want.

Regarding timezone: this is a bit confusing (should be improved, but time is tight :)). There are user profile settings that apply to the user. And not long ago the same settings can be applied to a collective. It is the same dialog, but you can toggle whether to apply to a collective or user. There you can set ui language and timezone and apply it to a  collective.

But, it's not possible to set it system wide at the moment, but a reasonable feature request, I guess. There is the idea to inspect the browser preferences and set the ui language accordingly, but same as above - no time currently 😃 I think a server side setting is ok as well as a last resort fallback.

**Comment by Burny92** [comment]
Hey @eikek Thank you very much for the quick fix! I will test when i got some left.
To the timezone/language topic: For me it would be perfectly fine, if i could set the defaults in the settings systemwide, more is not needed. Sure it would be nice, if docspell would take a look at the browser preferences, but it's just another nice to have option ;)
If i have tested it, i will drop a quick comment.
I wish you a nice weekend, thanks for your support!

**Comment by pschichtel** [comment]
@eikek you said something about some SQL to delete a collective, is there more to it than this?

```sql
BEGIN TRANSACTION;
DELETE FROM user_ WHERE coll_id IN (SELECT id FROM collective WHERE name = 'collective-name');
DELETE FROM collective WHERE name = 'collective-name';
COMMIT;
```

That's what I used to delete an empty dummy user/collective I just created.

**Comment by eikek** [comment]
@pschichtel That should do it, if the collective wasn't used much. There could be other linked data where you'd get an error due to sql constraints. There also are some cases where the collective id is stored in some data (e.g. task arguments) where you wouldn't get an sql error - but it would also not hurt much (besides having a few kb of data that is not used anymore). The users can have the same issues, of course.
