### ISSUE TITLE
Proposal: Make fields hideable

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#195]
First of all, many thanks for this really great software! 👍 
I have tried many different DMS for home use and this one, although still in beta status, is by far the best 🥇 

Now for my proposal. I don't need any due dates or directions in my workflow. How about making it configurable which fields you hide?
This would significantly increase simplicity and clarity, especially if more functions are added in the future.

**Comment by eikek** [comment]
Hi @eresturo , than you very much!

I like the idea. The menus are getting quite filled now. With 0.9.0 there is even one more field (the folder). So I think it would already be enough to simply hide it in the ui, since they are all optional anyways.
