### ISSUE TITLE
FR: Custom field/numeric - normalize , to .

### ISSUE THREAD

**Issue by adlerweb** [eikek/docspell#1975]
When using "numeric", typing a ',' results in a error message like "Not a number: 12,34". When using "money" inputs are normalized, in this case typing a "," automatically will replace to '.'. https://github.com/eikek/docspell/blob/e7556311c5cae706408fef5a0519612a0451f943/modules/webapp/src/main/elm/Data/Money.elm#L65
As ',' isn't parsed as thousand separator anyway it would be great to apply this normalization for numeric fields too. This would make it easier to enter decimals when using a keyboard layout optimized for ',' as decimal separator.

**Comment by eikek** [comment]
Oh yes, thanks for reporting!
