### ISSUE TITLE
pls delete

### ISSUE THREAD

**Issue by tknobi** [eikek/docspell#202]
-

**Comment by eikek** [comment]
Hi @tknobi , I'm deleting this issue as you requested. To answer the question real quick: just for simplicity. adding more values for equipment and people involves more complex queries and I wanted to not "overengineer" it at the beginning (it has implications for suggestions and makes this much more complex). It might be possible to open it for more values and I understand your point, but at the moment it's not on my list. I simply don't associate a person for documents to me and my wife or the family – that seems ok for my use-case as its just us anyways. Now, there is also no way to search for items that have *no* persons or equipments yet (I never needed it); so maybe a tag can be used to mark these items. The "concerning" data was intended to cover the "topic" of a document, most of the time for my files anyways, it's just one thing.
