### ISSUE TITLE
improve search

### ISSUE THREAD

**Issue by torak1981** [eikek/docspell#203]
First of all you made a really good piece of software, thank you for this :) 

I have put a few documents in it and testing in out right now. So I have created some tags and I'm really liking the possible to group the tags with categories together. In the overview it helps to have these with the same color, good idea to make this possible. What I'm missing is the possibility to search for categories or to search for more than one tag (with an "or" condition not with an "and"). I think an option to switch between "and" and "or" in the search view would be the most flexible but also the most complicating way (from user perspective). So the possibility to search for a category would solve this without over-complicating the interface. 

Example:
tag1: apples 
tag2: oranges
category: fruits

Right now I can search for apple or oranges, but I can't filter for fruits

**Comment by eikek** [comment]
Hi @torak1981 , thank you very much!

I see what you mean. I have plans to rework the search menu anyways with a better component for selecting tags. I will try to add categories to this list or maybe allow to configure the composition (`and` vs `or`). Never thought about searching for categories, but I can see that this is a nice thing. Thanks for your input!
