### ISSUE TITLE
Only support the date from 2010, what about the older files？

### ISSUE THREAD

**Issue by iszhi** [eikek/docspell#2032]
I'm going to move my saved documents into Docspell. Recently I found that it only allows me to set the file date from 2010. But what about the older files?

![image](https://user-images.githubusercontent.com/33443222/230716965-f9da94db-0500-43ac-8cd9-54814a34689c.png)

**Comment by TheFehr** [comment]
You can easily enter the date in the textfield. I think the calendar widget is just missing buttons to go back further in the years.
