### ISSUE TITLE
Position of the mask to create a new person / organization.

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#205]
I hope not to be annoying, just start using the software and keep noticing things :)

When you create a new organization / person, the popup opens over the document, so you can no longer copy name / address / e-mail / etc. from the document.
One possibility would be to have the popup only in the left area, i.e. to cover only the input mask for metadata.
It would also be cool if you could mark and copy text in the document to replace annoying typing with copy and paste.

Furthermore, it would be great if this mask could also be called up for editing, for example to add information that is available for the first time in the current document.

**Comment by eikek** [comment]
No, not annoying at all! I appreciate your inputs, thank you!

I think these are nice ideas! I also have been annoyed by the modal that made it impossible to copy things. I will try to have it only above the menu (which I want to redo anyways). I really like this idea, this should be simple to do.

Not sure what you mean by "mark and copy text in the document"? This should be possible already, if the document allows it (i.e. there is a text layer in the pdf)… or do you mean something else?

**Comment by eresturo** [comment]
Exactly, the idea was to copy from the text layer of the PDF. But this requires several copy operations. For example, starting with name, then street, then zip code, and so on, which is currently not possible because of the overlay.
