### ISSUE TITLE
best practice: how to update from 0.23?

### ISSUE THREAD

**Issue by Hobbabobba** [eikek/docspell#2062]
I run my installation on version 0.23 
What is the best way to update it docspell to the latest version? Esp. the change from 0.23 to 0.24 looks challenging.

**Comment by eikek** [comment]
Did the upgrade went well? I was going to anwser that you might just try and then we can see what to do if something goes wrong. I would suggest to use the new compose files if you are using docker and adjust them to your needs. And before upgrading always do a database backup.

**Comment by Hobbabobba** [comment]
Release by release updates worked very well. Just had to compare the docker-compose files very careful.
