### ISSUE TITLE
Improve handling of dropdown fields and make search feature configurable

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#207]
Is it possible to add a search to the person and organizations dropdowns? Similar to the tags input search.

**Comment by eikek** [comment]
This is already the case, but it is "configured" (aka hardcoded :)) to start with 6 elements. So if the dropdown has fewer elements, there is no search. But this should be possible to be moved into the ui settings.

**Comment by eresturo** [comment]
Oh, I missed that. Is there a reason for the minimum? Otherwise, you could just leave that distinction out. Personally, I prefer to use the keyboard over the mouse anyway and would configure it to zero.

**Comment by eresturo** [comment]
Something else that I noticed about the dropdowns: You can't press directly into the dropdown field and search, but you have to first open the dropdown on the right side of the small arrow, then press back into the field and only then you can type.

**Comment by eikek** [comment]
This is nowhere documented, so it's really hard to find :). For the dropdowns: I have the opposite (kind of); when search is enabled, I need to click on the little arrow to open the dropdown, but I can click directly into the search field. If search is not enabled, I can click on the whole dropdown field to open it. These dropdowns should be reworked to be more convenient to handle.

**Comment by eikek** [comment]
Ah I see now what you mean, sorry! Yeah, it seems to depend whether there is one or more values possible. I rename this issue to improve the dropdown fields usage (including making the search-limit configurable and 0).

**Comment by eikek** [comment]
Dropdowns are now always searchable. You're right – it's convenient to use search to select from just two elements and if you don't use it, it's not in the way. Dropdowns can now be clicked "normally" to open and not only on the small arrow.
