### ISSUE TITLE
Multi user capabilites

### ISSUE THREAD

**Issue by MarcSN311** [eikek/docspell#21]
Hi,
from the documentation it is not clear to me whether can organize documents for more than one person independent of each other.

 Example: I don't want my girlfrind to see the bills for her birthday presents. 

Is that possible?

**Comment by eikek** [comment]
Hi,

I like the idea, but this is currently not possible if you are both members of the same collective.

Currently all members of a "collective" have equal rights regarding documents. Every member can see every document. (I thought that I have somewhere statet this, I'll look into the docs to try being more clear). The use case here is that a household/family might have multiple users to deal with bills/contracts etc. While you can associate people to items, there is no visibility implemented.

You could create a different collective account with yourself as the only member and use this "private" account for things like you described.

**Comment by MarcSN311** [comment]
If we could make one user to be member of multiple collectives that would solve everything. 

Collectives: Me, Girlfriend, Household
Girlfriend an I are part of our own collective respectively and we are both part of the household collective.

**Comment by eikek** [comment]
Ah, that sounds good, indeed! Unfortunately, this requires a change in the data model, because the user currently has a to-one relationship to a collective. There are also some other implications. The user must then have a unique login name and you wouldn't login into a collective, but rather only using your login and see documents from all your collectives. Then there needs to be something like a "collective owner" that can add/remove users etc …. I have to think more about it. I really like the idea, I wish I had talked to you before creating the current state :). It seems like a fundamental change.

**Comment by MarcSN311** [comment]
I do understand, that this has major implications. If you are generally inerested in this Idea I would fork the project and start hacking around. I'm new to Scala and ELM though, so don't expect anything to soon ;)

**Comment by eikek** [comment]
Yes,  sure I'm interested! I also thought about a naive way by optionally associating a user to an item to create "private" items that can be filtered. But your  idea is better; it is similiar to how organizations work on github I think. I just don't know really how to implement it without changing almost everything.

Never worry about any timeline, I also have only little time for these things.

**Comment by eikek** [comment]
Hi, I thought a little bit about this recently and I'm now considering using your idea within a collective. So a user would create a "space" (no good idea for a name yet) and assign other users to it. Only an owner (the user who created it) can assign users to a space. An item can be associated to a space. Then a user sees all items that either have no space assigned or a space that he/she is a member of. This can be used to have "private items" and also for other organizational things.

**Comment by eikek** [comment]
Hi @MarcSN311 ,  just want to reach out to ask if you already put some effort into this. I'd like to start to explore the idea above, but wanted to check for your status here first.

**Comment by eikek** [comment]
Hi @MarcSN311 , in upcoming 0.9.0 there is now the possibility to create "folders" and associate users to them. Items can be placed into a folder and only users that are members of this folder can see them.

**Comment by sanbroz** [comment]
Hi, Currently a user is able to list and delete another user accounts in Collective Settings. I think a user should not be allowed to delete or modify another user account. A user with same collective & user name can be assumed master admin account which can modify all other user accounts.

**Comment by eikek** [comment]
Hi @sanbroz true, currently all users are equal in a collective. Please create new issues for new things, this one is almost 2 years old, closed - and also about something different :).

**Comment by cirrusflyer** [comment]
I just started using Docspell.  It's really nice, but I also don't understand user management.  Is there an admin user?

**Comment by eikek** [comment]
Hi @cirrusflyer , there is no admin user in docspell. However, the user who installs docspell can use some admin functionality through the cli. May I kindly ask to create new issues for new questions? It.s much easier to track and find later. You can always open new issues and ask anything or alternatively go to the gitter chat, if you prefer.
