### ISSUE TITLE
Docker error on starting

### ISSUE THREAD

**Issue by eliluong** [eikek/docspell#210]
Hi, I've installed docker and docker-compose, can run `docker-compose up` but am running into this error. I also deleted the entire docspell folder and pulled it from github again. Thanks.

```
osboxes@osboxes:~/Downloads/docspell/docker$ docker-compose up
Starting docspell-solr ... done
Starting postgres_db   ... done
Starting 48412a6dfdab_docspell-joex       ... done
Starting 0d84a8053338_docspell-restserver ... done
Starting docspell-consumedir              ... done
Attaching to docspell-solr, postgres_db, 0d84a8053338_docspell-restserver, docspell-consumedir, 48412a6dfdab_docspell-joex
0d84a8053338_docspell-restserver | bash: /opt/docspell-restserver-0.9.0/bin/docspell-restserver: Permission denied
docspell-consumedir | bash: /opt/docspell-tools-0.9.0/consumedir.sh: Permission denied
0d84a8053338_docspell-restserver exited with code 126
48412a6dfdab_docspell-joex | /bin/sh: can't open '/opt/entrypoint.sh': Permission denied
docspell-consumedir exited with code 126
docspell-solr | /bin/bash: /opt/docker-solr/scripts/docker-entrypoint.sh: Permission denied
postgres_db   | bash: /usr/local/bin/docker-entrypoint.sh: Permission denied
postgres_db exited with code 126
docspell-solr exited with code 126
48412a6dfdab_docspell-joex exited with code 2
```

**Comment by eikek** [comment]
Oh that is strange. It seems the scripts don't have permissions set correctly. But they have the correct permissions, because even the solr image doesn't start, and this is provided by solr.

What OS are you running on and what docker-compose version are you using?

**Comment by eliluong** [comment]
Hi, I ran this on Ubuntu 19.10. I've always used `sudo docker-compose up` to run docker images, maybe this is where the error happened. Docker version 19.03.12, build 48a66213fe and docker-compose version 1.26.2, build eefe0d31. I ended up removing all docker stuff, reinstall, configure to run without sudo, and I am able to install it and load the initial page in the browser now.

Now I ran into another problem - I create a new collective, user, password, but can't log in unless collective and user are the same. I can't use any old collective names I used when trying to create accounts.

**Comment by eikek** [comment]
If you have the same name for collective and user, say `doe`, you can login with just `doe`. Otherwise you need to write `collective/user`. For example `doe/john`, when `doe` is the collective and `john` the username. If you can't login, then either the account name (collective + user) is wrong or the password.

**Comment by eliluong** [comment]
Thanks, it wasn't clear to me that I would need to log in with `collective/user` format. Now I have five different collectives I created trying to figure out what was the issue with login XD

**Comment by eikek** [comment]
You're welcome. There is some info about collectives [here](https://docspell.org/docs/intro/#collective). If you want to get rid of the extra collectives, you'd need to remove them manually from the database. But they shouldn't do any harm either :).
