### ISSUE TITLE
Why I didn't the new look in the README file? are they from nightly build tag?

### ISSUE THREAD

**Issue by iszhi** [eikek/docspell#2104]
I just checked all latest tags. They newest tag is still from 3 months ago. Howeve, I did see a new look of it, which looks nice. I want to try.

**Comment by eikek** [comment]
Hi @iszhi I'm sorry, I don't really understand the issue. What did you do and what did you expect to happen? Last release was about 3 month ago, that is correct.

**Comment by iszhi** [comment]
@eikek Hello, I attached my version below, which looks very like an old version, isn't it? 
![image](https://github.com/eikek/docspell/assets/33443222/98a68506-10d1-43a7-ba2f-5b7e18027787)

**Comment by eikek** [comment]
I'm not sure why you think this is an old version? It looks ok to me. The UI didn't have huge changes for some time. If you go to the dashboard page, the version is printed below the menu at the bottom.

**Comment by iszhi** [comment]
It's 0.40.0. What I want to have is to show the count on the top, like what you showed.

**Comment by eikek** [comment]
Ah, you mean this summary table? You need to add items first and associate custom fields of type number of money. Then this box will show up, showing the overall count (that is 0 in your screenshot) and a summary table as in the screenshot in the readme. [This page](https://docspell.org/docs/webapp/customfields/) gives some details about custom fields and mentions the statistics box at the bottom. In the ui settings, in the "Item Search" tab, you can also enable/disable this box by checking "Show basic search statistics by default".

**Comment by iszhi** [comment]
Yeah. I see. I'll explore it Now.
