### ISSUE TITLE
Question: Multiple versions for same document possible?

### ISSUE THREAD

**Issue by TheBinaryLoop** [eikek/docspell#2142]
Hey, I wanted to ask if it is possible to upload multiple versions of the same document as versions for the same document? If not, is this a feature that would be considered for implementation?

**Comment by eikek** [comment]
Hi @TheBinaryLoop ,

unfortunately, this is not supported by Docspell. You can use the current features to get some kind of "poor mans versioning". Docspell works with "items" that can group together many files. So it is possible to upload many versions of the same file and treat it as one unit. But docspell doesn't know about it being different versions of the "same" document. So there are no features build on this and it could be hard to distinguish the different versions.

I don't think that this will be added to Docspell. I don't need it for myself and it is quite some work. If others would like to do it, I'm happy to assist.
