### ISSUE TITLE
Docspell restserver does not start anymore

### ISSUE THREAD

**Issue by PascalHessler** [eikek/docspell#2153]
I did some manuall changes at the database (regrating this now). And now my frontend does not load anymore. I think there is some issue with links to a file which i deleted (I also deleted some old collectives and users).

I am getting this result:
2023.07.03 17:42:11:0013 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Current version of schema "public": 1.39.3
2023.07.03 17:42:11:0014 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Schema "public" is up to date. No migration necessary.
2023.07.03 17:42:12:0000 [io-comp...] [INFO ] docspell.backend.ops.ONode.register:52 - Registering node rest1
2023.07.03 17:42:12:0001 [io-comp...] [INFO ] docspell.notification.api.EventExchange.consume:48 - Starting up 2 notification event consumers
2023.07.03 17:42:13:0000 [io-comp...] [INFO ] docspell.pubsub.naive.NaivePubSub.subscribe:89 - Adding subscriber for topics: NonEmptyList(Topic(job-finished))
2023.07.03 17:42:13:0001 [io-comp...] [INFO ] docspell.pubsub.naive.NaivePubSub.subscribe:89 - Adding subscriber for topics: NonEmptyList(Topic(job-submitted))
2023.07.03 17:42:12:0002 [io-comp...] [INFO ] org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop blaze-selector-0
2023.07.03 17:42:12:0003 [io-comp...] [INFO ] org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop blaze-selector-1
2023.07.03 17:42:12:0004 [io-comp...] [INFO ] org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop blaze-selector-2
2023.07.03 17:42:12:0005 [io-comp...] [INFO ] org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop blaze-selector-3
2023.07.03 17:42:12:0006 [io-comp...] [INFO ] org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop blaze-acceptor-0-0
2023.07.03 17:42:13:0000 [io-comp...] [INFO ] docspell.backend.ops.ONode.unregister:57 - Unregister app rest1
2023.07.03 17:42:13:0001 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:330)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:224)
        at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.$anonfun$bind$1(NIO1SocketServerGroup.scala:258)
        at scala.util.Try$.apply(Try.scala:210)
        at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.bind(NIO1SocketServerGroup.scala:257)
        at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup$$anon$1.bind(NIO1SocketServerGroup.scala:109)
        at org.http4s.blaze.server.BlazeServerBuilder.$anonfun$resource$4(BlazeServerBuilder.scala:413)
        at map @ org.http4s.blaze.server.BlazeServerBuilder.mkServerChannel$1(BlazeServerBuilder.scala:410)
        at make @ docspell.common.ThreadFactories$.executorResource(ThreadFactories.scala:48)
        at make @ docspell.common.ThreadFactories$.executorResource(ThreadFactories.scala:48)
        at uncancelable @ fs2.Pull$.acquireCancelable(Pull.scala:423)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Compiler.scala:161)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at uncancelable @ fs2.Compiler$Target.uncancelable(Compiler.scala:165)
        at unique @ fs2.Compiler$Target$ConcurrentTarget.unique(Compiler.scala:194)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at ref @ fs2.concurrent.Topic$.apply(Topic.scala:154)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)

In my Flyway fixup history i have this entries:
 installed_rank | version |      description      |   type   |              script               |  checksum  | installed_by |        installed_on        | execution_time | success
----------------+---------+-----------------------+----------+-----------------------------------+------------+--------------+----------------------------+----------------+---------
              1 | 1       | << Flyway Baseline >> | BASELINE | << Flyway Baseline >>             |            | dbuser       | 2023-02-15 16:50:02.466257 |              0 | t
              2 | 1.33.0  | fix reorganize files  | SQL      | V1.33.0__fix_reorganize_files.sql | 1347412019 | dbuser       | 2023-02-15 16:50:02.668944 |             52 | t

I hope you can help me with this.

Best Pascal

**Comment by eikek** [comment]
What exactly did you change? This `UnresolvedAddressException` indicates that some address/hostname is invalid and can't be resolved. It could be in the config file, like `base-url` or similar?

**Comment by PascalHessler** [comment]
Hey, I did delete some collective id, and everything connected with it (users tags etc. and one document). Afterwards I restarted the resterver container and got the 503 error in the frontend and the container does not start up correctly and then is in a restarting loop. base-rul was not changed. In general I did not change the config files.

**Comment by eikek** [comment]
Oh that is weird! I somehow doubt that the db change is the cause here. As long as the structure is not changed, the service should start up. The error message still indicates some invalid hostname or similar to me. Could you perhaps try the same docker compose setup in a fresh environment (different dir, empty db)?

**Comment by PascalHessler** [comment]
Hmm yeah that is weird. I did what you said and after the first migration, same error problem occures. So I did not destroy the databse^^.
Here is the docker config snapshot for the Restserver, perhaps there was an update and we have to update something?
`        docspell-restserver:
                image: docspell/restserver:latest
                container_name: docspell-restserver
                restart: unless-stopped
                networks:
                    - docspell-tier
                ports:
                  - "7880:7880"
                environment:
                  - TZ=Europe/Berlin
                  - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver:7880
                  - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=*****
                  - DOCSPELL_SERVER_AUTH_SERVER__SECRET=*****
                  - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=*****
                  - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:postgresql://docspell-db:5432/dbname
                  - DOCSPELL_SERVER_BACKEND_JDBC_USER=*****
                  - DOCSPELL_SERVER_BIND_ADDRESS=https://*****/
                  - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
                  - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
                  - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
                  - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
                  - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=*****
                  - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
                  - DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD=*****
                  - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
                depends_on:
                  - docspell-solr
                  - docspell-db`

**Comment by eikek** [comment]
I think the `DOCSPELL_SERVER_BIND_ADDRESS` is the problem. It must be a host address not an url, like `0.0.0.0` (the default), the address of the interface to bind the server to.

**Comment by PascalHessler** [comment]
nope did not change anything

**Comment by eikek** [comment]
Please try the exact environment variables from the [standard file](https://github.com/eikek/docspell/blob/master/docker/docker-compose/docker-compose.yml) - this works. And then you can change one item at a time towards your config.
