### ISSUE TITLE
Windows 11 - java.nio.file.InvalidPathException: Illegal character

### ISSUE THREAD

**Issue by magge-faf** [eikek/docspell#2159]
**Edit**: I fired up Ubuntu on a VM, started Docspell via Dockers and bridged the VM network to gave me access to the link:port via Windows PC. Making it run directly on Windows is too inconvenient, currently. Docker image for Windows is not supported anymore.

---

When I follow the tutorial from here: https://docspell.org/docs/install/download-run/ and I start the docspell-restserver.bat via CMD, I get following error:

`General error: "java.nio.file.InvalidPathException: Illegal character [:] in path at index 3: //C:/Users/name/AppData/Local/Temp//docspell-demo.db`

I assume the // behind Temp path are making issues - Is there anything I can do on my side to fix this?

---

![image](https://github.com/eikek/docspell/assets/101107758/508688d1-dfd6-4f42-832d-036582d16a8a)

**Comment by eikek** [comment]
Ah right, the default value in the config creates a JDBC url from the current temp directory. that doesn't work for windows because of the colon. You can change the url or use a different database (like postgres). One of this is recommended anyways if you like to use it more seriously.

For example, you can use an environment variable:
```
DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:h2://C/Users/name/AppData/Local/Temp//docspell-demo.db;MODE=PostgreSQL;
```

or starting it with the following option should also work:
```
docspell-restserver.bat -Ddocspell.server.backend.jdbc.url=""jdbc:h2://C/Users/name/AppData/Local/Temp//docspell-demo.db;MODE=PostgreSQL"
```

A more sophisticated way is to create a config file and pass it as the only argument when starting. More on this [here](https://docspell.org/docs/configure/main/).

**Comment by magge-faf** [comment]
Thanks for your fast reply

I think you missed " after docspell-demo.db

Before:

`docspell-restserver.bat -Ddocspell.server.backend.jdbc.url=""jdbc:h2://C/Users/name/AppData/Local/Temp//docspell-demo.db;MODE=PostgreSQL"`

After:

`docspell-restserver.bat -Ddocspell.server.backend.jdbc.url=""jdbc:h2://C/Users/name/AppData/Local/Temp//docspell-demo.db";MODE=PostgreSQL"`

Unfortunately, the issue is still persistent with that path:

Error log:


`org.h2.message.DbException: Log file error: "//C/Users/name/AppData/Local/Temp/docspell-demo.db.trace.db", cause: "org.h2.message.DbException: Error while creating file ""//C/Users/"" [90062-214]" [90034-214]
`

If I try with a more minimalistic approach:

`docspell-restserver.bat -Ddocspell.server.backend.jdbc.url=""jdbc:h2:/test/docspell-demo.db";MODE=PostgreSQL"
`

I get the path working, and it creates the files, however it encounters the next issue after he created the files:

![image](https://github.com/eikek/docspell/assets/101107758/78841067-ad3c-4798-bd29-4f2502e25880)

![image](https://github.com/eikek/docspell/assets/101107758/5bb44712-312d-408a-8e60-d838794b5b9c)


Any idea how to approach?

**Comment by eikek** [comment]
Hi @magge-faf sorry I'm too tight with time right now. Did you manage to solve it? From here it looks like the database is broken. Perhaps try with an empty directory/database.

**Comment by magge-faf** [comment]
Don't worry - I am running it via Ubuntu now. Thanks for trying to help me with Windows. I have edited my first post.
