### ISSUE TITLE
docker-compose: bind env variable seems to be ignored

### ISSUE THREAD

**Issue by michelwilson** [eikek/docspell#2185]
I'm trying to bind the server and joex to `localhost`/`127.0.0.1`, by having the following in my `.env`:
```
DOCSPELL_SERVER_BIND_ADDRESS=127.0.0.1
DOCSPELL_JOEX_BIND_ADDRESS=127.0.0.1
```
but this seems to be ignored. What is the proper way to bind to `localhost`?

**Comment by eikek** [comment]
I think this is more a docker question :-) I'm not at all docker expert, so jus trying here. If you want to run the docker-compose stack as given, I think you cannot bind to localhost. If I'm not mistaken, there is a virtual network created and binding to localhost wouldn't allow the other component to connect from inside the network. If you set the `bind.address` to localhost, it doesn't change the port. There is a similar env variable to change the port to bind to. Then the docker compose file already exposes ports. I'm not sure what setup you are trying to run, it's a bit hard for me to guess what is missing.
