### ISSUE TITLE
Drop a Collective

### ISSUE THREAD

**Issue by cpzengel** [eikek/docspell#2218]
Cant find any way to delete, drop or remove a entire collective.
Please provide a hint, how to do!

**Comment by eikek** [comment]
Hi @cpzengel, there is currently no easy way to do that unfortunately. The workaround for now is to remove everything possible via web or api (i.e. files and users) and then run some sql against the database to clean up the rest. Another way is to mark the collective as disabled via SQL as well. Then it still exists, but login is not possible.

Here are some notes about it: https://github.com/eikek/docspell/issues/1941#issuecomment-1558110683

**Comment by cpzengel** [comment]
Thanks for your Reply
How can I remove all Files from a collective to free Space via API
Talking about 100k to free space

**Comment by eikek** [comment]
This requires some scripting. You can use the command line client to some extend, i.e. to login and search all items that you want to delete. Then a curl can delete each item. Here is starting point:

```bash
#!/usr/bin/env bash

dsc login

# grep the token for the curl command
token=$(jq -r '.token' < ~/.config/dsc/dsc-token.json)

for id in $(dsc -f json search --no-details --limit 100 'date>2020' | \
                jq -r '.groups[]|.items[]|.id')
do
    echo curl -XDELETE -H "X-Docspell-Auth: $token" https://your.docspell.org/api/v1/sec/item/$id
done
```

The `dsc search` finds some items, the query is required but can be something to select all. You need to play with the limit a bit, perhaps you can delete much more in one go.

**Comment by cpzengel** [comment]
Thanks, this is working great.
Got it looping to remove 80k items
Is it possible to find all items that does not contain text?
I am a host of an open source show on youtube and did four pictures of ervery minute of the show.
So now i want to find all items just showing me talking!
cheers chriz
sysops.tv and zfs.rocks

**Comment by cpzengel** [comment]
As I vacuumed my PSQL I found that all Items now are in Trash
How can I empty the trash? Found no Button and tried something like

curl -XPOST -H "X-Docspell-Auth: $token"  -H "X-Docspell-Auth: $token" https://docs.xxx.de/api/v1/sec/collective/emptytrash/startonce
The request body was malformed

**Comment by eikek** [comment]
You might need to specify a content type of `application/json`. The api doc for this call is [here](https://docspell.org/openapi/docspell-openapi.html#tag/Collective/operation/sec-collective-emptytrash-start-now). It should work with an empty request, but maybe it's not (or an empty json object, I currently can't recall). The ui calls it with a request payload. You can go to your collective settings and run the empty-trash task from there.

**Comment by eikek** [comment]
> Is it possible to find all items that does not contain text?

It's not possible via the provided query, but you could find out querying postgres directly. There is a table `attachmentmeta` that has a `content` column. This column holds the extracted text. You can join it with `attachment` (via `attachid`) and find out the `itemid` this way. You might need to check, if these items really have no text, sometimes OCR might result in some gibberish….

**Comment by cpzengel** [comment]
I have now all Items in Trash, but no Idea how I can empty it.
Please provide help, its 80k Files!

**Comment by eikek** [comment]
You can go to your collective settings and run the empty-trash task from there.
