### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#225]
Hi, 
I just had another idea what could increase the efficiency of using this great program. How about assigning keyboard shortcuts to important functions?

For example, I'm currently going through a lot of old documents and have to confirm them. I would be faster if there were shortcuts for Confirm and next document buttons.

Sheers
eresturo

**Comment by eikek** [comment]
Ah, yes this is a nice idea, thanks! The only difficulty is to select the shortcuts. Best would surely be to have it configurable, but also the most work.

**Comment by eikek** [comment]
If enabled in ui-settings, the item detail view allows following shortcuts if edit menu is open and focused:
- `Ctrl-c` for confirm/unconfirm
- `Ctrl-.` for next item
- `Ctrl-,` for previous item

The dropdowns are also improved to work with the keyboard (independent of ui settings):
- iterate options using `n` and `p` (emacsy), `j` and `k` (vimy) and arrow keys
- select option with `RET`
- Unselect/Delete selected item with `ESC`
