### ISSUE TITLE
Tag / Folder / Category Selection

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#226]
Hello again :) 
In the outdated example screenshot from the Readme, tags folders and categories are listed according to the number of documents and can be pressed quickly. In the latest version, however, this has been replaced by a dropdown. May I ask why? Couldn't one have both? Or make it configurable? Or combine them?
Sheers
Eresturo

**Comment by eikek** [comment]
Hi, this is a bit of bad luck :-) Usually the screenshots are outdated really quick, so I mentioned it. But this time, one shows the future :) I have worked on the ui of the search/list view and it is now as you see it in the screenshot of the master branch. So this will be released with 0.10.0 (maybe this weekend). The dropdown is gone and replaced by a menu like structure for tags/categories and folders. The little downside is, that you have to use the mouse, now.

**Comment by eresturo** [comment]
Ok, great, thanks for the info :)
