### ISSUE TITLE
session-valid overflows between 24 and 25 days

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2309]
[This is over from #2292 to split the two seemingly unrelated issues]

After I log in, Docspell goes into a bit of a tornado, and will attempt to "add account to local storage" (from browser console) multiple times a second:

![image](https://github.com/eikek/docspell/assets/195073/afedbec2-17a2-4cb4-bc6f-e4bce9a9cb37)

These are calls to `/api/v1/sec/auth/session`, causing the auth cookie and also the account data in local storage to change every time, as a new token is received. And megabytes of data to be transferred within minutes.

There is no way to stop this, other than to close the tab. Meanwhile, the CPU goes into party mode, and the machine heats up.

Note that it happens to me on Firefox, Chromium, as well as a fresh Firefox profile in a fresh Windows 11 install.

It does not matter whether I am using OIDC or local auth.

**Comment by eikek** [comment]
Wow, that is very strange! It is a client bug, when looking at the video in the other issue. I just can't reproduce it (I need to fiddle more with the config). Did you try perhaps without any proxy in between? Going directly to the `:7880` port? Something is causing the session requests to go into an endless loop. Did you perhaps set some quite short life-time period for the session? (it would be `session-valid` in the config)

**Comment by madduck** [comment]
`session-valid` is at 30 days. And yes, the problem exists if I go directly to `:7880`, unfortunately.

If it helps, I can give you access to the server…

**Comment by madduck** [comment]
@eikek any further ideas? We're very close to getting ready to import our 411'000 documents, but as it stands, Docspell is not really usable as-is. Just having the app open in the browser means high CPU time and laptop fans going crazy.

**Comment by eikek** [comment]
Ah, I was suspecting the `session-valid` setting a few comments above. This should be a rather small value. The ui refreshes it periodically. I think the default is 5 minutes. I need to look at it later (currently not really on a computer), could be that a too big or too small value triggers some overflow issue.

**Comment by madduck** [comment]
Well, looks like you might have a signed integer in play for a time period. ;)

```
24 days * 86,400,000 milliseconds/day = 2073600000
                                  2³¹ = 2147483648
25 days * 86,400,000 milliseconds/day = 2160000000
```
