### ISSUE TITLE
Unable to log out

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2310]
[This is over from https://github.com/eikek/docspell/issues/2292 to split the two seemingly unrelated issues]

I am not able to log out of Docspell, with OIDC or local auth. If I do, I am sent back to the Login screen, or the SSO screen, but if I go back to the previous page, I find myself still logged in.

Here is a video: https://scratch.madduck.net/docspell-cannot-log-out.webm

And here a screenshot of the logout `POST`:

![image](https://github.com/eikek/docspell/assets/195073/614054b7-9ab9-420f-afaf-fa94aa4204bc)

**Comment by eikek** [comment]
Wow, that is very strange! It is a client bug, when looking at the video. I just can't reproduce it. Did you try perhaps without any proxy in between? Going directly to the `:7880` port? Something is causing the session requests to go into an endless loop. Did you perhaps set some very short life-time period for the session? (it would be `session-valid` in the config)

**Comment by madduck** [comment]
I am quite sure this issue is a result of #2309 and can be closed.
