### ISSUE TITLE
Docker image missing JAI

### ISSUE THREAD

**Issue by frankhommers** [eikek/docspell#2312]
I have this error when running everything from the docker images on hub.docker.com.

Creating preview images failed, continuing without it.: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed.

**Comment by eikek** [comment]
I'm afraid that jpeg2000 is not supported out of the box. There are licensing issues for using it in GPL projects. However, you could download the jar and place it manually into the `lib` folder where docspell is installed.

**Comment by frankhommers** [comment]
I'll try that and report back.

**Comment by frankhommers** [comment]
I have added it to the docspell-joex container, but it's still giving me errors.
I use OmniPage to do the initial scanning. I suspect that's where JPEG2000 is coming from.. Almost all my PDF's are like this :(

**Comment by frankhommers** [comment]
I did this, but it's not working. 

Here is the solution, but that's during build I guess.

https://stackoverflow.com/questions/57707735/how-to-fix-cannot-read-jpeg2000-image-java-advanced-imaging-jai-image-i-o-to

**Comment by frankhommers** [comment]
I can't get it to work. But I understand it's a licensing issue that can't be fixed.

**Comment by eikek** [comment]
> I did this, but it's not working.

Yes, I was too fast with my response, sorry! it is also necessary to make it available to the classpath which is currently specified in the manifest of the main jar. It's unfortunately not so easy to add after the build.
