### ISSUE TITLE
Allow new file upload without hitting Reset

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2323]
Unless there is a good reason why the user needs to reset the file upload form, it would be preferable IMnsHO that a new file could be submitted right away, reusing the same form:

![image](https://github.com/eikek/docspell/assets/195073/8f3b4e06-515a-4473-bce2-f94ad9ca45a1)

**Comment by eikek** [comment]
Yes, that makes sense. Not sure any more what the thoughts were back then.
