### ISSUE TITLE
Uploading a duplicates file with `skipDuplicates=True` yields `success==True`

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2341]
Possibly related to #2327, and arguably: when I upload a duplicate file and I ask Docspell to skip duplicates, then the API should not return `{'success': True, 'message': 'Files submitted.'}`

**Comment by eikek** [comment]
The upload only stores the file and submits a job into the queue. That's what the message says :-) Only when eventually the job is picked up, the duplicates are checked. So there can't be a better response, I think.

**Comment by madduck** [comment]
Fair, I get it, and it makes sense. However, I think it's a problem for me to upload a file, be told that it was successful, and then not receive any other information. At the very least, I should be given a job ID and an API endpoint so that I can check progress.

And then again, I think that duplicate checking is actually deterministically fast enough to be done synchronously… but that might be a can of worms.

**Comment by eikek** [comment]
I totally agree that the job api needs to be addressed (it just hasn't been done yet). Checking for duplicates is quite expensive and best left to the joex component.

**Comment by eikek** [comment]
I close this issue. I think the way to go for now is to improve the job api first. There is already this issue: #596
