### ISSUE TITLE
Setting item date from addons

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2345]
The "pure" addon JSON interface is great, but doesn't allow me to set the item date. Unless there's a reason for that, it would be good to extend the functionality to allow the date to be set.

**Comment by eikek** [comment]
There is no reason other than it's not done yet :-). Yes, must be definitely extended

**Comment by v6ak** [comment]
Not yet tested: https://github.com/v6ak/docspell/tree/feature/2345-setting-item-date-from-addons

**Comment by eikek** [comment]
Nice, looks good! 👍🏼

**Comment by v6ak** [comment]
Tested, it works. 

I assume that docspell.common.Timestamp is the way to go. It requires Long and doesn't accept Strings, but it might be fine for an API.

**Comment by eikek** [comment]
Done in #2362
