### ISSUE TITLE
[ui] Bulk-editing items

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2371]
Hey, this is just putting a need out here. I realise this is pretty far away from what the UI can currently do. I just scanned roughly 100 documents, and 30 or so of those were misattributed to the wrong organisation, when they all actually are about the same organisation Foo. I wish I could just select them all in the UI, and bulk-assign the organisation, rather than having to go into each individual item, and/or assume machine learning will eventually do it.

**Comment by eikek** [comment]
Good news then, i hope: https://docspell.org/docs/webapp/multiedit/ 😄

**Comment by madduck** [comment]
I don't understand why I missed that. Thank you!
