### ISSUE TITLE
Jobs get stuck processing emails with special attachments

### ISSUE THREAD

**Issue by madduck** [eikek/docspell#2376]
I found that some jobs just get stuck in the processing state forever, and it seems this is related to emails with "weird" attachments. I managed to recreate a test case with a `application/applefile` attachment, which is named `d0101c66_mySQL40.sql`. The conversion pipeline actually seems to ignore the MIME type and just assumed the file is `text/x-sql` (which it is not), but I am not sure this is the source of the problem — I've seen it happen with "Big5"-encoded vCards as well.

Please find the test email below. If you upload this into Docspell, the processing log should look like this:

```
Sa.. 11. November 2023, 20:49: ============ Start processing test.eml ============
Sa.. 11. November 2023, 20:49: Checking for duplicate files
Sa.. 11. November 2023, 20:49: Creating new item with 1 attachment(s)
Sa.. 11. November 2023, 20:49: Creating item finished in 15 ms
Sa.. 11. November 2023, 20:49: Reading e-mail test.eml
Sa.. 11. November 2023, 20:49: Filtering email attachments with '*'
Sa.. 11. November 2023, 20:49: Converting e-mail file...
Sa.. 11. November 2023, 20:49: E-mail has 2 attachments and text-and-html-body
Sa.. 11. November 2023, 20:49: Import attachments only: false
Sa.. 11. November 2023, 20:49: Extracted mail.html. Storing as attachment.
Sa.. 11. November 2023, 20:49: Extracted d0101c66_mySQL40.sql. Storing as attachment.
Sa.. 11. November 2023, 20:49: Use mail date for item date: Some(2023-11-11T20:45:53Z)
Sa.. 11. November 2023, 20:49: Extracted attachment Some(test.eml). Remove it from the item.
Sa.. 11. November 2023, 20:49: Not an archive: text/html; charset="UTF-8"
Sa.. 11. November 2023, 20:49: Not an archive: text/x-sql; charset="windows-1254"
Sa.. 11. November 2023, 20:49: Converting file Some(mail.html) (text/html; charset="UTF-8") into a PDF
Sa.. 11. November 2023, 20:49: Running external command: weasyprint --optimize-size all --encoding UTF-8 - /tmp/docspell-weasyprint/docspell-weasyprint11486183796891668857/out.pdf
Sa.. 11. November 2023, 20:49: Command `weasyprint --optimize-size all --encoding UTF-8 - /tmp/docspell-weasyprint/docspell-weasyprint11486183796891668857/out.pdf` finished: 0
Sa.. 11. November 2023, 20:49: weasyprint stdout:
Sa.. 11. November 2023, 20:49: weasyprint stderr: WARNING: Ignored `font-size: calc(100% * 0.7)` at 1:14, invalid value. WARNING: Ignored `font-size: calc(100% * 0.7)` at 1:1, invalid value. WARNING: Ignored `width: calc(0.97 * 15.5em)` at 1:1, invalid value. WARNING: Ignored `font-size: calc(100% * 0.7)` at 1:14, invalid value. WARNING: Ignored `font-size: calc(100% * 0.7)` at 1:29, invalid value.
Sa.. 11. November 2023, 20:49: Conversion to pdf successful. Saving file.
Sa.. 11. November 2023, 20:49: Closing process: `weasyprint --optimize-size all --encoding UTF-8 - /tmp/docspell-weasyprint/docspell-weasyprint11486183796891668857/out.pdf`
Sa.. 11. November 2023, 20:49: Converting file Some(d0101c66_mySQL40.sql) (text/x-sql; charset="windows-1254") into a PDF
```

And that's it, Joex is stuck there forever. If I cancel the job, the item is created with the mail attachment, but no preview, and obviously the weird attachment also isn't there. Addons are not run.

Here is the email:

```
Date: Sat, 11 Nov 2023 21:54:36 +0100
From: invalid@example.org
To: invalid@example.org
Subject: Docspell test email
Message-ID: <20231111205436.oefruzlox57xssbt@example.org>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="holmsj2d6wm2cnnr"
Content-Disposition: inline


--holmsj2d6wm2cnnr
Content-Type: text/plain; charset=utf-8
Content-Disposition: inline

Check attachment

--holmsj2d6wm2cnnr
Content-Type: application/applefile
Content-Disposition: attachment; filename="d0101c66_mySQL40.sql"
Content-Transfer-Encoding: base64

ABRkMDEwMWM2Nl9teVNRTDQwLnNxbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbUJJTgAA
AAAAAAAAAAAAAAAAAACCgf+/AAA=

--holmsj2d6wm2cnnr--
```

**Comment by eikek** [comment]
I think we hit a bug I copied over a few years ago...
https://github.com/http4s/http4s/blob/2d2e26171bfc2881ea4b00c42c463d801c777db0/core/src/main/scala/org/http4s/util/package.scala#L28

The problem is the file that gets falsly detected as a text file. This can happen and I don't think there is a lot we can do in general about it. But then it tries to decode the bytes using a windows-1254 charset which triggers the bug. Using utf8 returns fine.

**Comment by madduck** [comment]
Unfortunately, #2378 causes the job to get stuck here, if I try to upload the above test email using the webapp. Here is the corresponding trace log:

```
Nov 12 13:56:51 docspell docspell-joex[422961]: 2023.11.12 13:56:51 [io-comp...] TRACE docspell.store.impl.DoobieLogging.run:24 - SQL: INSERT INTO joblog (id, jid, level, created, message) VALUES (?,?,?,?,? )  (List(Ident(6wfFfgPy9Db-UvxXvXx3EkW-facK82YZdsS-2fYiupKbkQp), Ident(2w8Cim4WXci-LavAaVGqrQF-BMAANwXakef-L2BeqWMTFq2), Info, Timestamp(2023-11-12T12:56:51.394035757Z), Converting file Some(d0101c66_mySQL40.sql) (text/x-sql; charset="windows-1254") into a PDF)) executed in 132199 nanoseconds
Nov 12 13:56:51 docspell docspell-joex[422961]: 2023.11.12 13:56:51 [io-comp...] TRACE docspell.store.impl.DoobieLogging.run:24 - SQL: SELECT job.retries FROM job  WHERE job.jid = ?   (List(Ident(2w8Cim4WXci-LavAaVGqrQF-BMAANwXakef-L2BeqWMTFq2))) executed in 124734 nanoseconds
Nov 12 13:56:51 docspell docspell-joex[422961]: 2023.11.12 13:56:51 [io-comp...] ERROR docspell.scheduler.impl.SchedulerImpl.wrapTask:304 - Job 2w8Cim4WX.../1/process-item/High execution failed. Retrying later.
Nov 12 13:56:51 docspell docspell-joex[422961]: java.nio.charset.UnmappableCharacterException: Input length = 1
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.text$.$anonfun$decodeCWithGenericCharset$1(text.scala:263)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$$anon$1.cont(Pull.scala:149)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$.fs2$Pull$$bindBindAux(Pull.scala:748)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$BindBind.cont(Pull.scala:735)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$ContP.apply(Pull.scala:683)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$ContP.apply$(Pull.scala:683)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$Bind.apply(Pull.scala:691)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$Bind.apply(Pull.scala:691)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$UnconsRunR$1.$anonfun$out$2(Pull.scala:1020)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$.$anonfun$compile$2(Pull.scala:953)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at get @ fs2.internal.Scope.openScope(Scope.scala:275)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1215)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]: 2023.11.12 13:56:51 [io-comp...] DEBUG docspell.scheduler.impl.SchedulerImpl.onFinish:224 - Job 2w8Cim4WX.../1/process-item/High done Stuck. Releasing resources.
Nov 12 13:56:51 docspell docspell-joex[422961]: 2023.11.12 13:56:51 [io-comp...] DEBUG docspell.scheduler.impl.SchedulerImpl.onFinish:226 - Permit released (8 free)
Nov 12 13:56:51 docspell docspell-joex[422961]: 2023.11.12 13:56:51 [io-comp...] ERROR docspell.scheduler.impl.LogSink.logInternal:49 - >>> 2023-11-12T12:56:51.403623590Z Error 2w8Cim4WX.../1/process-item/High: Job 2w8Cim4WX.../1/process-item/High execution failed. Retrying later.
Nov 12 13:56:51 docspell docspell-joex[422961]: java.nio.charset.UnmappableCharacterException: Input length = 1
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.text$.$anonfun$decodeCWithGenericCharset$1(text.scala:263)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$$anon$1.cont(Pull.scala:149)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$.fs2$Pull$$bindBindAux(Pull.scala:748)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$BindBind.cont(Pull.scala:735)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$ContP.apply(Pull.scala:683)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$ContP.apply$(Pull.scala:683)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$Bind.apply(Pull.scala:691)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$Bind.apply(Pull.scala:691)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$UnconsRunR$1.$anonfun$out$2(Pull.scala:1020)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at fs2.Pull$.$anonfun$compile$2(Pull.scala:953)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at get @ fs2.internal.Scope.openScope(Scope.scala:275)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1215)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Nov 12 13:56:51 docspell docspell-joex[422961]:         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
```

**Comment by eikek** [comment]
Yes, but this is fine. The job fails, because of a bad input. It doesn't end up in an endless loop, but fails gracefully. It will rety a few times and then stop. It works as intended for bad input.

Now, if we want to support that file, this is another story.

**Comment by madduck** [comment]
No need to support that file, but why not instead include an attachment that just says that the part could not be converted? Rather than blocking the entire upload with no recourse? If I receive an email from someone else like this, how would I even proceed? It is not like I could modify the file and retry the upload, and there seems to be also no way to fix the stuck job...

**Comment by eikek** [comment]
Yes true, this can be handled better, like just skipping this attachment. Currently there are retries until some configured value with exponential backoff. It then fails and simply creates the item with stuff that could be done until that error.

**Comment by madduck** [comment]
That is why the preview is not generated, nor addons called...

I recommend to do like mutt, i.e. include an attachment that says there was an attachment named xyz of type xyz and it could not be converted.

**Comment by eikek** [comment]
The preview won't be done for that attachment anyways. If we generate a dummy file, then addons and further processing/analysing code could get confused perhaps.

**Comment by madduck** [comment]
How would addons/further processing even find out? I don't know how the processing pipeline works exactly (yet), but I imagine that joex tries a conversion, and if it fails, it just moves on.

Here is what happens right now, and it's not good:

1. The job fails, gets retried *n* times, and eventually finishes in the `failed` state;
2. An item is generated with all attachments;
3. No previews are generated;
4. OCR has not run;
5. Addons have not been invoked.

Here is what should happen instead:

1. Not being able to process an attachment is not an error, it should be anticipated; not all email attachments can be converted to PDF, and we shouldn't even try;
2. When an attachment is found for which a converter doesn't exist, just store the attachment as-is. In the UI, the user should then be alerted to the fact that no converter/viewer exists for the attachment, which can thus only be downloaded;
3. Obviously, previews and OCR cannot be run on such attachments, and that is fine;
4. Addons, however, should be given access to these attachments.

**Comment by eikek** [comment]
This is not quite true. If an attachment is not supported it is currently skipped. This case here is special, because it is the case an internal error occurs when processing an attachment. It is incorrectly classified as supported but later the code blows up, because it is a bad input. If an attachment is not supported your points are already implemented. 

I don't like the idea to create a dummy attachment, because that has to be marked and taken care everytime one handles attachments of an item. That is going to be very annoying. But anyways, I think this is a different issue.

**Comment by madduck** [comment]
I agree with you about the dummy attachment. I think an unsupported attachment just shouldn't get processed, and it's up to the UI to handle that.

With internal error, are you referencing the infinite loop? Because that should now be fixed, right? The behaviour I described two messages up happens with the current `master` code, i.e. with this PR merged.

**Comment by eikek** [comment]
The infinite loop is fixed with that issue. The case with that specific broken file is that it is incorrectly classified as a supported file (some text file), and therefore joex goes into processing it and blows up at some point with an exception (it can't decode the bytes). If it were correctly classified as not supported, then it wouldn't go into processing and things would work pretty much as you described. This case shouldn't happen often, but can occur of course, because it comes down do educated guessing after all.

**Comment by madduck** [comment]
Hey, thanks for your time engaging with me over this. It's a serious issue for me because a trial run of our data stock exposed nearly a thousand problematic cases, far too many for me to be able to manually do anything about it.

Right now, the software seems to use the heuristic ("educated guessing") that a file matching the `*.sql` glob must therefore be `text/x-sql`, when in fact that is nowhere standardised, and there are many other cases, where it just isn't that easy, anyway. There is simply no other reliable way to determine the MIME type of a file, other than letting an interpreter try processing it. I think `joex` needs to be taught to anticipate failure of the interpreter, and be shown what to do in this case.

We still need the educated guess to pick an interpreter or two, but when the interpreter(s) fail to process a file, that should yield the raw attachment to be stored unprocessed, and the rest of the processing pipeline to continue. Do you agree with that?

**Comment by eikek** [comment]
> Right now, the software seems to use the heuristic ("educated guessing") that a file matching the `*.sql` glob must therefore be `text/x-sql`

Oh no, it's not that simple! It uses multiple things, including the magic header strategy. For some reason, it fails for this file. It works for the majority, but will always be a heuristic. As I said, one option is to skip an attachment on such a failure. The "problem" with this is, that retries are either void or errors need to be classified whether they are retriable or not. 

Currently, after the retries the item will be created with the attachment but without any results from processing. You get all data and it's kind of clear that something didn't work.

**Comment by madduck** [comment]
What speaks against processing everything else, just skipping this attachment?

Yes, it's clear that something didn't work. So what now. The mail may have come in via the SMTP gateway, or it got slurped up from IMAP. And as in my case, there are hundreds of those already, and probably dozens more to come… especially Apple Mail seems to be quite keen on sending emails that Docspell cannot process.

PS: What magic header strategy are you using? The file in question above is a binary file, and on a modern Linux system, `file` (correctly) identifies it as a "MacBinary":

```
lotus:~/.tmp% file d0101c66_mySQL40.sql
d0101c66_mySQL40.sql: MacBinary III INVALID date "d0101c66_mySQL40.sql"
lotus:~/.tmp% file -i d0101c66_mySQL40.sql
d0101c66_mySQL40.sql: application/octet-stream; charset=binary
```

So maybe the bug is in the magic, that could be.

Apart from that, I still think that the error-handling strategy could be improved. Would you be okay if we started working on that?

**Comment by eikek** [comment]
> What speaks against processing everything else, just skipping this attachment?

I don't understand - just this specific attachment? How to determine this?



> What magic header strategy are you using?

A library is used for this, called [tika](https://tika.apache.org/). For this file, the library doesn't do a good job and could probably be improved there. My point is, that this can happen any time for any weird file. On my linux system `file` identifies it as a binary (didn't recognize a valid text encoding) as well. Firefoxs File-Open dialog, for example, says it's "SQL-Code", probably just looks at the file extension - don't know. 

Of course, things can be improved. Not really sure, what you mean. I proposed an option above. But it's not that this scenario is about an "unsupported file" - for the app it is a supported file but errors out anyways. 

How exactly do you want to improve error handling?

**Comment by madduck** [comment]
Ah, good to know you're using tika.

Let's take things one step at a time. I am confused by this statement:

> I don't understand - just this specific attachment? How to determine this?

Maybe this is the source of confusion. I am thinking that Docspell disassembles the MIME message like an archive, then processes each attachment in turn. I am thinking this is the case because I can (a) limit attachments by glob in the upload dialog/metadata, (b) there's an option to only handle attachments for mails, and (c), the log mentions the filename, so it's unlikely you are just passing the entire email to tika.

If I am right, and Docspell converts/interprets each MIME part in turn, and if I am allowed to write it down as imperative pseudo-code, then I imagine it like this:

```
attachments = []
for part in message.parts {
  proc = get_processor(identify(part))
  errcnt = 0
  while true {
    try {
      processed_part = proc(part)
      attachments += processed_part
      break
    } except Error {:
      if errcnt > 3:
        # this is the key, it seems to me that right now, joex
        # just aborts all further processing, while I suggest
        # it should store the raw attachment and continue processing
        # the remaining MIME parts, before contining with the rest of
        # the processing pipeline.
        attachments += raw(part)
        break
      }
    }
  }
  for attachment in attachments {
    if not is_raw(attachment):
      further_process(attachment)
  }
}
```

**Comment by madduck** [comment]
@eikek how can we proceed on this issue? Can you please reopen it, or should I file a new one with the findings thus far summarised?

**Comment by madduck** [comment]
For the purpose of moving forward, I would like to offer the following summary, possibly with a view of creating new issues.

I think there are two problems when mails with attachments (and presumably Zip files) are archived:

1. Certain attachments are mis-identified by the heuristics in Docspell. For instance, the file `d0101c66_mySQL40.sql` in the original email is identified to be of type `text/x-sql`, presumably mostly based on the filename extension, when in fact the file is a binary of type "MacBinary III INVALID date" (possibly corrupt), as identified by `libmagic1` version 5.45. This is unfortunate, but not the end of the world, i.e. a **minor issue**.

2. The real issue — the one blocking us right now — is that such attachments will cause the processing pipeline to exit prematurely. Upon encounter of such an attachment, Docspell will try to interpret it as `text/x-sql`, but that fails. As a consequence, Docspell skips all further steps: remaining attachments, post-processing (OCR and preview images), and also doesn't call addons or hooks. This is a **major issue**.

In my opinion, there shouldn't be any mis-identification, but it also won't be possible to ever rule that out. If such a mis-identification happens, Docspell needs to handle the situation more gracefully. For instance:

1. If processing of an attachment yields an error, the system should dutifully retry 1–2 times with a bit of delay in between. This could be configurable with a simple integer;
2. If all retries also fail, then the attachment should simply be included in the item in its raw format;
3. OCR and preview generation presumably won't be able to handle the raw data, so they should just skip the file without error;
4. Addons and hooks similarly need to handle this gracefully themselves;
5. The final item will include a raw attachment, which can be downloaded, but likely won't be viewable through the UI.
6. Reprocessing the item would give the raw attachment another chance.

Thoughts?

**Comment by eikek** [comment]
As said many times above, this is a different issue - please use a new one, this one is done and another topic.
