### ISSUE TITLE
How i set up OpenID with docspell

### ISSUE THREAD

**Issue by danielbaessler** [eikek/docspell#2381]
I want to set up OpenID SSO with env variables on docker but i dident find them in the Docs

Thank you for Helping

**Comment by eikek** [comment]
Here are the docs about it:
https://docspell.org/docs/configure/authentication/#openid-connect-oauth2

Just convert the config file to env variables as shown here:
https://docspell.org/docs/configure/defaults/#environment-variables

**Comment by schacka** [comment]
I have the same problem. How can Docspell.Server.Openid = {[....]} be converted to env variables? It's not covered by [https://docspell.org/docs/configure/defaults/#environment-variables](https://docspell.org/docs/configure/defaults/#environment-variables)

Same with DOCSPELL_SERVER_LOGGING_LEVELS_ORG_HTTP4 or DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ALLOWED__IPS_IPS

Thank you

**Comment by eikek** [comment]
Not all is covered, but the pattern hopefully is. The limitation with env variables is currently, that arrays cannot be defined. Every setting with arrays requires a config file.

**Comment by schacka** [comment]
Thank you for the clarification. It would have been nice if it also worked with the arrays. I'll just stick with the config file.

**Comment by eikek** [comment]
Yeah, sorry for being so brief at the beginning (tight on time as always). The docs should be more obvious here.

**Comment by madduck** [comment]
> Thank you for the clarification. It would have been nice if it also worked with the arrays. I'll just stick with the config file.

It's trivial to use a config file with Docker as well. Could you just do that?

**Comment by schacka** [comment]
> > Thank you for the clarification. It would have been nice if it also worked with the arrays. I'll just stick with the config file.
> 
> It's trivial to use a config file with Docker as well. Could you just do that?

I'm actually doing this :)
