### ISSUE TITLE
Change AWS Region for Minio backend

### ISSUE THREAD

**Issue by da-avidid** [eikek/docspell#2386]
Deployment Type: Docker Compose
Images: docspell/restserver:v0.40.0, docspell/joex:v0.40.0, docspell/dsc:v0.10.0, postgres:16.0, solr:9

Issue:
I am getting the following error when I try to use the Minio backend to connect to an S3 bucket.

```
docspell-joex        | java.util.concurrent.CompletionException: error occurred
docspell-joex        | ErrorResponse(code = AuthorizationHeaderMalformed, message = The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2', bucketName = null, objectName = null, resource = null, requestId = <REDACTED>, hostId = <REDACTED>)
```

I have been able to successfully perform actions from the CLI with the following ENV VARS set
```
AWS_ACCESS_KEY_ID=<REDACTED>
AWS_SECRET_ACCESS_KEY=<REDACTED>
AWS_DEFAULT_REGION=us-west-2
```

How can I set the AWS_DEFAULT_REGION using the for the Minio Backend?

I have Tried:

1. Injecting the ENV VAR directly into the container
2. Looking for clues in the Binny Source here https://github.com/eikek/binny/tree/master/modules/minio/src/main/scala/binny/minio
3. Reading through the Default Config Docs here https://docspell.org/docs/configure/defaults/
4. Searching the github issues

Any help would be appreciated : ^ )

**Comment by eikek** [comment]
Oh that is really bad. Thanks for reporting! Binny simply misses this piece of configuration :( Currently it can't be set, but it's easy to change and I'll do it shortly.

**Comment by rehanone** [comment]
@da-avidid , did to try the following setting?

```sh
DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENDPOINT="https://s3.us-west-2.amazonaws.com"
```

I guess that should help.

**Comment by da-avidid** [comment]
@rehanone , I had the second ENV VAR set but not the first. I added the first and I get the same issue.

However, I see that @eikek added a region setting to Binny (that was fast!). I also see that there is a "nightly" tag for the containers on Docker hub.

My new questions are:
1. Do those "nightly" tags have the updated Binny in them?
2. How exactly would I form the new ENV VAR? DOCSPELL_JOEX_FILES_STORES_MINIO_REGION?

**Comment by eikek** [comment]
Yes I added the setting to the binny library. Only needs to be integrated here. The underlying s3 client does some magic regarding region based on the url/host that is used. @rehanone tip could really have helped. The exact way to define it via env variable is not decided - but your guess looks pretty close. The binny library is already included in the nightly build, but docspell doesn't make use of this new feature yet. Should be easy to change and I expect it to happen in the next days.

**Comment by eikek** [comment]
@da-avidid you can try it out with the current nightly version. The env variable is that you described earlier.

**Comment by da-avidid** [comment]
@eikek Thank you very much. It is up and working now. I will list below the relevant ENV VARS I used in Docker, just in case anyone comes by looking for answers.

`
  restserver:
    image: docspell/restserver:nightly
    container_name: docspell-restserver
    environment:
      - DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE=minio
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_BUCKET=<BUCKET NAME>
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENABLED=true
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENDPOINT=https://s3.us-west-2.amazonaws.com
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ACCESS__KEY=<REDACTED>
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_SECRET__KEY=<REDACTED>
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_TYPE=s3
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_REGION=us-west-2

  joex:
    image: docspell/joex:nightly
    container_name: docspell-joex
    environment:
      - DOCSPELL_JOEX_FILES_DEFAULT__STORE=minio
      - DOCSPELL_JOEX_FILES_STORES_MINIO_BUCKET=<BUCKET NAME>
      - DOCSPELL_JOEX_FILES_STORES_MINIO_ENABLED=true
      - DOCSPELL_JOEX_FILES_STORES_MINIO_ENDPOINT=https://s3.us-west-2.amazonaws.com
      - DOCSPELL_JOEX_FILES_STORES_MINIO_SECRET__KEY=<REDACTED>
      - DOCSPELL_JOEX_FILES_STORES_MINIO_ACCESS__KEY=<REDACTED>
      - DOCSPELL_JOEX_FILES_STORES_MINIO_TYPE=s3
      - DOCSPELL_JOEX_FILES_STORES_MINIO_REGION=us-west-2
`

NOTES:
1. <BUCKET NAME> takes literally just the bucket name, no s3:// etc. "example-bucket-name-123"
2. Your REGION will vary but it will probably have to match the ENDPOINT. Consult the link below for different REGION/ENDPOINT examples.
3. Make sure your IAM user has the appropriate permissions. This may vary depending on your use case.

REGION/ENDPOINT Link: https://docs.aws.amazon.com/general/latest/gr/s3.html
