### ISSUE TITLE
Stack two Documents

### ISSUE THREAD

**Issue by mirisbowring** [eikek/docspell#2406]
Hi,

recently i discovered, that it would be cool to select multiple documents and "stack" them together.

Currently, it is possible to upload an additional Document into a Docspell Document.

In my case, I e.g. request a change to a contract and store that into docspell. Some Weeks / Months later, i get the confirmation that the change is valid. I scan this letter and upload it into docspell.
Now, I would like to be able to select those documents and press "Stack" or "Merge" to group them together.

Regards!

**Comment by eikek** [comment]
I think this is possible, if I understand correctly. https://docspell.org/docs/webapp/merge/ An alternative way could be to "link" both together - there are no docs for this yet, it would be the last icon in the list when you select multiple.

**Comment by mirisbowring** [comment]
Oh, i missed that point - Thank you! ❤️
