### ISSUE TITLE
H2 upgrade instructions for v.0.41.0 missing

### ISSUE THREAD

**Issue by mprasil** [eikek/docspell#2477]
The latest version 0.41.0 fails to start after upgrade with:

```
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported database file version or invalid file header in file "/db/docspell.db.mv.db" [90048-224]
```

I believe this is due to upgrade of H2? There were [instructions for upgrading the DB in the 0.39.0](https://github.com/eikek/docspell/blob/master/Changelog.md#h2), I believe similar instructions for 0.41.0 might be required?

**Comment by eikek** [comment]
Yes, well I thought this is h2 docs purpose 😏 But you're right, a few words won't hurt here. So I think it comes down to export + import. The script in `tools/h2-util.sh` can be used for this. I'll add a sentence to the release notes.

**Comment by eikek** [comment]
There are no additional things needed this time. It is only a bump of h2, but no schema changes or anything.

The script is not bundled, I just created it for convenience, but people can simply run a single java command on their dockers if they want. (it can be all found in the h2 docs) Java should be there, because h2 and docspell need it.

**Comment by mprasil** [comment]
That's fair. I think something like this would be enough as a pointer for people to do the migration and not have to fish the H2 versions from github:

```sh
# Database user
export H2_user=<username>
# Name of the DB file without the ".mv.db" extension
export DB_NAME=<file>

# Dump the DB
export H2_VERSION=2.1.214
h2-util.sh dump "${DB_NAME}" dump.sql

# Move the old DB to a directory in case we want to restore it later
mkdir old_db
mv ${DB_NAME}.* old_db/

# Restore dump into new DB
export H2_VERSION=2.2.224
h2-util.sh restore dump.sql  "${DB_NAME}"
```

(I have not tested this, just a suggestion)

**Comment by eikek** [comment]
I updated the release notes - closing this. Thank you for reporting and the neat script, I linked it in the release notes.

**Comment by marvin8** [comment]
The link to the H2 website in the release notes seems incorrect. Should it link to https://www.h2database.com  or is there a deep link that would be more appropriate?

**Comment by eikek** [comment]
Oh my... 🤦🏼 Thanks for pointing this out! I don't know a good deep link. I think people using h2 should really read a bit through their docs anyways. There is the `SCRIPT` and `RUNSCRIPT` commands if I recall correctly. But the script in `tools` runs these already.
