### ISSUE TITLE
Can't create an account

### ISSUE THREAD

**Issue by torwag** [eikek/docspell#250]
Installing docspell with the given dockerfile, I end up in the login-screen. Creating an account and pressing "ok", seems not to trigger anything. Browser does no further loading and the docker log remains silent about the sign-up procedure.

**Comment by eikek** [comment]
Thank you for reporting and sorry for the inconvenience. I have some questions:

- how did you get the docker file, using git? or downloading the zip?
- do you access it all from the local machine? IOW do you use `localhost:7880` in the address bar?
- did you change the config file?
- do you see any errors on startup?
- what version does it report at the bottom?

If the logs are silent then I suspect the request doesn't hit the server. One way find out more is to open "developer tools" of your browser (when using firefox, it's F12) and look at the network tab when clicking "submit". If you could somehow share what you see, that would be of great help, I think.

I just tried at my machine with a completely wiped docker environment and I couldn't reproduce it :/ That's why I can't give any specific advice.

Thank you!

**Comment by torwag** [comment]
Hi and thanks for the quick reply.
No need to be sorry. It should be an implicitness to contribute to an open source project by providing feedback and not expecting everything works out of the box.
 
1. I used the git repository and started the service with the provided dockerfile from my server.
2. I can access the server vial <domain>.local and I end up on the login page, thus I think it is safe to say I can reach the service.
    Calling the service, I can see quit some status messages in the docker log, thus it is save to say... I have a connection.
    Choosing sign-in and fill in the form, does not trigger any reaction.
3. What do you mean by config? The docker-compose-file? I did not touch the docspell.conf
4. There are many messages on the docker log, but with a quick view I couldn't spot any major error a grep for error over the log shows me this 
```docspell-solr | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
docspell-solr | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
docspell-solr | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
```
5. Version infos
```docspell-joex | [main] INFO  d.joex.Main - 
docspell-joex | ***>  ______                          _ _
docspell-joex | ***>  |  _  \                        | | |
docspell-joex | ***>  | | | |___   ___ ___ _ __   ___| | |
docspell-joex | ***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
docspell-joex | ***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
docspell-joex | ***>  |___/ \___/ \___|___/ .__/ \___|_|_|
docspell-joex | ***>                      | |
docspell-joex | ***>                      |_| v0.11.0 (#cc041680)
docspell-joex | ***>  << JOEX >>
docspell-joex | ***>  Id:       joex1
docspell-joex | ***>  Base-Url: http://joex:7878
docspell-joex | ***>  Database: jdbc:postgresql://db:5432/dbname
docspell-joex | ***>  Fts:      http://solr:8983/solr/docspell
docspell-joex | ***>  Config:   /opt/docspell.conf
docspell-joex | ***>   
```
The dev console of chromium.... gives me something very interesting, should have started with this:
```
docspell-app.js:4358 POST http://localhost:7880/api/v1/open/signup/register net::ERR_CONNECTION_REFUSED
```
Thus, it seems to look at localhost instead of <domain>.local, which is obviously wrong.
I searched further and noticed that there is localhost setting in the docspell.conf file. Changing this to <domain>.local and it worked. 

Not sure this is the right way to do it.

**Comment by eikek** [comment]
Thank you so much for the detailed reply!

So you solved it already :) Yes, this exactly is currently the intended way. It is required to configure the externally used URL in the configuration file (for point 3, I meant docspell.conf), so docspell can generate links and set restrictions for the authentication cookie. But issues like these make me think to maybe still use the request header for absolute links. But while convenient this has other drawbacks….  Maybe a more prominent place in the docs would also be an improvement? What do you think would have helped you in this situation?

**Comment by poblabs** [comment]
I'm having the same issue. I followed the instructions to install via docker-compose and that went fine. When I go to the signup page it won't let me sign up. 

I am installing this on my docker host which is not localhost. Thoughts on how I can get around that?

![image](https://user-images.githubusercontent.com/3484775/92668977-46a37380-f2de-11ea-85a6-dedb52118602.png)

**Comment by eikek** [comment]
Yes, this is also this issue. For now, you need to change `docspell.conf` – look for the setting `base-url = "http://localhost:7880"` and change the URL to the one you are using to access it (the external URL).

**Comment by poblabs** [comment]
Thanks, setting that before `docker-compose up` seems to have worked. Thanks!

**Comment by eikek** [comment]
You're welcome! I'm going to think about how to improve this situation.

**Comment by eikek** [comment]
I'm now about to make these changes when `base-url` is left unchanged:

- The domain is taken from the request doing the login to configure the cookie. That means that you need to stick to the url used when logging in. When using a reverse proxy, you must set the `X-Forwarded-For` header for internal requests.
- The webapp is doing requests against the host currently in the address bar. So the value of `base-url` doesn't matter at all. 

However, if the user changes `base-url`, it is used as before; the behavior is not changed then. I hope this makes it less confusing when trying it out.  I still recommend to set `base-url` to your public/external URL when using docspell, as it is  safer. Also some server-side functionality (like sending notification mails that contain absolute urls) still require this setting.
