### ISSUE TITLE
[Query Language] All documents that don't have a specific custom field

### ISSUE THREAD

**Issue by TheAnachronism** [eikek/docspell#2518]
Hey there,

How can I check whether documents have a specific custom field set or not?
With [Exist](https://docspell.org/docs/query/#exist) I can check if they have a certain field, but I haven't figured out yet, how to apply this to custom fields.
The syntax described [here](https://docspell.org/docs/query/#custom-fields) doesn't seem to work:
`exist:f:SomeField`

Thanks

**Comment by eikek** [comment]
You could check for any value, perhaps. Like `f:somefield:*` ?

**Comment by TheAnachronism** [comment]
But that only shows documents that actually have that field, but nothing set for it. If I never assign that field to a document, it won't show up in the search result.

**Comment by eikek** [comment]
Ok, I might misunderstood. The query `f:somefield:*` returns all documents that have the field `somefield` set (to some value). Then negating this like `!f:somefield:*` would return documents that don't have this field.
