### ISSUE TITLE
Fulltext search broken after update (from v0.40.0 to v0.41.0?): SolrException: undefined field content_sk

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#2538]
After updating from v0.40.0 to v0.41.0 the fulltext search is broken (maybe already before?).
A fulltext search has no result, it just shows all documents as before.
I get following entry in the Solr log :
`ERROR x:docspell RequestHandlerBase org.apache.solr.common.SolrException: undefined field content_sk`
In the terminal following command has not the expected output (content_sk ist missing):
```
curl http://192.168.15.102:8983/solr/docspell/schema/fields | grep content_
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4577  100  4577    0     0   337k      0 --:--:-- --:--:-- --:--:--  343k
      "name":"content_cz",
      "name":"content_da",
      "name":"content_de",
      "name":"content_en",
      "name":"content_es",
      "name":"content_et",
      "name":"content_fi",
      "name":"content_fr",
      "name":"content_he",
      "name":"content_hu",
      "name":"content_it",
      "name":"content_ja",
      "name":"content_lt",
      "name":"content_lv",
      "name":"content_nl",
      "name":"content_no",
      "name":"content_pl",
      "name":"content_pt",
      "name":"content_ro",
      "name":"content_ru",
      "name":"content_sv",
      "name":"content_uk",
```

I already useed the admin endpoint to initiate a re-index, but it didn't solve the problem.
 
I just realized that also "content_kh" is missing and I have following log entry in the solr log:
```
2024-03-09 20:14:02.263 ERROR (qtp1863953433-60) [   x:docspell] o.a.s.h.RequestHandlerBase org.apache.solr.api.ApiBag$ExceptionWithErrObject: error processing commands, errors: [{add-field={name=content_kh, type=text_kh, stored=true, indexed=true, multiValued=false}, errorMessages=[Field 'content_kh': Field type 'text_kh' not found.
]}],  => org.apache.solr.api.ApiBag$ExceptionWithErrObject: error processing commands, errors: [{add-field={name=content_kh, type=text_kh, stored=true, indexed=true, multiValued=false}, errorMessages=[Field 'content_kh': Field type 'text_kh' not found.
]}], 
org.apache.solr.api.ApiBag$ExceptionWithErrObject: error processing commands, errors: [{add-field={name=content_kh, type=text_kh, stored=true, indexed=true, multiValued=false}, errorMessages=[Field 'content_kh': Field type 'text_kh' not found.
]}],
```
and
```
2024-03-09 20:14:02.263 INFO  (qtp1863953433-60) [   x:docspell] o.a.s.c.S.Request [docspell]  webapp=/solr path=/schema params={commitWithin=1000} status=400 QTime=1
```
This is the JOEX log:
```
2024.03.09 21:14:02:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-09T20:14:02.202161786Z Info ARgyWc6jt.../docspell-system/full-text-index/Low: Running full-text-index migrations now (jobId: "ARgyWc6jtvS-n6XA1TDgss2-fmRDBoP2sY5-HZxcKCHhR1M", task: "full-text-index", group: "docspell-system", jobInfo: "ARgyWc6jt.../docspell-system/full-text-index/Low")
2024.03.09 21:14:02:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-09T20:14:02.235437795Z Info ARgyWc6jt.../docspell-system/full-text-index/Low: Apply 32/Add new field type for khmer content (jobId: "ARgyWc6jtvS-n6XA1TDgss2-fmRDBoP2sY5-HZxcKCHhR1M", task: "full-text-index", group: "docspell-system", jobInfo: "ARgyWc6jt.../docspell-system/full-text-index/Low")
2024.03.09 21:14:02:0000 [io-comp...] [WARN ] docspell.ftssolr.SolrSetup - Adding new field type 'AddFieldType(text_kh,solr.TextField,Analyzer(Tokenizer(solr.ICUTokenizerFactory,Map()),List()))' failed: unexpected HTTP status: 400 Bad Request for request POST http://192.168.15.102:8983/solr/docspell/schema?commitWithin=1000
```
I can reach ´http://192.168.15.102:8983/solr/docspell/schema?commitWithin=1000´
I also can reach the solr admin page `http://192.168.15.102:8983/solr/#/`

I'm running docspell as docker on Unraid
 - docker Solr from bitnami (8.11.3)
 - docker postgres  (13.3)

At the moment I don't know what I could do to repair the fulltext search....

**Comment by eikek** [comment]
Hi @vakilando thanks for all these details! I think the problem could be on an outdated docker compose file. There was an addition of khmer language and with it, solr startup was changed to include an additional module. It somehow slipped through my attention and so I didn't document it on the release notes :/ 

If you look at the current compose file [here](https://github.com/eikek/docspell/blob/4167b64e31d05b80bcc32825fa0abe32239dcc21/docker/docker-compose/docker-compose.yml#L131), there is now `-Dsolr.modules=analysis-extras`. If that couldbe the cause in your case, you can try re-creating the index after starting solr with that option. 🤞🏼

**Comment by vakilando** [comment]
Thank you very much, I'll look at the current compose file........because, yes, mine could be outdated...

Meanwile I reinstalled Solr and now I have another error while the first error `undefined field content_sk` is gone.
```
ERROR x:docspell RequestHandlerBase org.apache.solr.common.SolrException: undefined field collectiveId
ERROR x:docspell RequestHandlerBase org.apache.solr.common.SolrException: undefined field content
```
I'll look at my docker configs in unraid (compose file)
I just tried to start solr with `-Dsolr.modules=analysis-extras` but I don't know where to put this option/command. I have to dig a bit deeper....

**Comment by eikek** [comment]
Yeah it's a bit confusing. Solr has a few words here: https://solr.apache.org/guide/solr/latest/configuration-guide/solr-modules.html it depends probably on the setup you use. You should be able to add it to the startup commands (like it's done in teh compose file here), or add it to some config file.

**Comment by vakilando** [comment]
Ok, got Solr startet with the env-var: `-e SOLR_OPTS="$SOLR_OPTS -Dsolr.modules=analysis-extras"`

This error persists:
```
ERROR x:docspell RequestHandlerBase org.apache.solr.common.SolrException: undefined field collectiveId
ERROR x:docspell RequestHandlerBase org.apache.solr.common.SolrException: undefined field content
```
Joex log:
```
2024.03.09 23:50:01:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 POST /internal/pubsub
2024.03.09 23:50:01:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 200 OK
2024.03.09 23:50:01:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-09T22:50:01.553808204Z Info 6GzTPknC1.../1/full-text-reindex/Low: Running full-text re-index now (jobId: "6GzTPknC1NC-4TBBNjTbnB5-LTgrPRXGGaT-uEExNsDk2qz", task: "full-text-reindex", group: "1", jobInfo: "6GzTPknC1.../1/full-text-reindex/Low")
2024.03.09 23:50:01:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-09T22:50:01.555287126Z Info 6GzTPknC1.../1/full-text-reindex/Low: Clearing index data (jobId: "6GzTPknC1NC-4TBBNjTbnB5-LTgrPRXGGaT-uEExNsDk2qz", task: "full-text-reindex", group: "1", jobInfo: "6GzTPknC1.../1/full-text-reindex/Low")
2024.03.09 23:50:01:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-09T22:50:01.555726139Z Info 6GzTPknC1.../1/full-text-reindex/Low: Deleting full-text index for collective 1 (jobId: "6GzTPknC1NC-4TBBNjTbnB5-LTgrPRXGGaT-uEExNsDk2qz", task: "full-text-reindex", group: "1", jobInfo: "6GzTPknC1.../1/full-text-reindex/Low")
2024.03.09 23:50:01:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-09T22:50:01.577155509Z Info 6GzTPknC1.../1/full-text-reindex/Low: Clearing data failed. Continue re-indexing. (jobId: "6GzTPknC1NC-4TBBNjTbnB5-LTgrPRXGGaT-uEExNsDk2qz", task: "full-text-reindex", group: "1", jobInfo: "6GzTPknC1.../1/full-text-reindex/Low")
2024.03.09 23:50:01:0000 [io-comp...] [ERROR] docspell.scheduler.impl.SchedulerImpl.wrapTask:304 - Job 6GzTPknC1.../1/full-text-reindex/Low execution failed. Retrying later.
org.http4s.client.UnexpectedStatus: unexpected HTTP status: 400 Bad Request for request POST http://192.168.15.102:8983/solr/docspell/update?overwrite=true&wt=json&commit=true

2024.03.09 23:50:01:0000 [io-comp...] [ERROR] docspell.scheduler.impl.LogSink.logInternal:49 - >>> 2024-03-09T22:50:01.579179212Z Error 6GzTPknC1.../1/full-text-reindex/Low: Job 6GzTPknC1.../1/full-text-reindex/Low execution failed. Retrying later.
org.http4s.client.UnexpectedStatus: unexpected HTTP status: 400 Bad Request for request POST http://192.168.15.102:8983/solr/docspell/update?overwrite=true&wt=json&commit=true
 (jobId: "6GzTPknC1NC-4TBBNjTbnB5-LTgrPRXGGaT-uEExNsDk2qz", task: "full-text-reindex", group: "1", jobInfo: "6GzTPknC1.../1/full-text-reindex/Low")
```
Fulltext search is still broken for me. I'll look at this tomorrow. Thank you!

**Comment by eikek** [comment]
Hm, strange. The solr logs can show such errors, because there are situations where docspell removes and creates a field. Solr doesn't have an api for it, so it would error when deleting a non-existent field. A very aggressive approach can be to re-create the solr core (stop docspell first) and then start docspell. It should then populate the index.

**Comment by vakilando** [comment]
**Thank you for your support, it works again!**
I followed your suggestion of a "_very aggressive approach_" to re-create the solr core (stopped docspell first) but it didn't work... 
Then I deleted the whole solr docker (config, image and files in persistant volume) and recreated it. This also did not work. 
So I finally deleted the solr docker (config, image and files in persistant volume) again and recreated it but this time I even upgraded solr from bitnami solr docker 8.11.3 to 9.5.0. After this it worked and populated the index!

Just for Info, this is my docker run command on my unraid server:
```
docker run
  -d
  --name='solr'
  --net='eth1.15'
  --ip='192.168.15.102'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="FloBineDATA"
  -e HOST_CONTAINERNAME="solr"
  -e 'TCP_PORT_8983'='8983'
  -e 'SOLR_PORT_NUMBER'='8983'
  -e 'SOLR_CORE'='docspell'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8983]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/solr.png'
  -v '/mnt/cache/appdata/solr/':'/bitnami':'rw'
  --mac-address 02:42:E1:15:01:02
  --health-cmd='["CMD", "curl", "f", "http://192.168.15.102:8983/solr/docspell/admin/ping"]'
  --health-timeout=10s
  --health-retries=2
  --health-interval=60m
  --health-start-period=30s
  -e SOLR_CORES=docspell
  -e SOLR_OPTS="$SOLR_OPTS
  -Dsolr.modules=analysis-extras" 'bitnami/solr:9'
```

As I did not change the solr configuration except that I moved from '_bitnami/solr:**8**_' to '_bitnami/solr:**9**_' it seems that the solr container (v8) from bitnami has a problem with the "new" env-var: `-e SOLR_OPTS="$SOLR_OPTS -Dsolr.modules=analysis-extras`".....

thank you again!

**Comment by eikek** [comment]
Thank you @vakilando for the update! It looks like with this setup, solr has to be at least version 9. It only is strange to me, I'm not aware that anything changed to require solr9 now.

**Comment by vakilando** [comment]
Yes strange, perhaps a problem with the bitnami v8 Container, or with my docker setup - i just realized that after removing the bitnami solr V8 Container I still hat a dangeling docker image of v8...
