### ISSUE TITLE
Save Name on confirm

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#255]
Hi, 

I really like the new update :)  Nice work!

Another little thing that has bothered me now more often: All fields except the one for name are saved directly. What I felt already 100 times has happened to me now: Name changed, forgot to press save, pressed confirm, changes were lost. 

An idea could be to save the name field while pressing the confirm button?

Cheers
Eresturo

**Comment by eikek** [comment]
Ah yes, so true. I don't like this save button anyways (I have to use the mouse, while on the keyboard…!) It would be easy to submit a request when pressing "confirm", that's a nice idea. It might be a little harder to indicate success/failure. I'm thinking to try first to submit the save request while typing (when paused a few ms) and indicating the result with a little icon (where currently the save button is).
