### ISSUE TITLE
No suggestions for hidden fields  

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#256]
Hi,
if you have hidden a field, e.g. due date, you still get suggestions, but you can't delete them, because they are hidden. My suggestion is not to make suggestions for hidden fields. 
Sheers
Eresturo

**Comment by eikek** [comment]
Ah sure...  this was not well done. I'd really like to leave this a feature at the client only (currently the server doesn't care about hidden fields). But to really support it, the server needs to know this, too – and it would be a setting of the collective then. Currently it only removes it from the view for the logged in user. So I would now also remove it consistently from the item headline and the cards. Would this also work for you?

**Comment by eresturo** [comment]
The problem with client only is, that you confirm wrong suggestions then, because you never see them.
Let's say you disable due date at the moment. When you enable it one day you have many wrongly confirmed due dates in your database.

**Comment by eikek** [comment]
Yes, this is a problem indeed. But having no due-date could be also wrong when re-enabling this field, no? It's an "unknown wrong", yet also confirmed. But I also think that this is the better option! Better have no value than a wrong one. One solution could be to unset all hidden fields when the user clicks "confirm"? It is then still client only, but the effect seems the same. Another user of the collective could still change the values, though, but this should not be a problem I think. wdyt?

**Comment by eresturo** [comment]
> Better have no value than a wrong one.

Absolutly

> One solution could be to unset all hidden fields when the user clicks "confirm"?

I like this idea.
