### ISSUE TITLE
[Question] Using OpenId with Docspell Api

### ISSUE THREAD

**Issue by DominicSaladin** [eikek/docspell#2584]
I'm pretty new to Docspell and just configured everything on my server to run all the required components. I also integrated a OpenId provider to authenticate, instead of the Docspell login.

Now I would like to use the Api for further processing and maybe some custom websites for some processes, but with a user based login. Is there any way to use OpenId authentication while still authentication on behalf of a user to Docspell (without using username and password)?

**Comment by eikek** [comment]
Hi, I think I don't understand the question, sorry. If it is desired to authenticate as another user, you can probably use features of the OpenID provider. Some support impersonating users, I think. Using the api, you need to somehow get a token, which would require an initial login using username/password. Some routes allow for alternative auth methods (like uploading files you can use a "source id").

**Comment by eikek** [comment]
Yes, I think so. I mean, it also depends on how you configured your OpenID provider. Initially I would assume that you need to give username + password.

**Comment by DominicSaladin** [comment]
Perfect, that is all I needed to know. Thank you!
