### ISSUE TITLE
password authentication failed for user "dbuser"

### ISSUE THREAD

**Issue by ZuluPilgrim** [eikek/docspell#2589]
I have change the password for dbuser in the docker-compose file but now I get, 

`password authentication failed for user "dbuser"`

I tried searching  for 'dbuser' in the file and change all related password values to the same value, but this did not help

- DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=mypassword
- DOCSPELL_JOEX_JDBC_PASSWORD=mypassword
- POSTGRES_PASSWORD=mypassword

**Comment by ZuluPilgrim** [comment]
Ok, I changed it back to dbpass and all worked. Is there no security issue using a published password?

**Comment by eikek** [comment]
I'm not sure I understand. If you change the password in the compose file, you of course need to change it on postgres first no? For the security concern, it all depends on how you are exposing your things. And then the provided compose file is for getting started quickly. Everyone has their own ways of running things, so just adopt as you see fit.

**Comment by ZuluPilgrim** [comment]
I just wanted a password that was not the default so  changed it everywhere i.e. POSTGRES_PASSWORD too but it would not connect. When I put it back to dbpass, it worked again. I must have missed changing it somewhere else too. I will try again later in the week.
