### ISSUE TITLE
FR: Allow to find all documents without tags or deselect all tags easily

### ISSUE THREAD

**Issue by SBGit-2019** [eikek/docspell#2608]
Also for importing new documents it would be good if the search would allow to easily find all documents which are not tagged.
Either allow directly to search for all untagged documents or allow to make all tags easily to have selected the "-" sign. The function can be achieved now already if you manually click all tags on "-" but that is tedious. If the feature already exists I could not find either function easily. Maybe then in the docs?

**Comment by eikek** [comment]
Isn't this a duplicate of #2620 ? I think a UI only option is not very nice and efficient, it should be supported by the search query.
