### ISSUE TITLE
Errors while processing documents

### ISSUE THREAD

**Issue by cappucino70** [eikek/docspell#2614]
I keep seeing the following message in the document processing log:

`Error updating with chunk of data: Error connecting to http://localhost:8983 using address localhost:8983 (unresolved: false)`

This has worked for 2 years, but the VM has already been moved to another host 2-3 times. The IP of the Docspell has changed. However, the DNS resolution works correctly. What could be the reason?

The second problem is that I can hardly find anything using the search. I have already started the re-indexing several times.

My installation is this one: https://github.com/andreklug/docspell-debian

**Comment by eikek** [comment]
Hi and sorry for the long delay, some notifications slipped through my attention apparently.

The error means, that docspell cannot connect to SOLR. This is probably also the cause for your search not working well. I cannot say why connecting fails, perhaps a network issue or solr is down?
