### ISSUE TITLE
Document Classifier - Remove category restriction

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#263]
Hi,
i'm about to test the really cool feature of automatically suggesting tags. What I ask myself during configuration is: Why do I have to specify a category? Do the suggestions only work for tags from this category?
Sheers
Eresturo

**Comment by eikek** [comment]
Yes exactly. It only suggests tags from this given category. The system can only learn from tags that somehow relate to patterns in the text. So tags like "todo" can't really work with that feature. But the typical "document type" tags like "invoice", "contract" etc should be no problem. Currently, only one category is supported. It is rather an experimental feature, still open where to go from here :-)

**Comment by eresturo** [comment]
Thanks for the clarification.
Then I wait excitedly until several categories are supported :)
