### ISSUE TITLE
Running addon in docker fails: Error response from daemon: invalid mount config for type "bind": bind source path does not exist

### ISSUE THREAD

**Issue by tiborrr** [eikek/docspell#2666]
I do not think it works correctly yet.

I am now getting this error:

```log
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/docspell-addons/addon-14483220073169593010.
```

```log
Thu, May 30th, 2024, 14:16: Running external command: docker run --rm --name docspell-addon-example-0.7.0-4B1nxM --mount type=bind,source=/tmp/docspell-addons/addon-14483220073169593010,target=/mnt/work --mount type=bind,source=/tmp/docspell-addons/addon-output-10138378789386319765,target=/mnt/output --mount type=bind,source=/tmp/docspell-addon-cache/EXpNaSFCvTP-eXs6FcYKdaS-41zyL95tTUR-jJERLW2CNkj,target=/mnt/cache --network none --env ADDON_DIR=addons/docspell-addon-example-0.7.0 --env ITEM_DATA_JSON=item/item-data.json --env DSC_DOCSPELL_URL=http://localhost:7880 --env ITEM_DIR=item --env TMP_DIR=temp --env TMPDIR=temp --env CACHE_DIR=/mnt/cache --env ITEM_ARGS_JSON=item/given-data.json --env ITEM_ORIGINAL_JSON=item/source-files.json --env DSC_SESSION=1717078614008-MS9ldHMvNldTa1dQaTl5dDYtTXROMmYzVXlwRGctY2tRQTZka1lOZG4tTlRIczJjTnhkTkgvYWRtaW4=-false-900-$2a$10$/xwLHsshpLKSDGii55kbUu-a8eFZrPefIXqO6qxnktUXLwPC/A= --env ITEM_PDF_JSON=item/pdf-files.json --env OUTPUT_DIR=/mnt/output --env ITEM_ORIGINAL_DIR=item/originals --env ITEM_PDF_DIR=item/pdfs -w /mnt/work tiborr/docspell-addon-example:latest arguments/user-input
Thu, May 30th, 2024, 14:16: Waiting for command to terminate…
Thu, May 30th, 2024, 14:16: >> [docspell-addon-example-0.7.0 (err)] docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/docspell-addons/addon-14483220073169593010.
Thu, May 30th, 2024, 14:16: >> [docspell-addon-example-0.7.0 (err)] See 'docker run --help'.
Thu, May 30th, 2024, 14:16: >> [docspell-addon-example-0.7.0 (err)]
```

I also think it's weird you are getting this `pull access denied for tiborr/docspell-addon-example` because this is a public repo.

[link to docker hub](https://hub.docker.com/repository/docker/tiborrr/docspell-addon-example)

Can you check what happens if you do `docker pull tiborr/docspell-addon-example` in your joex instance

_Originally posted by @tiborrr in https://github.com/eikek/docspell/issues/2650#issuecomment-2139689454_

**Comment by eikek** [comment]
This is what I get:
```
$ docker pull tiborr/docspell-addon-example
Using default tag: latest
Error response from daemon: pull access denied for tiborr/docspell-addon-example, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
I assume I have to configure something perhaps?

**Comment by tiborrr** [comment]
How stupid. I already found the issue. Can you update the plugin and retry once? 

I made a typo:

`tiborr**r**/docspell-addon-example`

**Comment by tiborrr** [comment]
I updated it. Now the example should work. 

Once it works it would be great to add this somewhere for other people to use.

**Comment by eikek** [comment]
I tested it again successfully! Thank you for testing this!

Where do you like to add this example? If you want you can add it somewhere in the docs, and/or also use a topic on github `docspell-addon` (makes it easier to discover, like [this](https://github.com/topics/docspell-addon))?

**Comment by tiborrr** [comment]
Both would be best. Then what you have on your website reflects what is in the docspell repo. How do we achieve that result? Do you fork my example repo? Or can you make some kind of link? 

I you decide to fork it, then make sure to adjust the .github files. Because they currently point to my docker repo.

**Comment by tiborrr** [comment]
I have updated my repo so its easier to port. I have made the things that require configuration a Github secret in the github release file.

**Comment by eikek** [comment]
I don't think it needs to be forked - or do you intend to remove it from your account soon? I would simply point to it in the docs.

**Comment by tiborrr** [comment]
Pointing to it in the docs would be fine. I do not intend to remove it.

**Comment by tiborrr** [comment]
Found the issue. This was caused by a missing volume in the docker compose.

```
volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp # this line was misssing
```
