### ISSUE TITLE
Release v0.42.0 -- taged docker containers?

### ISSUE THREAD

**Issue by marvin8** [eikek/docspell#2743]
I was just trying to update my docker containers for docspell to the new release version v0.42.0 but have found that the docker containers at https://hub.docker.com/r/docspell/joex/tags have no tagged version for v0.42.0.... 

Is that intentional?

Anyway, I'd like to thank you for sharing docspell. I've been using it for the last couple of years and it works pretty sweet for me :wink:

**Comment by eikek** [comment]
Hi @marvin8 , thank you for letting me know (and the kind words :-)). This is not intentional. Something went wrong unfortunately. I'll look into it and publish the images soon

**Comment by eikek** [comment]
I just published the images from my notebook. It seems the process on release used the wrong version and thus published snapshot images (successfully, so I didn't notice…).

**Comment by marvin8** [comment]
Awesome... thank you.

I just successfully updated to v0.42.0 version in my podman setup. Seems to be working great.
