### ISSUE TITLE
"Try it docker setup" uses wrong path

### ISSUE THREAD

**Issue by ministryofsillywalks** [eikek/docspell#281]
The instructions to start the docker compose are run from the wrong folder if you follow the mini tutorial

```
git clone https://github.com/eikek/docspell
cd docspell
DOCSPELL_HEADER_VALUE="my-secret-123" docker-compose up
```
should be:

```
git clone https://github.com/eikek/docspell
cd docspell/docker
DOCSPELL_HEADER_VALUE="my-secret-123" docker-compose up
```
because the compose file is in the docker folder and not the root folder.

**Comment by eikek** [comment]
oh thanks so much for reporting, what a stupid mistake

**Comment by eikek** [comment]
Luckily the website was right, readme fixed now.
