### ISSUE TITLE
FR: Proper docker files

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#283]
So far they just download binaries from github and are fixed to a version.

Would be great if they would actually run the installation, so one can easily deploy the latest committed version..

I might give it a try in the next days myself :-)

**Comment by eikek** [comment]
That would be nice indeed, thanks. Yes, currently it only provides the latest released version :-). Let me know if you need support when building it. Some notes about this are [here](https://docspell.org/docs/dev/building/).

**Comment by eikek** [comment]
Thank you so much!
