### ISSUE TITLE
Debian install only 127.0.0.1

### ISSUE THREAD

**Issue by t4t4nos** [eikek/docspell#2837]
Hi, I succed to install for test Docspell on Debian 12. But when I launch the I have this
org.http4s.ember.server.EmberServerBuilderCompanionPlatform - Ember-Server service bound to address: 127.0.0.1:7880
and I can't have acces to Docspell, on other IP. I try to change this in the conf files of docspell-restserver and docspell-joex, with the 0.0.0.0 and 10.0.0.34. Nothings works, always 127.0.0.1. I don't understand.
Pls help me.
Thank in advance.

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by t4t4nos** [comment]
> You need to change the `bind.address` as described here: https://docspell.org/docs/configure/bind/ - try to set it to `0.0.0.0`.

[eikek] thank  a lot  I just missed a localhost in the conf file of Joex.
