### ISSUE TITLE
Trying to sign up "There was a network error."

### ISSUE THREAD

**Issue by t4t4nos** [eikek/docspell#2841]
Hi,
I succeed to launch and access the log page. And I have the error when I try to create an account. 
Collective ID and User Login are the same "admin" and password and are the same. Don't understand why the log of CLI doesn't show an error. The database worked it's connected, but, nothing happen.
Can you help me pls ?
Thank you in advance.

**Comment by eikek** [comment]
Hi @t4t4nos what are you trying to do exactly? Signup on the web ui, using the cli or logging in on the web ui, perhaps? Where did you get this error message from?

**Comment by t4t4nos** [comment]
> Hi @t4t4nos what are you trying to do exactly? Signup on the web ui, using the cli or logging in on the web ui, perhaps? Where did you get this error message from?

On the page http://IP:7880/app/register when i try to sign up on the web ui.

**Comment by eikek** [comment]
then this seems to be an issue that your browser cannot connect to the restserver. can you open the dev console on your browser and look at the "Network" tab to see where the requests are being sent to? Perhaps you need to reset or update the `base-url` setting.

**Comment by t4t4nos** [comment]
> then this seems to be an issue that your browser cannot connect to the restserver. can you open the dev console on your browser and look at the "Network" tab to see where the requests are being sent to? Perhaps you need to reset or update the `base-url` setting.

@eikek  thank you a lot again. It work, (I'm in the dashboard). To fix my  problem earlier, I put in  base-url =  0.0.0.0. Of course it doesn't not work.
