### ISSUE TITLE
Add convenience enhancements

### ISSUE THREAD

**Issue by Lucki** [eikek/docspell#289]
* Localization
  * Render time in local time (it's currently UTC)
  * Use the correct [local date format](https://en.wikipedia.org/wiki/Date_format_by_country) - for me:
    * `DD.MM.YYYY` instead of `MM.DD.YYYY`
    * `DD MMMM YYYY` instead of `MMMM DD, YYYY`
  * (Other languages, probably a bigger task)
* Dark theme
* Searchable documentation - everything is in categories and it's a bit difficult to find a specific part again.

**Comment by eikek** [comment]
Thanks, yes these are all valid points! Some quick comments
- Localization of UI: This is a lot of work, since all view files need to be touched and converted. That's a reason why I'm not doing it right now. It's not just dates, but also all the texts.
- Dark theme: this is even more difficult, sadly :/. I tried it on my other project – there is no dark theme for Semantic-UI. A workaround for now is to use the [DarkReader](https://github.com/darkreader/darkreader) browser extension. 
- Other languages are coming: next I'm considering is Spanish. I have to check if all the tools support it
- Searchable documentation: You are so right, I'll see to move this up. Since the site generator offers this already, it shouldn't be so much work (I hope).

**Comment by Lucki** [comment]
>  * workaround for now is to use the [DarkReader](https://github.com/darkreader/darkreader) browser extension.

Yes, but it's not perfect on all UI elements. (I prefer [this](https://github.com/m-khvoinitsky/dark-background-light-text-extension) extension, it is running a lot faster here)

>  * Other languages are coming

Whoops, should have placed that into the localization group, meant the UI elements.

Anyway, thanks for considering :)

**Comment by eikek** [comment]
Hi @Lucki ,

thanks a lot for the pointer to the browser extension and your inputs! If you don't mind, I'd create separate issues for your points and then close this one?

As said, localization will probably not happen anytime soon (by myself, PRs gladly accepted). But later, I'd like to add this! Same with dark-theme. I also think about a ui rewrite from time to time, but only when the whole thing reaches some mature state. However, auto-reset of upload page (yeah, that's very reasonable :)) and search in docs is something for the near future.

**Comment by Lucki** [comment]
Sorry for hijacking this with a question: Is there an exit strategy? E.g. when this isn't suitable anymore or support ends, what happens to my files? Since everything is in a database it's not as easy as moving the plain files to another location. Could you add a section in the documentation about this please?

> If you don't mind, I'd create separate issues for your points and then close this one?

Go ahead, do what it needs to keep the best track of it.

**Comment by eikek** [comment]
No worries bc of hijacking: Currently there is no easy way to get things out. But the data model is open and the rest api is documented. It shouldn't be too hard with some fiddling :-). For example, with the api it is possible to create a simple bash script that downloads all items as json and then every file. Right now the most reliable way without fiddling is to only import things from a folder and not deleting these files. However, this won't give you the metadata but at least it lets you control the files that go in (you can also check with the `ds.sh` script if a file is in docspell). In the longer run, there will be a CLI tool and this can have a command for downloading files and exporting metadata into some format. If all you need is a file (and not a separate database process), you could go with the H2 database option which is in-process and stores everything in a file.
I need an exit plan, too ;-) I create a postgresql dump every night. It's just one command and not more difficult than a rsync. Knowing that I can always run the application later (e.g. with docker) and knowing that I can just use standard sql even without the application, is enough for me. So I postpone the exact exporting to some specific format to the time I need it, but I know that I can always access all the data. And the database dump is all that is needed to run the app – there is no additional setup required.

I think this is a good question for starting a faq section in the docs, thanks.

**Comment by eikek** [comment]
Closing this; there are separate tickets for the mentioned points here.
