### ISSUE TITLE
/opt/docspell.conf isn't used

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#303]
It still works on the last release - just not on the latest/self-compiled version!

Mapping for local one is done in `docker-compose.yml`and seems to work properly:
```
volumes
	- ./docspell.conf:/opt/docspell.conf`
```

execing ls in the container also shows that all rights are there:
```
-rwxrwxrwx    1 root     root           871 Oct  3 17:35 /opt/docspell.conf
```

But still, the default one is used :-/
```
[main] INFO  d.r.Main - Using config file from system properties: /opt/docspell-restserver/bin/../conf/docspell-server.conf
```

**Comment by eikek** [comment]
Is the code on your branch? Or where can I find it for playing around?

**Comment by totti4ever** [comment]
Not committed, yet. Wanted to keep the commit history clean for the PR ;-)

But figured out the problem: When combining entrypoint and cmd one has to use [] notation for them, but then again ENV variables cannot be used (for JVM params). Because I switched to exec notation in order to have the var read properly, docker went on to ignore the cmd and therefore the path to the conf file!

I would go with setting the JVM params by JAVA_OPTS ENV variable now and not passing it directly to the docspell binary calls. From my understanding and little testing, this seems to work.

**Comment by eikek** [comment]
great! don't worry about unclean commits too much. you can always squash them together afterwards

seems strange that it's not possible to have env variables in the command, but I have no clue:) if it can be solved better or differently thats fine. consumedir image also needs an env Variable currently in the command.
