### ISSUE TITLE
Cookies not set when using traefik (because of X-FORWARDED-Header)

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#308]
When it exists, Docspell uses the `X-FORWARDED-FOR` header as domain for the cookies. But this Header contains IPs or local host names (e.g. laptop.lan) at best.

Correct would be `X-Forwarded-Host` or `Host`.

This is a major bug when using traefik as one cannot disable the forwarded-headers there, i.e. all functions relying on cookies don't work with traefik right now.

**Comment by eikek** [comment]
Unfortunately, docspell uses the `-FOR` header first, and then checks the other mentioned headers, which is wrong obviously. As discussed in chat, I will simply drop the `domain` cookie attribute. The browser then associates it to the origin used to "request" the cookie.
