### ISSUE TITLE
FR: Configure database connection through environment variables [Docker]

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#312]
Right now, one has to adapt the docspell.conf. Since the last release an adaption is not necessary any longer when using other hosts. So the DB connection is the only adaption left in my case.

I'll try to setup a PR for this, but want to have this issue as reminder.

**Comment by eikek** [comment]
Hi @totti4ever – this seems done to me?

**Comment by totti4ever** [comment]
Yes, you are right! At least, I am using it :-)

**Comment by eikek** [comment]
Great :-) I'll close it then….
