### ISSUE TITLE
FR: build automated docker builds

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#318]
In order to benefit from the new build hook from #311, I suggest to add the following automated builds to docker hub:
1. https://hub.docker.com/repository/docker/eikek0/docspell/builds/edit
2. add the following rules
![image](https://user-images.githubusercontent.com/49901208/95752927-1c5c2180-0ca1-11eb-8e97-b76719ce5c19.png)

This will
* on commits to master build new SNAPSHOT images
* on new tags with format v0.00.00 build new versioned images (there's is a check that version.sbt is the same as the tag name, be aware :-) )

**Comment by eikek** [comment]
Works great - thank you!
