### ISSUE TITLE
Cannot upload files larger than 10 MB

### ISSUE THREAD

**Issue by AlertSubject** [eikek/docspell#322]
Hello there,
I've noticed that every file that is larger than 10 MB fails to upload. Tried this via webapp as well as mobile app. Is there an upload limit regarding file sizes?

Thanks!

**Comment by eikek** [comment]
I'm not aware of adding any limits to the app itself. Are you using it behind some reverse proxy? These will also usually add limits to the request. With nginx for example, I have this option set: `client_max_body_size 50M;`.

**Comment by AlertSubject** [comment]
Thank you so much!
Did not think of that, fixed the issue
