### ISSUE TITLE
Changes to the Tag / Category system

### ISSUE THREAD

**Issue by AlertSubject** [eikek/docspell#323]
If I have a tag named "X" that belongs to category "Y" I cannot use the name "X" again, even if "X" belongs to category "Z" in another case.

Example: 
Tag - UPS
Category - Correspondence
/
Tag - UPS
Category - Invoices

In this case there is an error message when creating the second example because the tag UPS is already in use.
But I think it would be handy if a name could be used multiple times if the category is different 

Thank you!

**Comment by eikek** [comment]
Thank you very much for your input! I have to admit, it never occurred to me having same tags in different categories. (I have to improve the error message though. It seems it only displays a server error.) Currently there are some features relying on this uniqueness, for example: keywords in pdf files (in their metadata) section are compared against the tags in the database and there are rest calls that allow to set tags by names. So I'm not sure if we should open it up. There is no easy way back then :) and the mentioned features would behave in a strange way I think.

In your example, wouldn't it be possible to solve it differently: like use UPS as an organization? Or was it just an example and not a real use-case?

I would leave this issue open to see how others think about it. I currently tend to rather not remove the unique constraint.

**Comment by totti4ever** [comment]
From my thoughts, it might be feasable to to add the category in brackets, like _UPS (Invoice)_ and _UPS (Correspondence)_. I guess one is meant to be the invoice (obviously) and the other means you write them a letter and get the answer? Wouldn't it be enough to have UPS as correspondent and only the tag _Invoice_ and _Correspondence_? That would shift your tags one level up. One could also add the 'department' (Invoice or Correspondence) as person to the organization.

I think in the way the tags are right now, it makes sense that they are unique as the category is more like an additional information and not a complete different _tag world_

**Comment by AlertSubject** [comment]
Yeah i guess ill fall back on only using the name tag and leave the category tag blank since that also works as intended for me, its probably easier that way and requires no changes in the code
Thank you!
