### ISSUE TITLE
FR: Show number of pages as metadata

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#325]
Would help to identify and quality check documents easer. Especially the latter is important to me, when doublechecking that the whole physical document has arrived in docspell before I trash it :-)

Additionally, one could implement the feature from papermerge, where you can edit/remove pages in the WebUI. Would help me alot to remove blank pages (havn't mastered to do that by script, although one should think with OCR it was easy to identify blank pages...) - but this is probably quite an effort to implement, so let's focus on the former ;-)

**Comment by eikek** [comment]
Just to make sure I understand correctly: the number of pages of each file should be visible somewhere? Or do you want a metadata field like "pages" that you can edit?

Editing the files directly is something that I have planned, but it's still a long way; I want other things first :)
