### ISSUE TITLE
FR: Overwrite ocrmypdf parameters by env variables [Docker]

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#326]
I learned, they can be set in the docspell.conf - but for convenience during updates, I think it'd rather nice to keep that file untouched and have the params being overwrite in the `docker-compose.yml` or `.env`

Will open up a PR for this myself!

_https://docspell.org/docs/configure/_

**Comment by eikek** [comment]
Hi @totti4ever just going through some older issues :) Are you still interested in this issue? If not, I'd close this as I don't have a use and shy away from maintaining more docker stuff :-)

**Comment by totti4ever** [comment]
Not for my personal use, thus can be closed
