### ISSUE TITLE
FR: Show thumbnails as preview

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#327]
Having had a look at the latest papermerge, I have to say that previews are just really helpful to feel confident about a software like docspell. I totally get your point and meanwhile I think one can live without it - but as I said...for starting with the software it just gives confidence about where one's documents are :-)

**Comment by Lucki** [comment]
I'd like to add that the current hugely displayed filename is almost completely worthless for me - they're mostly "Scanned document.pdf" which is meaningless. I'd appreciate an option to replace the filename with a thumbnail.

**Comment by eikek** [comment]
The filename is used as a default value for the item name. The name can be changed (independently from the filename) which then makes sense to display in the card, I think. I'm using the name quite often, but not curating it for every document. The item name is also added to the fulltext index. My scanner allows to set filename profiles, so it's not completely useless for me. Then not all files are coming from my scanner, then I don't want to loose this name. However, I totally see your point.

If you don't want to use the item name, then it's of course needless. It should be possible to hide it – I think I simply forgot the item name when I added hiding some fields in the ui. When a thumbnail can be displayed and the item name hidden via ui-settings, would this support your use-case enough @Lucki ?

Regarding "or something other?" – do you have something specific in mind? I was thinking about to display the whole pdf inside a small preview area in the card. But I think this is a waste of traffic, some files may be large. So I tend now to create a png/jpg from the first page of each document and scale it down.

**Comment by Lucki** [comment]
> When a thumbnail can be displayed and the item name hidden via ui-settings, would this support your use-case enough @Lucki ?

I guess so, it's then possible to see a rough layout and if it's somewhat what you're expecting out of a search.

> do you have something specific in mind?

No, I just didn't want to say it _has_ to be a thumbnail. Maybe something else is also suitable as a document representation.
