### ISSUE TITLE
FR: Make persons being suggested as correspondent only

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#332]
Actually in my case, persons are either adressed/concerned (my wife and me) or are correspondents. Right now I can keep my wife and me out of the correspondent suggestions, but the correspondents not out of the concerned suggestions.

Plus: Wouldn't a correspondent always be linked to an organization? So after selecting an organization, I would only have the persons suggested who are part of that organization

**Comment by eikek** [comment]
The organization->person connection is not modelled in docspell. I was thinking about this, too and figured to move it to a later point. Generally this whole section about organization/person can be improved a lot (like importing data from somewhere, make it feel more like an address book and not this simple crud thing…)

For the concerned/correspondent person: would you want it to be completely excluded, or only when using it for making suggestions?

**Comment by totti4ever** [comment]
1. I don't think importing contacts would make a big difference as I guess most people don't have the people/organizations they get letters they scan from in their address book - or do you?
2. I think that the relation Orga -> Person is a must, especially when deriving those metadata automatically. It doesn't make sense to have Person A of Bank 1 as correspondence together with organization Bank 2.
3. For me, the _concerned person_ is some person in the collective while the correspondents are always external, at least in another collective. Or would you have some letters appear from/to people within the collective? So, yes - I would make it either concerned or correspondent (at least selectable, for me it would be 100%)

But, I am open to other use-cases, maybe I don't see them for myself so far :-)

**Comment by eikek** [comment]
1. Agree!
2. Agree!
3. That's where I was always a bit unsure. My case is exactly as yours - I guess all families would work tihs way. But I might not see other interesting use cases :-) So I'd change the ui in that the dropdowns and suggestions only show the options as you describe. It is the sanest thing so far. The api would still allow to set an external person as concerned and an "internal" person as corresponent.
