### ISSUE TITLE
FR: apply count of tags etc to current search

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#333]
The filters apply additionally to the text filter, but the preview/count is based on all documents:
<img src="https://user-images.githubusercontent.com/49901208/96251609-03a97f80-0fb1-11eb-91ba-2f4d1300e04a.png" height=100 />

This is quite unintuitive and it would really help to also get a grasp on the search results when thoe counts would come from the already narrowed results.

Hope this is understandable :-)

**Comment by eikek** [comment]
Yes, understood and agreed :)

**Comment by eikek** [comment]
Fixed in #496  (via #511)
