### ISSUE TITLE
Create a CLI client

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#345]
It should support at least changing all metadata for an item and uploading files. It can then replace the current `ds.sh` script. Prepared to provide admin tasks like export/import etc.

**Comment by almereyda** [comment]
You could check out https://docspell.org/docs/tools/ds/

**Comment by eikek** [comment]
You're right, this is already something useful! But there should be a "real" cli client, that can, for example, change item metadata etc. Best would be to support the complete remote api, of course, but a good start is to be able to modify items to become useful in scripts.

**Comment by eikek** [comment]
Finally: https://github.com/docspell/dsc
