### ISSUE TITLE
Safe deletion of items

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#347]
Currently deleting an item immediately removes it from the database.

Other approach: add a new state `deleted` and create a periodic job that really remove those items. Deletion for the user is then super fast and it can be "undeleted" for some period of time.

**Comment by maspiter** [comment]
Nice, but how to delete an item? I see how to remove documents from an item but no option to remove an item itself.

**Comment by eikek** [comment]
You need to go to the detail of an item and then click on "edit" to open the menu where you can set tags etc. On the top right of that menu, there is a delete button (in red). Its on this screenshot: https://docspell.org/docs/webapp/curate/#modify-if-necessary

**Comment by maspiter** [comment]
Okay, got it. Thanks. That's a bit hidden but essential functionality.

**Comment by eikek** [comment]
Ok, where would you put it? I think the edit menu is not a bad place; deleting items is probably rarely used, no? So my thoughts where to save the more prominent space for more often used things. But I might simply miss other use-cases. If you think this is important, could you open another issue for this? Thanks! (discussion and tracking; as this is already another one ;-))
