### ISSUE TITLE
FR: Make information in detail header clickable

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#355]
So when I click on the organization or one tag, I am transferred to the search with this item selected. Would make the navigation more fluent and also helps in certain use cases (looking for a document by text search, but it is not the right one, but the organization was right. So instead of going back and selecting the orga, one could just click in the header)

**Comment by eikek** [comment]
![Selection_054](https://user-images.githubusercontent.com/701128/96643210-87ec6180-1327-11eb-9074-7011fd6e669d.png)

You mean this right?

**Comment by totti4ever** [comment]
Exactly, folder would make sense as well of course

**Comment by eikek** [comment]
Yes I see, I like the idea. It would then simply add to the search form, to further narrow down the search results. If the search form already has this org/folder etc set, then it's a noop. - ?

**Comment by totti4ever** [comment]
Interesting, I thought adding them to an empty search. So when you click on Tag `bill` you see all bills, not only the ones of the last search.
But your way also makes sense, depending on the use case.

But coming from mail programs maybe, I would still prefer 'my' way. Providing both would of course be possible, but tricky ui wise

**Comment by eikek** [comment]
Ah ok, so you mean a click on a tag or organization empties the search form and only sets this one thing? Yes, that makes sense! It's probably better this way, because one would probably rather search something different instead of narrowing what was there already.
