### ISSUE TITLE
BUG: Error while processing (Unclosed group near index 12 (?i)(telefon)

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#356]
```
2020-10-20T12:29:05: Job 2uqmKQH3N.../Collective/process-item/High execution failed. Retrying later.: Unclosed group near index 12 (?i)(telefon
```

What's happening here? Happens with several documents; they contain normal information like letters do with the official telephone numbers

**Comment by eikek** [comment]
I'll have a deeper look later. I guess currently it is a bug with how regexes are derived from your address book. It seems that some values (phone numbers here?) contain parentheses that break the regex syntax. If this is true, a workaround is to disable the `text-analysis.regex-ner` processing in the joex config. It will still do (quite good in my case) correspondent recognition, but may not be as accurate.
