### ISSUE TITLE
Update the overview/search page after detail edition

### ISSUE THREAD

**Issue by svenihoney** [eikek/docspell#357]
### Observed
After editing the details of a document and going back to the search results, the document's data/status is not updated.

### Expected
1. Update the document's tile data after edititing the details
2. Remove the document from the page if it does not match the search conditions anymore

### How to reproduce
@1.
1. Pick the first document
2. Change the document title
3. Go back to the overview page with the left arrow: The document title stay the same. Applies to other document details as well.

@2.
1. Go to detail search and select "only new"
2. Pick the first document
3. Set the status to "not new" by picking the check mark
4. Return to overview page: The document is still marked as new and not removed from the search results.

**Comment by eikek** [comment]
Thanks a lot for reporting!

I hoped this is solved in the 0.13.0 release – did you use this version?

**Comment by svenihoney** [comment]
Was waiting for the *-latest containers to update - they are still on .12. Pulled the v0.13.0 containers, with these the behaviour is as expected. Keep up the good work, I like it a lot!

**Comment by eikek** [comment]
Ah ok, thanks for telling me. I think they are now spelled `LATEST` (upper case) – I might add it to the changelog.
