### ISSUE TITLE
FR: Show number of items in processing queues

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#364]
I think it would give a better feel when I look on the processing page and can see immediately how long the lists of waiting and failed items are. So maybe just put the numbers beside the arrows?

Plus, maybe add a little filter to only show successfully and failed documents.

**Comment by eikek** [comment]
Yes, this is so true – the processing page is a very quick thing, it can be improved a lot (see 2. point in #363)

**Comment by eikek** [comment]
I think this is realized now in the new UI, from 0.20.0.
