### ISSUE TITLE
FR: Reprocess items

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#365]
I am right that I can set the parameters for retrying, but once a document processing has failed I have to chance to re-start it through the UI?

I think it would be quite helpful to have an icon for re-starting after one has fixed some problematic orga/tag names or simply updated the version.

**Comment by eikek** [comment]
Yes this is right. It's a slightly different intention: restarting while processing is a general retry for long-running tasks. The other situation is to submit the item to processing again. For the latter there is no UI currently. Reason was that you'd only need it rather rarely; I thought most of the time it's easier for one item to simply change what is wrong (like orga/tag name), no? But for new versions, maybe it's better to submit all to reprocessing?

**Comment by totti4ever** [comment]
My specific problem was the error on classification, which was gone after updating. For this case I would have liked to just restart the processing of the failed files.

Maybe just add two buttons:
1. reprocess all items (after adding information/assigning metadata)
2. reprocess failed

But yes - it would be used rather rarely, true!

**Comment by TheOneValen** [comment]
I would regard this as an rather important feature. Imagine importing a large (sorted) collection of documents for which you all have to set tags/correspondents/etc. Reprocess them if you setup the most important metadata! Also would be great if the document date would automatically select the suggestion.

**Comment by eikek** [comment]
But wouldn't it also work, if you first import maybe 50, fix all their metadata and then import the rest?

**Comment by TheOneValen** [comment]
Sure but you would have to put much more effort into what to import first.

**Comment by eikek** [comment]
There is already an endpoint to submit a single item to reprocessing, but without setting the newly extracted metadata. I thought about extending this to set metadata, but only for new items (as you suggested). I think when going for "reprocess selected", one can click first "unconfirm all" and then "reprocess" when wanting to also update the metadata. wdyt?

**Comment by TheOneValen** [comment]
That sounds very good, keeps the workflow clean and predictable. :)
