### ISSUE TITLE
BUG: UI settings (user) only saves the last changed item

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#368]
It took me a bit to figure out, but I tried to
* increase the number of shown files
* set native PDF as default
* enable keyboard shortcuts (not knowing though what I can do with them :-) )
* put notes to the bottom

Took me 4 save clicks and refreshes :-)

**Comment by eikek** [comment]
Oh yes, this is a bug– I also noticed it but forgot to quickly because was in a hurry :)

**Comment by eikek** [comment]
keyboard shortcuts allow to to navigate in detail view using keys: ctrl-c for confirm/unconfirm, ctrl-./ctr-, for next previous item. this is when the edit menu is opened

**Comment by totti4ever** [comment]
> keyboard shortcuts allow to to navigate in detail view using keys: ctrl-c for confirm/unconfirm, ctrl-./ctr-, for next previous item. this is when the edit menu is opened

Are they supposed to work on Mac as well? I am on Chrome and it doesn't really do

**Comment by eikek** [comment]
Oh, I don't have a mac, so I have no clue :-/. It's using the keycode `17` which is supposed to be the control key

**Comment by totti4ever** [comment]
Uhm, interesting. Isn't there a function especially for ctrl? For JavaScript there is. How is the UI programmed?

Refering to this, it is a completely different code:
https://eastmanreference.com/complete-list-of-applescript-key-codes

**Comment by eikek** [comment]
Interesting… I created a separate ticket for this (#371). Ui is programmed using the "onkeyup" event (I think :-)) Then I use the keycode….
