### ISSUE TITLE
BUG: No uniqueness check for equipment (possibly more?)

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#370]
I now have work three times

**Comment by eikek** [comment]
Oh no, you can add duplicate equipments? Checks for orga/person/tag/folder seem to work.

**Comment by totti4ever** [comment]
![image](https://user-images.githubusercontent.com/49901208/96775838-67381080-13e8-11eb-91de-4eb8312fd04f.png)

**Comment by eikek** [comment]
Yes, I found it… :/ really sad, the unique constraint is missing.
