### ISSUE TITLE
No password reset link

### ISSUE THREAD

**Issue by maspiter** [eikek/docspell#376]
Just got it up and running on my QNAP NAS.

Would like to submit a feature request for a password reset link.

**Comment by eikek** [comment]
Ah, nice to know it works on a QNAP NAS! Yeah, this is still missing. The link could be sent via e-mail, but this then only works if a user has supplied an address (and possibly some smtp settings).

**Comment by totti4ever** [comment]
In case the admin still has access, it would maybe help, if at least the admin was able to (re)set the password of another user through API?
Right now, I guess, one has to do some nasty database editing to get the user back into his/hers account?

**Comment by eikek** [comment]
I was also thinking about this. There are already some admin routes (start re-index for example). I can move them all behind the same secret and add a password reset endpoint. Then an admin can reset passwords of all users (via curl, can provide a bash script for this).
