### ISSUE TITLE
opt/docspell-tools/consumedir.sh: No upload URLs given

### ISSUE THREAD

**Issue by maspiter** [eikek/docspell#380]
Hi

I'm trying to use the integration endpoint with the following entrypoint command but always get the error above:

/bin/sh -c /opt/docspell-tools/consumedir.sh --path /opt/docs -i --iheader Docspell-Integration:secret -m http://ip-to-host:7880/api/v1/open/integration/item -v

Any idea what could be the cause?

Also, does the script remove the files after uploading them?

I want to use it as a file share for scanned documents that should be removed.

**Comment by eikek** [comment]
I can't see anything wrong with the command, maybe some shell escaping/interpretation issue? Could you try putting everything after `/bin/sh -c` in quotes (I assume `/bin/sh` is bash?).

Why is it executed as an command to /bin/sh and not directly?

To delete uploaded files, just add `-d` to the mix (there is an option overview via `--help`).

**Comment by maspiter** [comment]
Wow, you rule, dude. That was it, been messing with quotes but could not get it right. Thanks!

**Comment by eikek** [comment]
You're welcome :-) (I'm closing it then)
