### ISSUE TITLE
Docspell 0.13: Problems behind reverse proxy

### ISSUE THREAD

**Issue by svenihoney** [eikek/docspell#383]
I am using traefik as the reverse proxy for my docker containers. With 0.12, docspell worked perfectly behind traefik.

In docspell.conf, the base_url is set to "https://dok.fritz.box", under which the login screen is found successfully. But after a successful login (message box is green below password), the login page is shown again. Additionally, I get 403 Forbidden errors in the log file.

If I access the same docspell instance via localhost:7880 (with base_url set accordingly), everything is working fine.

**Comment by Lucki** [comment]
Try deleting the cookie. That let me in.

**Comment by totti4ever** [comment]
I think, Idid that too, yes!
Plus, I am fine having the default (localhost) as base_url since 0.13

**Comment by svenihoney** [comment]
Deleting the cookie did the trick indeed. Thx!
