### ISSUE TITLE
Navigation during search

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#395]
Okay, some more observations for discussion :-)

---

1. When you do a fulltext search and then want to further narrow down the results, there is no way to adapt the keywords once in the left sidebar, is it? I've seen that there are the boxes for both, name search and text search, but they are empty.  
Maybe they should also be on top so the text filter can be directly seen when having one applied?

1. ~~Also I generally miss some button to reset all filters. Tried it a couple of times with hitting the logo, hoping it would just go to the beginning, i.e. show all - didn't work ;-)~~ found the reset icon...  
Still, having a reset icon when the sidebar is not open, would also be nice

1. When you ctrl+click an item, you can open it in a new tab - this doesn't work in multi-select mode. It would help a lot there, to have a short view on the item in order to decide whether to check or uncheck. As a work-around already now it's possible to use right-click.

1. Would be great to see how many results I do have, maybe just put in brackets behind *Result* in the sub-header?

1. I don't really get the visual idea behind this bar in search/filter mode  <br /><img src="https://user-images.githubusercontent.com/49901208/97310495-9543a780-1863-11eb-96d0-c67635a6e188.png" height=40 />  
It looks like a search bar to put text into and I also don't understand the need of the search button to the right. Aren't all filters applied directly?  
Finally, shouldn't the chevron/arrow to close the sidebar go to the left? At least it is opened from the right-hand side

**Comment by eikek** [comment]
1. Yes, this is currently inconvenient. There is a difficulty that I'm not sure currently how to present/resolve. There are two kinds of searches: a) full-text search only and b) the search menu that may include a full-text search. If only fulltext search is done (a), the results are taken as-is from the solr index, including the context information and the order as this reflects the relevance. So there is no grouping on month. The second mode (b) works differently: it will at first search the database and then narrow it down using the fulltext search by asking the index to only look into a subset of items. The second way will take *very* long, if the results are not first narrowed down using some property. The *Name* search in the search bar is working the same as the same named field. The contents are shared, so it doesn't matter where you fill it in.  
I could imagine to do the following: The server detects if only a fulltext search is filled when receiving a search-form and then delegates to the fulltext-only search. This then behaves as if the other endpoint had been called. But I personally dislike a bit this difference in behavior…. But then one could do a fulltext search and if wanting to narrow down using a field this submits the form again which will trigger the "normal" (b) kind of search. Not sure if I can explain what I mean :)
2. Yes, I'm open to change this whole searchbar/searchmenu thing! I'm not happy with it either, just didn't have a good idea yet.
3. Yes, true – the multi select mode "steals" the normal link functionality. This is a bit tricky to solve I think. The card itself is a link (an `a` tag). So it's not possible to put another link "into it" as content. But where can a second link to the detail be placed?
4. I don't know which *Result* header you mean? This can be done, though I'm not sure if it's worth the effort? For the db query it means to execute a `select count` which may be expensive. Aren't we usually looking for some specific document? What do you gain if you know how much results exactly the search found? 
5. This bar is just meant as a menu. The chevron is indeed strange and it's also visually not related to the search bar that is toggled by this! So I'm all open to improve this. I would really like to make it better looking and more intuitive… I'm not good at this kind of stuff… :/ The rest is just some action buttons. Filters are applied immediately, so the search button could be removed. Help in form of design ideas are welcome :)

**Comment by eikek** [comment]
![Selection_073](https://user-images.githubusercontent.com/701128/97496042-b04c0f80-1968-11eb-8ab9-10dc98368efc.png)

Tried to improve a little the menu/bar toggling for a first start.

**Comment by totti4ever** [comment]
Nice, maybe you could use the filter icon alternatively for the hidden state
<img src="https://user-images.githubusercontent.com/49901208/97529883-31c79000-19b1-11eb-82c9-f87522ea6a06.png" height=35 />

**Comment by eikek** [comment]
Sure, it would look like this then:
![Selection_011](https://user-images.githubusercontent.com/701128/97536999-59712500-19be-11eb-9221-5dd28bccf64d.png)

**Comment by totti4ever** [comment]
I think I like it more, because you see what you'll get.

**Comment by eikek** [comment]
Created separate issues for the remaining things.
