### ISSUE TITLE
FR: Show more tabs for attachments if space is available

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#396]
I guess, right now it is hard-coded set to 1 to meet mobile needs?
<img src="https://user-images.githubusercontent.com/49901208/97317703-5d406280-186b-11eb-96f7-4b32cf48856c.png" height=75 />

Any chance to make this dynamic or at least put it to user UI settings? I happen to oversee the `...` and I think, it'd be great to see more tabs on laptop/pc

**Comment by eikek** [comment]
Yes this is true, I once changed it to be able to use it from smaller devices. I think it is something for the ui settings.

To mitigate the inconvenience a little, you can change the attachment order by drag&drop in this list below the `...`. This allows to put the important document in the first position.

**Comment by eikek** [comment]
How would you implement this: say there are 4 files and 2 of them are shown in the tab menu. Then you select another one from the dropdown menu and "onclick" the currently visible or first one is replaced with the new content? This might feel strange …

**Comment by totti4ever** [comment]
> To mitigate the inconvenience a little, you can change the attachment order by drag&drop in this list below the `...`. This allows to put the important document in the first position.

good to know!


> How would you implement this: say there are 4 files and 2 of them are shown in the tab menu. Then you select another one from the dropdown menu and "onclick" the currently visible or first one is replaced with the new content? This might feel strange …

Best would be the way MUI proposes, I'd say: to have arrows to the left and the right; so you are rather moving the visible part of the tabs that exchanging tabs:
https://material-ui.com/components/tabs/#scrollable-tabs

No clue, how easy to use the MUI components in ELM, though. Maybe this component works: https://package.elm-lang.org/packages/achutkiran/material-components-elm/latest/Mwc.Tabs
