### ISSUE TITLE
BUG: PDF extension appears twice

### ISSUE THREAD

**Issue by totti4ever** [eikek/docspell#397]
<img src="https://user-images.githubusercontent.com/49901208/97317703-5d406280-186b-11eb-96f7-4b32cf48856c.png" height=75 style="clip: rect(0px,10px,10px,5px)" />

I think this comes from calling ocrmypdf with `infile` as sourcefile and `out-pdf` as temporary destination?

**Comment by eikek** [comment]
Correct, this is some laziness. I just append `.pdf` to whatever is the input file name. Before pdf->pdf conversion this was enough :-) 

Do you think to add some hint that this is a converted file? I'd like to know to distinguish it from the original file, but maybe it's just me…. maybe like `blabla_converted.pdf`?

**Comment by totti4ever** [comment]
I like that idea, too.

We just have to make sure, that if a file is not converted, because it already had been OCRed before, we don't touch it at all.

**Comment by eikek** [comment]
Just to clarify: currently, all files are converted. The pdfs that already have an ocr layer are only not ocr-ed again. But ocrmypdf (iiuc) creates a pdf/a from them (but not touching the ocr layer).

**Comment by totti4ever** [comment]
Hmm, good point - I'll check how the files differ when I send in an file which has been treated by ocrmypdf with exactly the same settings before!

**Comment by totti4ever** [comment]
Okay, you are right - so maybe all ocrmypdf files should be renamed to `original_name-converted.pdf` oder `original_name.converted.pdf`

I'd maybe prefer the latter one as it cannot be mixed up with any existing dash-logic in the filename

**Comment by svenihoney** [comment]
I slightly disagree:
1. If docspell is used, it is clear to anyone that input processing takes place, the processing queue is even exposed to the user.
2. In most of the cases the user doesn't care if the file is converted, unless the content stays the same

My proposal would be to make the suffix a configuration option, with no suffix as the default. Perhaps something like
```
docspell.joex {
  ...
  processing {
    processed-file-suffix = ".converted"
  }
  ...
}
```
or similar.

**Comment by eikek** [comment]
That is also fine to me! My thoughts were regarding downloading the files back to the filesystem. If both have the same name, you then have difficulties distinguishing them.

**Comment by eikek** [comment]
It is configurable, but the default is set to `converted`; it can be set to an empty string to use the same filename as the original.
