### ISSUE TITLE
Custom metadata fields

### ISSUE THREAD

**Issue by joekhoobyar** [eikek/docspell#41]

**Comment by eikek** [comment]
Thanks for your input @joekhoobyar. Would you mind to elaborate a little on what you have in mind? 

My initial thought was, that custom dynamic fields including type information and special search/ui handling per type is really hard to include. But maybe your use case allows for other solutions? For example, it may be possible to add more fields statically. Then it would be interesting to know which fields you think should be included.

Currently there is only the "tag" meant to be a custom metadata field (which is of course not much).

**Comment by joekhoobyar** [comment]
It completely makes sense to first go with an "MVP" that begins with support statically added fields.

Basically, I am looking to be able to use something more lightweight than *Mayan EDMS*, which has support custom fields (configured per "document type"), and also has support for storing document "blobs" in the filesystem instead of the database.

However, the support that *docspell* has for automatically modifying metadata fields based on content from OCR scans is very compelling.   *Mayan EDMS* lacks even this basic capability.  I had to write a microservice to integrate with Mayan even to achieve basic automatic classification of my documents - but at least I can apply any "classification" to the fields of my choosing.

**Comment by eikek** [comment]
I need to install Mayan again, to see this feature about custom fields
per document type. I tried Mayan EDMS, too some time back and I also
found it too much for what I need. And I can't quite remember this.

Document cassification is something I also want to implement. I'm
still thinking about how to integrate it, maybe it would be possible
to use some AI learning algorithm….

Currently the idea is to use tags for classification, sadly manually
right now. That is why a tag can have a category. With basic
classification, do you mean to use text based rules, like regex or
substring checks to automatically associate a tag?

**Comment by joekhoobyar** [comment]
Yes, I have a very basic microservice that I wrote (in Ruby) to do "chains" of text based classification, matching against OCR and existing metadata.  Each "classifier" in the chain applies additional metadata as it matches, and each subsequent "classifier" can match against that additional metadata as well.  It gives me a very cheap way to conditionally apply additional classifications after earlier ones match.

**Comment by eikek** [comment]
Ah, I see. That sounds interesting, thank you for sharing! It seems to me that this would be too specific to be a part of docspell like being configurable in the ui, while I think I will add simple text based rules to auto-add tags one day. 

But docspell should be open and welcoming to write these things you mentioned and integrate custom workflows and tools. Maybe executing custom scripts during processing or calling an external service would be an option? If there was an CLI tool to update metadata a script could be handed all necessary data and then do its customized processing.

**Comment by joekhoobyar** [comment]
Yes, it would be great if simple integrations like that were doable.

**Comment by JaCoB1123** [comment]
I have a similar requirement for custom metadata:
I use an auto-incrementing stamp to assign each incoming document a number and until recently used that number as the filename and ordered my paper-documents by that number. So if I need some document in paper form I search my files and can lookup the original file by using the number.
I'd be ok assigning that number manually, though an automatic assignment would be nice to have.

**Comment by eikek** [comment]
Thanks for you input @JaCoB1123 – the next topic I'm going to work on is exactly this: custom fields.
