### ISSUE TITLE
AttachmentTabMenu: Display documents in tabs if space pemits

### ISSUE THREAD

**Issue by svenihoney** [eikek/docspell#422]
### Current situation
If there are multiple documents attached to an item, the items are displayed in the following way:
* The currently selected item is displayed in a tab view, tab title is the document name
* The additional items are selectable in a dropdown menu indicated by 3 dots

### Expected/Wished for
* All documents are displayed on a tab for each document. No dropdown menu is displayed
* If the space does not permit a display of all documents as tabs, add the dropdown menu or allow the tabstrip to be moved

### Steps to reproduce
* Add an item to docspell
* Add a second item: The items are selectable only by dropdown

**Comment by eikek** [comment]
Thank you for reporting! I'm just wondering if #396 already covers this?

**Comment by svenihoney** [comment]
Dammi, should have been looking closer again ;-)

**Comment by eikek** [comment]
No worries :-)
