### ISSUE TITLE
Customize title and subtitle of the item card

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#429]
Following from #327 , the item name property may not be used at all if the only use case is scanned documents. Then the name is almost always something like "scanned document 3.pdf", which doesn't add any value.

So first, allow to hide the item name like other fields. Then the titlte of a card can be filled with some other value – since this is hard to guess for all users, make it configurable. Then one can select the correspondent, or something else to show as the title of a card.

**Comment by totti4ever** [comment]
Sounds great, just want to add that I still try to give most of my documents a readable name as this still helps when scrolling through results. It might be the same as looking at category plus month(created-date), but it is just better readable if it's put together in big letters :-)

**Comment by eikek** [comment]
Yes, I'm doing it too. Not all names, but I curate most of them. I don't want to change the default. Your idea using something like a pattern for the title, sounds nice! So a user could say `${correspondent}-${date}` or something… Have to think about it :-)

**Comment by vanto** [comment]
This sounds useful to me, too. I'm also struggling with the item name, especially because it is so prominently placed and category, tags and correspondents are almost invisible compared to the title. I like the idea with templating the card title while maintaining the filename as Metadata. Perhaps also the other information items can be made more visible, more balanced.

**Comment by eikek** [comment]
Thanks for your input, @vanto . I'm very open for suggestions to make the ui better. I always feel quite limited in ui things, I very much rely on the css framework (which is great luckily). Do you have something concrete in mind with 'more visible, more balanced'?

I was going to make the item title a template. But then I felt that this is like a half way. The other fields still exist, so would it be good to have the correspondent in the card title *and* again below it? These thoughts have hold me back a while. But last time I was going to start with templating the card title and see what else can be done from there. I think this provides something good already, what do you (and others) think?
