### ISSUE TITLE
FR: Add a "Remember my login" function

### ISSUE THREAD

**Issue by svenihoney** [eikek/docspell#435]
Entering the password every time docspell is opened is cumbersome. A functionality to remember the successful logon would make the login process much more pleasant if used multiple times throughout the day.

**Comment by eikek** [comment]
Yes true! Would be nice to decide this per session. As a current workaround when using it at home, you could set the session time to some high value in the config file of the restserver, like `docspell.server.auth.session-valid = 7 days` for example (it is set to `5 minutes` by default). Then *all* sessions are valid for this period (the user can't decide this currently).

**Comment by totti4ever** [comment]
it took me quite a while to figure this out and I was quite annoyed!
Maybe you could think of setting it to 60 minutes or at least 15 minutes?

**Comment by eikek** [comment]
You mean the default session time? I could set it to 15min. But if the browser is open, then the client should ask for a new token every 4 minutes (or so) and so never timeout. It's only if you close the browser, no?
