### ISSUE TITLE
New project name?

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#450]
There was a [helpful hint on reddit](https://www.reddit.com/r/coolgithubprojects/comments/jus3zp/i_created_docspell_for_organizing_documents_with/gcffnlw/?utm_source=reddit&utm_medium=web2x&context=3) that the project name is not very good. 

I'm open to change it. My initial idea with that name is a mix of "document and spell", with "spell" in the sense of magic/allure – but this doesn't get across really.

As changing the name is quite some effort, I thought to collect some names here (just thumb-up/down on existing ones).

Some things:
- would be nice if it allows a _cheap_ domain :-) I guess it can be workarounded using some prefix, like `get-something.org` etc
- I don't want to create a new logo, so the new name should also start with the letter `d`, except someone else takes care of the logo :)

**Comment by eikek** [comment]
A [suggestions from a reddit user](https://www.reddit.com/r/coolgithubprojects/comments/jus3zp/i_created_docspell_for_organizing_documents_with/gcfwmi6/?utm_source=reddit&utm_medium=web2x&context=3):

> *Do*cument organi*zer* = dozer?

**Comment by eikek** [comment]
Also adding the current name for completeness :) "docspell"

**Comment by totti4ever** [comment]
DocSafe


Do*zer* is hip, but I'd say Docspell is not too bad, at least you can pronounce it without a problem and it is distinct (compared to all paperless projects ;-) )

_discarded by me (if liked by someone feel free to post):_
* _DocArc(hive)_
* _Document Cabinet_
* _Document Lake_

**Comment by totti4ever** [comment]
DigiDoc

to have something not starting with document ;-)

**Comment by eikek** [comment]
Thanks @totti4ever  for your proposals. I think, however, that I'm not going about this right now. It is much work and I'm not too much against the current name :-) (and there aren't many votes here;)).  I think this time is better spent elsewhere. But we can reopen this at a later point.
