### ISSUE TITLE
Supporting more document languages

### ISSUE THREAD

**Issue by Daedren** [eikek/docspell#461]
Hello! I see in the collective profile's settings that the document language can only be German, English or French

Is there a way to add more languages to be parsed?
I personally am looking for Portuguese.

**Comment by eikek** [comment]
Hi @Daedren , 

I would like to support more languages. I'm using the [StanfordNLP](https://nlp.stanford.edu/software/) library that provides all the AI magic used here. For the NLP part (detecting correspondents and such), it relies on previously build models that are provided by StanfordNLP library for various languages. Unfortunately, [there](https://stanfordnlp.github.io/CoreNLP/human-languages.html) are none for Portuguese… however, there is a third-party one [here](http://lxcenter.di.fc.ul.pt/tools/en/LXParserEN.html) – but I don't know if it is updated to run with the latest version of this library.

It would be possible to add more languages for text-extraction only, as tesseract has a wide support for this. But you then loose the "nice" functions from docspell (imho).

**Comment by Daedren** [comment]
Ah, no problem then.
I've stuck with French and it works close enough for now.

Thanks for the help.

**Comment by eikek** [comment]
It just came to my mind, that you could (as a workaround) actually hard code the language used for text extraction in the config file for the external commands. You could change the ocrmypdf and tesseract command to always use some specific language by replacing the `{{lang}}` pattern with your language. Obviously this applies then to all users and all documents, so if you are the only user that might be ok :-)
