### ISSUE TITLE
Support for more document languages

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#488]
Languages are currently english, german and french. This is what is supported by stanford-nlp. But other languages good be added easily without the nlp support. For these a fallback could be provided, then adding more languages is not hard. Maybe get rid of NLP alltogether.

See: #461

**Comment by mrtnggnn** [comment]
Docspell 0.17.1 installed with the docker-compose method seems not to have the french language installed for tesseract.
French is the default language for my collective.
```
2020-12-31T17:03:10: ocrmypdf stderr: ERROR - The installed version of tesseract does not have language data for the following requested languages: fra
2020-12-31T17:03:10: PDF conversion failed: Command result=3. No output file found.. Go without PDF file
```

**Comment by eikek** [comment]
Thanks @mrtnggnn – this is missing indeed! I'll create a new issue from your comment to fix this bug in the docker file.

**Comment by eikek** [comment]
Next release will include the following languages for document processing: Spanish, Italian, Portuguese, Czech, Dutch, Danish, Finnish, Norwegian, Swedish, Russian, Romanian

If you'd like others to be included, please let me know.

**Comment by maciekb** [comment]
Please consider to add Polish language processing support.

**Comment by eikek** [comment]
> Please consider to add Polish language processing support.

@maciekb  Yes, of course! Let's create a new issue #1345 for this, otherwise it gets lost too easily. Can I ping you for help, because unfortunately I don't know any Polish.
