### ISSUE TITLE
docker-compose with joex on different host

### ISSUE THREAD

**Issue by whysthatso** [eikek/docspell#516]
Considering that joex is the most intensive compute part, i was wondering what are the required configuration changes on docspell and docker-compose config in order to outsource the joex component to a different more powerful host. i'would run the solr instance and the rest server on a rather low-end device, like a pi, but would do ocr on a more high-end device in another location.

any thoughts on that?

**Comment by eikek** [comment]
This is a good idea. Regarding docspell, you only need to start joex with a config that points to your desired database and solr. Usually only the host/ip addresses of the solr and database urls change then.

Regarding docker, I'm myself not very knowledgable. I think you can create a new docker-compose file containing only the joex part (removing all `depends on` lines). Then change the `.env` file (and `docspell.conf` for solr) to point joex to the other machine running solr and the database. If you run the provided docker-compose setup know, I think only the `DB_HOST` changes in the `.env` file and the `solr` hostname in the solr url – put in the ip address of the pi. You must expose the corresponding ports (5432 and 8983) on the pi so that it can receive connections from other machines. You can then remove the `docspell.restserver` block from the config file on the machine running joex only.

When you get it to work, I'd be interested to add it as a template to the docker setup.

**Comment by eikek** [comment]
Ah forgot a detail :) it is recommended to reach the joex machine from the pi. For this you need to change the `docspell.joex.base-url` to the url that can be used from the pi to reach the joex machine. Also the port (`7878`) must be exposed on the machine running joex. It works without it, but then joex only "wakes up" periodically to process jobs and will not receive requests from the webapp.

**Comment by eikek** [comment]
Hi @whysthatso can I help you in any way with this? Or can the issue be closed? If you found something interesting, maybe it could be included in the docs?

**Comment by whysthatso** [comment]
i will need a bit more time, but i'm still on it. you can close it for now, and i will reopen it in case i got anything to add.

**Comment by eikek** [comment]
Ah, no problem, take your time. I didn't know you were on it. This can just be left open then.

**Comment by whysthatso** [comment]
so i came around to implement that, and it also worked. however, due to $reasons, i've just moved the whole setup to the more powerful machine, so i got rid of the problem in the first place.

they main feedback i would like to give though is the readability of `docspell.conf`
it was not very straight forward what is responsible for which part between joex and smartserver, or rather: can i just rip apart the two declarations? base-url was not immediately obvious, as in: do i need to change it when i run all of this behind a proxy under a domain (hint: no)?

now looking back it seems straight forward, but in the beginning, a couple of comments would probably be helpful. 

this is what i used for smartserver:

```
docspell.server {
  base-url = "http://localhost:7880"
  bind {
    address = "0.0.0.0"
  }
  integration-endpoint {
    enabled = true
    http-header {
      enabled = true
      header-value = ${?DOCSPELL_HEADER_VALUE}
    }
  }
  full-text-search {
    enabled = true
    solr = {
      url = "http://solr:{{ service_port_docspell_solr }}/solr/docspell"
    }
  }
  backend {
    jdbc {
      url = "jdbc:"${DB_TYPE}"://"${DB_HOST}":"${DB_PORT}"/"${DB_NAME}
      user = ${DB_USER}
      password = ${DB_PASS}
    }
  }
}

docspell.joex {
  app-id = "joex-"${HOSTNAME}
  base-url = "http://host.that.runs.joex:{{ service_port_docspell_joex }}"
  bind {
    address = "0.0.0.0"
  }
  jdbc {
    url = "jdbc:"${DB_TYPE}"://"${DB_HOST}":"${DB_PORT}"/"${DB_NAME}
    user = ${DB_USER}
    password = ${DB_PASS}
  }
  full-text-search {
    enabled = true
    solr = {
      url = "http://host.that.runs.solr:{{ service_port_docspell_solr }}/solr/docspell"
    }
  }
  scheduler {
    pool-size = 1
  }
}

```
and this is what i used for joex:

```
docspell.server {
  base-url = "http://localhost:7880"
  bind {
    address = "0.0.0.0"
  }
  integration-endpoint {
    enabled = true
    http-header {
      enabled = true
      header-value = ${?DOCSPELL_HEADER_VALUE}
    }
  }
  full-text-search {
    enabled = true
    solr = {
      url = "http://solr:{{ service_port_docspell_solr }}/solr/docspell"
    }
  }
  backend {
    jdbc {
      url = "jdbc:"${DB_TYPE}"://"${DB_HOST}":"${DB_PORT}"/"${DB_NAME}
      user = ${DB_USER}
      password = ${DB_PASS}
    }
  }
}

docspell.joex {
  app-id = "joex-"${HOSTNAME}
  base-url = "http://host.that.runs.joex:{{ service_port_docspell_joex }}"
  bind {
    address = "0.0.0.0"
  }
  jdbc {
    url = "jdbc:"${DB_TYPE}"://"${DB_HOST}":"${DB_PORT}"/"${DB_NAME}
    user = ${DB_USER}
    password = ${DB_PASS}
  }
  full-text-search {
    enabled = true
    solr = {
      url = "http://host.that.runs.solr:{{ service_port_docspell_solr }}/solr/docspell"
    }
  }
  scheduler {
    pool-size = 1
  }
}

```

**Comment by whysthatso** [comment]
i leave this here for reference, also the double curly braces are variable expansions for jinja2 templates / ansible automation, so don't get confused :)

**Comment by eikek** [comment]
Thank you for your insights @whysthatso ! There is some documentation about the config file [here](https://docspell.org/docs/configure/) – I think this link can be added to the default docker config file for a better starting point. This site lists all default options with comments and has also some notes on specific (more important) settings. 

Yes, you can use two separate files for joex and the server, both have separate namespaces (`docspell.server` and `docspell.joex`) for their config values.
