### ISSUE TITLE
Scan Mailbox Task: the mailbox entry resets to the first in list

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#524]
- I have two mailboxes configured in: "_E-Mail Settings (Imap)_"
- When I create a "_Scan Mailbox Task_" I can choose between those two mailboxes and everything is just working fine with both mailboxes (start once button and cron)
- BUT when I choose the second mailbox I have the problem that in the edit mode the mailbox entry allways resets to the first existing mailbox available in "_E-Mail Settings (Imap)_".
When changing something like a filter I MUST take care to properly set the mailbox _again_ to the correct value (from mailbox 1 to mailbox 2).

I tried to delete all settings an recreate them, changing names and setting. But this problem is reproducible.
I'm using docspell on ann unraid server with docker

**Comment by eikek** [comment]
Thanks for reporting! This is clearly a bug in the ui.
