### ISSUE TITLE
FR: Toggle between tile and list view

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#526]
A little feature request:
Sometimes it would be useful to be able to toggle between a **tile view** and a **list view**.
This should not only be an option in the users profile settings but on every page where documents are listed.
In the list view perhaps with more details if clicked on the item or with a mouse over effect...

**Comment by eikek** [comment]
Yes, good idea! There is no list view currently and there is only one page where items are listed. Maybe the card can be rendered when clicking on the row.

**Comment by JuneTwooo** [comment]
Good idea, especially when there is a lot of paper from the same tag / correspondent
