### ISSUE TITLE
Idea: Relationship (link) between documents

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#528]
Imaging you have two or more documents that have different tags, same or different correspondents and same or different  concerning people.
Document 1: a real estate exposé (from a real estate agent)
Document 2: a finance confirmation (from a bank)
Document 3: a cost estimate (from a craftsman)
All these documents can have the same but also different tags, correspondents and/or concerning people.
These documents could be "virtually" merged by a relationship (link documents to each other)

**Comment by eikek** [comment]
I also thought about this. For the use case you mentioned, I currently use a custom field like "order number" or "reference" or "topic" and assign the same value to all.  You could also use a separate tag just to combine these documents, like "dossier-x".

But maybe this can be provided "natively"? Then one could imagine other possible types of relationships, for example "reply-to", when one document is a reply to another. I don't want to add too much builtin relationships, not sure right now what is good and what is too much. Currently I try to solve this with existing things. But if that is not good enough, I'm open to new ideas!

**Comment by vakilando** [comment]
I'm not using the custom fields at the moment.....perhaps I should....
I saw this relationship-thing when testing nuxeo and liked it because you can directly switch to related documents because they are shown as clickable links.
Perhaps an automatic suggestion for linking documents to each other is possible when enough attributes (custom field, tags, concerned, correspondent, ...) are the same?
Your "reply-to" idea is good and could be achieved in the mail function: "Recipient(s)" could be a dropdown prefilled with existing e-mail addresses of concerned/correspondent of this document.

**Comment by vakilando** [comment]
I'm not using the custom fields at the moment.....perhaps I should....
I saw this relationship-thing when testing nuxeo and liked it because you can directly switch to related documents because they are shown as clickable links.
Perhaps an automatic suggestion for linking documents to each other is possible when enough attributes (custom field, tags, concerned, correspondent, ...) are the same?
Your "reply-to" idea is good and could be achieved in the mail function: "Recipient(s)" could be a dropdown prefilled with existing e-mail addresses of concerned/correspondent of this document.

**Comment by eikek** [comment]
I didn't know nuxeo, thanks for this hint! I couldn't find something to download and test, but I only had a quick look. Going to search more in the next days and have a look at this feature.

Not sure about the automatic suggestions. The first comment is about documents with different such properties. When documents have same correspondents/concerning etc, it is already possible to quite quickly find these (not with one click, though).

The recipient suggestion in the email form is a good idea! But in my case I usually send documents to external people… I use it more as a sharing function. But I can see that the correspondents email is a good suggestionk

**Comment by vakilando** [comment]
> I saw this relationship-thing when testing nuxeo and liked it because you can directly switch to related documents because they are shown as clickable links.

I just discovered that Teedy also has the possibility to add relationships (documant>edit>more metadata>relationships)
You begin typing the name of a document and Teedy suggests matching documents.

**Comment by vakilando** [comment]
sorry, closed it by mistake....

**Comment by eikek** [comment]
Ah thanks! I didn't realize that you can click on the title "additional metadata". Ok, I see what you mean now. It's just some general relationship, where semantics left to the user. That would be fine to add for me. Maybe we could add labels like "relates-to" and "in-reply-to" to indicate the type of relationship…, but maybe this is already too much.

**Comment by vakilando** [comment]
yes I think additional labels are too much. Since the user links the documents manually, he should know why or add an note to the document...
