### ISSUE TITLE
Trim whitespaces

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#539]
Hi eikek,
It's me again running into a little inconvenience :)
If i create new Organization or Person i usually copy the information from the document's OCR.
It happens quite often, that i select surrounding white spaces around Name, street, etc. Sometimes i also have multiple white spaces in a name (i.e. Organization[SPACE][SPACE][SPACE]ABC). Can we trim white spaces and remove mutltiple spaces between words? 
Cheers 
eresturo

**Comment by eikek** [comment]
Yes, good idea! I'm not sure whether I want it happen on the server or client, but that's a detail :-)
