### ISSUE TITLE
Scroll search menu and results independently

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#541]
Hi,
I often have that I enter something in the search relatively far down, which leads to only a few results, then I have to scroll up again and again to see the result. Could not this be made scrollable independently?
Sheers
Eresturo

**Comment by eikek** [comment]
I see what my bounded css skills can do here :). I'm not sure how that would look like – it migh be ugly when there are two scrollbars, no?

PS: Thanks for all your suggestions!
