### ISSUE TITLE
Introduction: A script to scan from ADF, preprocesses it and uploads it to Docspell

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#556]
This script scans from the ADF (Automatic Document Feeder), preprocesses it and uploads it to Docspell: 
[scanadf2docspell](https://github.com/eresturo/scanadf2docspell)

![overview](https://github.com/eresturo/scanadf2docspell/raw/main/overview.png)

I don't know if this is helpful to other Docspell users, but feel free to link to it in the Docspell documentation.

Any suggestions or missing features?

Sheers eresturo

**Comment by eikek** [comment]
Thank you @eresturo ! That looks great; some scanners can do this already, but others can't – it is nice to have then an easy way to create sensible pdfs. I'll add a link in the docspell docs.

**Comment by eikek** [comment]
Hi, I added this to the now existing "blog" on the website : https://docspell.org/blog/scan-and-process-from-adf/ I hope that is ok, please let me know otherwise!

**Comment by eresturo** [comment]
Hi eikek, thanks! Proud to wrote the first blog post ever ;)

Bzw, I close this issue now, because I think the script is introduced now.
