### ISSUE TITLE
A click on a category in the search menu always has the result 0 items

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#568]
When I click on a category in the search menu that definitely has items (the bubble behind the category name also shows the number of items) the result shown is always 0 items after the click (the bubble behind the category name then also shows 0 items).
Before the click:
![1](https://user-images.githubusercontent.com/36138919/104763664-8be12180-5766-11eb-922f-e7ef8091d58e.png)
After the click:
![2](https://user-images.githubusercontent.com/36138919/104763680-926f9900-5766-11eb-8f7b-d014bd692d81.png)

Docspell version 18.0 running on Unraid

**Comment by eikek** [comment]
Hi @vakilando , thanks for reporting!

Oh noes… I'm just guessing right now, have to verify and test it first. But I would bet it is a case problem. Could you try to rename `Dokumententyp` to `dokumententyp` and try again?

**Comment by vakilando** [comment]
well, how do I edit a category?? I can edit tags, but not categories...
But you are right for v0.18.0: categories that are only lower case are working.

I have another Docspell v0.17.1 instance running as docker (but not unraid) and there it works well with `Dokumententyp` (no need to be lower case `dokumententyp`).
I will upgrade it to 0.18.0 and look if it still works.

**Comment by eikek** [comment]
Yeah right, editing categories is not really possible. You can choose another one per tag, but it's not possible in the ui to change the name of all. You could connect to the db and execute `update tag set category = lower(category);` to make them all lowercase. 

This is probably a regression, I wouldn't be surprised if it works in 0.17.1. Composing queries was almost rewritten in preparation for next features like the query parser.

**Comment by vakilando** [comment]
So, the upgrade from 0.17 to 0.18 broke the search for categories...?
I'll update the DB and will test again.

BUT I think:
- categories must be editable (Feature Request?!) 
- category names must be allowed to be upper case (Feature Request?!) 
- IF upper case is NOT possible: there must be a syntay checking when creating/editing categories. (but this would be the worst case... for me...)

**Comment by eikek** [comment]
> So, the upgrade from 0.17 to 0.18 broke the search for categories...?

Yes, I'm sorry. It breaks it in that they are now compared case sensitive, but with lowercased input. 


>     * categories must be editable (Feature Request?!)

Yes, I'd see this as an enhancement. It is a little related to #413 .


>     * category names must be allowed to be upper case (Feature Request?!)

Yes, and this is clearly a bug. For one, upper case was allowed before and then it just doesn't make any sense :-) The intention is that case doesn't matter, category "doctype", "Doctype" and "DocType" are all the same. In 0.17 they were all _different_ categories. But imho this is confusing. So my attempt was to make it case-insensitive, by which I unfortunately broke it :-/ Another thing is that I forgot to mention it in the changelogs, I missed this change. At least the fix is not hard to do. It will be fixed in the next release. Until then, maybe lower-casing them for now is a (sad) workaround. After the release I can give you a db command to make them capitalized again.

**Comment by eikek** [comment]
I have to correct myself from above. Just checked 0.17 - there comparison is done case-insensitive. So different cases in a category name were handled all the same when searching.

**Comment by vakilando** [comment]
Thank you for the fast response!
> Yes, I'm sorry. It breaks it in that they are now compared case sensitive, but with lowercased input.

For me it's not really that bad because I have not that many Documents, tags and categories yet.
But I suppose I'm not the only one using upper case category names.

> Yes, I'd see this as an enhancement. It is a little related to #413 .

Yes, but in my opinion even without nested tags categories should be editable.

I'm just having the idea, that instead of (infinitely many) nested tags and a tree structure for clickable navigation you could make a clickable tree structure of categories and associated tags like this:

- category_1
  - tag1
  - tag2
- category_2
  - tag3
  - tag4
 
Clicking on a category would show all documents that have tags of this category as result.
Clicking on a tag would show all documents with this tag as result. 

> The intention is that case doesn't matter, category "doctype", "Doctype" and "DocType" are all the same. In 0.17 they were all different categories. But imho this is confusing.

True ;-)

> Until then, maybe lower-casing them for now is a (sad) workaround. After the release I can give you a db command to make them capitalized again.

Yes & Yes, thank you

**Comment by eikek** [comment]
> Yes, but in my opinion even without nested tags categories should be editable.

You are right. I can implement it  without changing the underlying db model. If I would want to support this on the db side, it gets close to nested tags. But that's just one option. We can have a separate issue for this.


> I'm just having the idea, that instead of (infinitely many) nested tags and a tree structure for clickable navigation you could make a clickable tree structure of categories and associated tags like this:
> 
>     * category_1
>       
>       * tag1
>       * tag2
> 
>     * category_2
>       
>       * tag3
>       * tag4
> 
> 
> Clicking on a category would show all documents that have tags of this category as result.
> Clicking on a tag would show all documents with this tag as result.

We can create an issue for this. I'd be interested what others would prefer. I thought about this (a long while ago), but then went with the current view. A minor concern was that it takes additional horizontal space. The other thing is that then you don't see most used tags at the top, regardless of category. An advantage is that categories could be folded away. It wasn't a easy decision :) I'm open to change/add this as another option.

**Comment by nero82** [comment]
I don't think such a tree structure is necessary for me at the moment. Frequent tags can be found at the top, and rare tags can be filtered. But with a lot of tags, I can imagine that it can help to get an overview of the structure of the tags and categories.

**Comment by eikek** [comment]
Thanks for your input @nero82 , I agree, my own situation is like you described. I created a new issue – I kind of think currently, it might be better to go directly to the nested-tags issue. Then the view has to be revisited anyways.
