### ISSUE TITLE
Full text search breaks when Solr volume is recreated

### ISSUE THREAD

**Issue by tinkerdudeno1** [eikek/docspell#597]
First of all: This might be a very hypothetical issue so feel free to close it as out of scope or something. I stumpled upon this when trying to switch from docker volumes to "volumes" that are actually bind mounts (where you specify a host file system path and map it into a container counterpart). In the course of doing, I did some back and forth, removing volumes and containers and ended up with a non-functional full-text-search. When digging into this (i.e. starting off with a fresh install and changing one thing at a time until something breaks) I tracked it down to some sort of mismatch of the Solr volume data and the database volume data.
Steps to reproduce:
Fire up the docker-compose.yml as documented in the getting started guide. Then stop the stack, remove the Solr container and its volume and fire up the docker-compose again. Then, when you try the full text search, the Solr container will crash with an "unknown field" error, see below.
I found no way to fix this except for starting completely over again with an empty database and an empty Solr volume. If they are not initialized at the same time, full text search breaks.

Oh and like I said in the other issue: Love this project! It's got everything a modern web app should have: It's completely based on a REST API; it's got a responsive and modern GUI, and it's in Docker. All with just the right amount of features for organizing a paperless home.

So here's the log:

> docspell-restserver | [ioapp-compute-1] INFO  d.r.w.TemplateRoutes - Compiled template jar:file:/opt/docspell-restserver/lib/com.github.eikek.docspell-restserver-0.18.0.jar!/sw.js
docspell-restserver | [ioapp-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 GET /sw.js
docspell-restserver | [ioapp-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK
docspell-restserver | [docspell-restserver-3] INFO  d.r.r.ItemRoutes - Make index only summary: ItemFtsSearch(0,60,dr.)
docspell-solr | 2021-01-25 19:48:38.036 ERROR (qtp649769713-19) [   x:docspell] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: undefined field content
docspell-solr |         at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1325)
docspell-solr |         at org.apache.solr.schema.IndexSchema$SolrQueryAnalyzer.getWrappedAnalyzer(IndexSchema.java:473)
docspell-solr |         at org.apache.lucene.analysis.DelegatingAnalyzerWrapper$DelegatingReuseStrategy.getReusableComponents(DelegatingAnalyzerWrapper.java:86)
docspell-solr |         at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:192)
docspell-solr |         at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:262)
docspell-solr |         at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:534)
docspell-solr |         at org.apache.solr.parser.QueryParser.newFieldQuery(QueryParser.java:62)
docspell-solr |         at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:1109)
docspell-solr |         at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:832)
docspell-solr |         at org.apache.solr.parser.QueryParser.Term(QueryParser.java:421)
docspell-solr |         at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:278)
docspell-solr |         at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
docspell-solr |         at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:282)
docspell-solr |         at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
docspell-solr |         at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:131)
docspell-solr |         at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:270)
docspell-solr |         at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:49)
docspell-solr |         at org.apache.solr.search.QParser.getQuery(QParser.java:174)
docspell-solr |         at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:162)
docspell-solr |         at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:337)
docspell-solr |         at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:214)
docspell-solr |         at org.apache.solr.core.SolrCore.execute(SolrCore.java:2627)
docspell-solr |         at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:795)
docspell-solr |         at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:568)
docspell-solr |         at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:415)
docspell-solr |         at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:345)
docspell-solr |         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
docspell-solr |         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
docspell-solr |         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
docspell-solr |         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
docspell-solr |         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
docspell-solr |         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
docspell-solr |         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
docspell-solr |         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
docspell-solr |         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
docspell-solr |         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
docspell-solr |         at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177)
docspell-solr |         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
docspell-solr |         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
docspell-solr |         at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
docspell-solr |         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
docspell-solr |         at org.eclipse.jetty.server.Server.handle(Server.java:500)
docspell-solr |         at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
docspell-solr |         at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
docspell-solr |         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
docspell-solr |         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
docspell-solr |         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
docspell-solr |         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
docspell-solr |         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
docspell-solr |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
docspell-solr |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
docspell-solr |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
docspell-solr |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
docspell-solr |         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
docspell-solr |         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
docspell-solr |         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
docspell-solr |         at java.base/java.lang.Thread.run(Unknown Source)
docspell-solr |
docspell-solr | 2021-01-25 19:48:38.037 INFO  (qtp649769713-19) [   x:docspell] o.a.s.c.S.Request [docspell]  webapp=/solr path=/query params={} status=400 QTime=16
docspell-solr | 2021-01-25 19:48:38.041 ERROR (qtp649769713-24) [   x:docspell] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: undefined field content
docspell-solr |         at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1325)
docspell-solr |         at org.apache.solr.schema.IndexSchema$SolrQueryAnalyzer.getWrappedAnalyzer(IndexSchema.java:473)
docspell-solr |         at org.apache.lucene.analysis.DelegatingAnalyzerWrapper$DelegatingReuseStrategy.getReusableComponents(DelegatingAnalyzerWrapper.java:86)
docspell-solr |         at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:192)
docspell-solr |         at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:262)
docspell-solr |         at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:534)
docspell-solr |         at org.apache.solr.parser.QueryParser.newFieldQuery(QueryParser.java:62)
docspell-solr |         at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:1109)
docspell-solr |         at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:832)
docspell-solr |         at org.apache.solr.parser.QueryParser.Term(QueryParser.java:421)
docspell-solr |         at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:278)
docspell-solr |         at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
docspell-solr |         at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:282)
docspell-solr |         at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)
docspell-solr |         at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:131)
docspell-solr |         at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:270)
docspell-solr |         at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:49)
docspell-solr |         at org.apache.solr.search.QParser.getQuery(QParser.java:174)
docspell-solr |         at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:162)
docspell-solr |         at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:337)
docspell-solr |         at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:214)
docspell-solr |         at org.apache.solr.core.SolrCore.execute(SolrCore.java:2627)
docspell-solr |         at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:795)
docspell-solr |         at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:568)
docspell-solr |         at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:415)
docspell-solr |         at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:345)
docspell-solr |         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
docspell-solr |         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
docspell-solr |         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
docspell-solr |         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
docspell-solr |         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
docspell-solr |         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
docspell-solr |         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
docspell-solr |         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
docspell-solr |         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
docspell-solr |         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
docspell-solr |         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
docspell-solr |         at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177)
docspell-solr |         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
docspell-solr |         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
docspell-solr |         at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
docspell-solr |         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
docspell-solr |         at org.eclipse.jetty.server.Server.handle(Server.java:500)
docspell-solr |         at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
docspell-solr |         at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
docspell-solr |         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
docspell-solr |         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
docspell-solr |         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
docspell-solr |         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
docspell-solr |         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
docspell-solr |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
docspell-solr |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
docspell-solr |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
docspell-solr |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
docspell-solr |         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
docspell-solr |         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
docspell-solr |         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
docspell-solr |         at java.base/java.lang.Thread.run(Unknown Source)
docspell-solr |
docspell-solr | 2021-01-25 19:48:38.041 INFO  (qtp649769713-24) [   x:docspell] o.a.s.c.S.Request [docspell]  webapp=/solr path=/query params={} status=400 QTime=20
docspell-restserver | [docspell-restserver-blocking-3] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchStats
docspell-restserver | [docspell-restserver-blocking-3] INFO  o.h.s.m.Logger - service raised an error: class org.http4s.client.UnexpectedStatus
docspell-restserver | [docspell-restserver-blocking-3] ERROR o.h.s.service-errors - Error servicing request: POST /api/v1/sec/item/searchStats from 172.22.0.1
docspell-restserver | org.http4s.client.UnexpectedStatus: unexpected HTTP status: 400 Bad Request
docspell-restserver | [docspell-restserver-blocking-3] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchWithTags
docspell-restserver | [docspell-restserver-blocking-3] INFO  o.h.s.m.Logger - service raised an error: class org.http4s.client.UnexpectedStatus
docspell-restserver | [docspell-restserver-blocking-3] ERROR o.h.s.service-errors - Error servicing request: POST /api/v1/sec/item/searchWithTags from 172.22.0.1

**Comment by eikek** [comment]
Hi @tinkerdudeno1 , you stumbled upon something that is simply not supported currently :)

The situation is like this, if I understood correctly: you started up the first time with solr. It works as expected. Then docspell is shut down, the solr volume/container is removed but the database is left as is. Then the app is started again. Now, solr will initialize itself anew, since it is an empty installation. Docspell runs on startup solr migration tasks and memorizes when it has done so. This is why it doesn't try it again on next startup, because it thinks it has already been run, not knowing that solr is a fresh installation. As I said, this could be improved. Maybe provide a startup argument or try to detect when this migration should be done. But I figured it is not a common case…. Anyhow, you have two options currently:

- Run a post request against `/api/v1/admin/fts/reIndexAll` and supply the "admin secret" (from the config file). It's not that easy to find, but there is some docs about it [here](https://docspell.org/docs/configure/#full-text-search-solr) and [here](https://docspell.org/docs/api/intro/#admin). This creates the schema at solr and then pushes all documents. This should fix your situation without restarting.
- empty the table `fts_migration` in the database and restart Docspell. It then thinks that migration haven't run yet and will run them again.

Hope this helps!

**Comment by tinkerdudeno1** [comment]
Ah I see, so that's how it works. I assumed it would be more standalone but as usual, things are more complicated than they appear.
Since I did started over from scratch, this issue is theoretical for me. I remember myself trying to "re-index all data" in the collective settings of the web GUI. This did not solve the issue. Is this addressing a different endpoint of the API than the one you mentioned? As a matter of fact, I did stumble upon the documentation you linked and also saw that endpoint but I thought I had triggered that already with the GUI... 
You are probably right with your original assumption: It's not at all common. I'm happy now knowing what was going on and how to solve it, if it pops up again. Again, feel free to close this issue, this is really nothing to worry about.
Thanks again!

**Comment by eikek** [comment]
> I assumed it would be more standalone but as usual, things are more complicated than they appear.

Yes, it would be nicer, if this would work automatically. The current way is not very convenient and also strange to store the schema state of solr in the sql database. I think this should be improved! I'll create a separate issue to not forget it (but it's not high on the list :-)).

> I remember myself trying to "re-index all data" in the collective settings of the web GUI. This did not solve the issue. Is this addressing a different endpoint of the API than the one you mentioned? As a matter of fact, I did stumble upon the documentation you linked and also saw that endpoint but I thought I had triggered that already with the GUI...

The reindexAll is different in that it applies to all collectives. The button in the settings only affect the current collective and it also doesn't re-create the schema. It is indeed a bit confusing. I already thought about removing this re-index task from the settings….

**Comment by eikek** [comment]
I'm closing this, you can reopen or create new issues any time.
