### ISSUE TITLE
improve error message for consumedir

### ISSUE THREAD

**Issue by whysthatso** [eikek/docspell#607]
i'm running consumedir.sh in docker, but on startup got the error:
/bin/sh: /opt/docspell-tools/consumedir/consumedir.sh: Permission denied

trying to troubleshoot that i _assumed_ this is a file system permission issue, since i basically bind another container's bind (scanservjs for scanning documents) into the docspell-consumedir container, and it seemed brittle. however, docker docs say that this is no problem, so i started the consumedir container on its own, and i could indeed access the bind volume and saw now scans appear. however, when i then executed consumedir.sh i got Permission denied. only then it dawned on me that it might be something else, and fair enough i hadn't set DOCSPELL_HEADER_VALUE, it was still set to none as in the original docker-compose. but that still didn't fix it.

what could this missing permission possibly be?

**Comment by sukram230799** [comment]
Thanks for reportimg the error. It was fixed in #601 and should no longer be a problem once the image is updated.

**Comment by eikek** [comment]
I just used the fix from #601 to push an updated image to dockerhub. It should now work again when using the LATEST tag.
