### ISSUE TITLE
edit category name (lower case to capitalized and change name)

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#611]
As mentioned in issues #568 I connected to the db and executed `update tag set category = lower(category);` to make all category names lowercase. That worked fine.
Now I'm struggling making them  capitalized again... 
Additionally I want to change the name of a category, just editing the name in the tag table didn't work.
Could you please help me?

**Comment by eikek** [comment]
You can now use this update:
```
update tag set category = initcap(category);
```

Renaming must be done similar:
```
update tag set category = 'Status' where category = 'State';
```

Note that both update all tags for all collectives.

**Comment by vakilando** [comment]
ok, thanks. it worked.
I had an old category `auto` that I renamed to `Fahrzeug`. 
Everything seems to be fine, but in table `classifier_model` in the column `name` I found the entry `tagcategory-auto`. Shouldn't this be `tagcategory-fahrzeug` or `tagcategory-Fahrzeug`?

**Comment by eikek** [comment]
Oh good point… this is exactly the problem when editing directly on the db…:-S 

We can rename it too, but it's not a big problem. Next time the classifier is trained, it will remove these entries. You can try this in the collective settings and start the "learn task" once. After it finishes, there are entries for all existing categories and those that don't exist anymore are gone. But until then, there are now no models for the "new" categories. So I would run this task now manually.

**Comment by vakilando** [comment]
Thank you, I started the "learn task" once and everything is fine now.
