### ISSUE TITLE
Confirm step for bulk operations

### ISSUE THREAD

**Issue by antifuchs** [eikek/docspell#613]
I just managed to rename all the items in my database to "2" because I mistook the "bulk-edit" form (with all items marked from a previous edit operation) for the "search" form, and tried to search for a file name starting in 2. Unfortunately, that applied the name change to all the marked files - everything in the DB.

I thankfully have a way to recover (backups! Woo!), but this seems very dangerous. Could the "bulk" operations on multiple marked items be made to have an "apply" button? I see there's an "unconfirm" button in the UI already, but it unfortunately doesn't help with recovering from this scenario.

**Comment by eikek** [comment]
I'm sorry that this happened to you! This is really a stupid thing. I thought that doing so many clicks to arrive in bulk-edit mode would be enough. I'm a bit hesitant to add an additional button. It would be different behavior compared to all the other forms. But I can see the use here, of course. Maybe it would suffice to make a much more prominent indication that currently "bulk-edit" mode is active? Would you think that this could have helped to avoid this?

The unconfirm/confirm buttons are for confirm/unconfirm multiple items.

**Comment by antifuchs** [comment]
> Would you think that this could have helped to avoid this?

It's a good question - in this case, it was purely a confusion about whether I was in the search or the edit form. One thing that I guess would be interesting might be a way for users to indicate that we'd want to change the given field: maybe have a checkbox next to them that enables the input field?

The other thing that would be really really neat is to be able to undo every "bulk" operation - that's probably really hard to do (especially going from "500 items have distinct names" to "they all have the same name"), but would have been super worth it in my case (:

**Comment by vakilando** [comment]
> backups! Woo!

Lucky guy having an (actual) backup!

> a checkbox next to them that enables the input field

nice idea (at least for "dangerous" fields)

Two thoughts I have:

- multi-edit Mode should have another background colour than the search to avoid confusion
(yellow or orange perhaps?)
- does it makes sense to edit the name in multi-edit mode? 
(it only makes sense if the use of placeholders/variables is possible, I think)

**Comment by eikek** [comment]
Great ideas, thank you both! I also thought about changing the background and provide a message to make it clear that one is now in "dangerousland". I like the idea to enable each field explicitly via a checkbox; I'll add these two things.
