### ISSUE TITLE
Option in `consumedir-entrypoint` not used

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#615]
The delete-option in the `consumedir-entrypoint` script is unused (https://github.com/eikek/docspell/blob/master/docker/consumedir-entrypoint.sh#L15)

Found by @highball-it ([gitter link](https://gitter.im/eikek/docspell?at=6016c0d1063b6c68d52cd8d0))

**Comment by highball-it** [comment]
There is a showUsage() function in this entrypoint script. I think it would be helpful to match the default options with the suggested ones in the help text. E.g. `CONSUMEDIR_DELETE=y` suggests that by default consumed files get deleted but it is now implemented as default not to.

**Comment by eikek** [comment]
Good point! It seems this function isn't called anywhere. So another option is to simply remove it. Or it can be just a comment and make it clearer, that these are only example options, via `CONSUMEDIR_DELETE=y|n` for example…? Since this is only a helper to call another script inside a docker container, I'm fine with removing this. A user doesn't interact with this script
