### ISSUE TITLE
Person is always added

### ISSUE THREAD

**Issue by JaCoB1123** [eikek/docspell#625]
Hi,

I've had one person added to all my incoming documents, although it has nothing todo with them.
The correspondent organization is usually guessed correctly. The person is recognized no matter which organization it is.
When editing afterwards I'm also being warned "The selected person doesn't belong to the selected organization." After removing it, I can't even add the person again.

Is there any way to fix this? Maybe to reset the correspondent person K.I. without resetting everything?

Thanks in advance.

**Comment by eikek** [comment]
Ah this looks like a bug: it should not suggest a person that is not part of a previously found organization. I might have just missed to implement this "detail" :). I currently can't think of a simple workaround, I guess I need to make code changes here.
