### ISSUE TITLE
mark several attachments of a document for deletion

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#626]
Sometimes imported mails that contain pictures get converted into several attachments.
Like this:
![Bildschirmfoto vom 2021-02-06 18-51-04](https://user-images.githubusercontent.com/36138919/107125874-9ea1ce80-68ac-11eb-9cf2-8a0399f28e8d.png)
As each of these attachments contain only one picture they are useless and I delete them and most of the time only one attachment (e.g. the pdf that was attached to the mail) is left.
Could there be the possibility to mark several attachments for deletion instead of deleting each separately?

**Comment by eikek** [comment]
I see, that are really many logos :). Maybe we can add a filter to skip images below a certain size (there is already one that skips images above some size).

Deleting many attachments is also fine, have to think about how to do the ui part.

**Comment by vakilando** [comment]
Adding a filter also is a nice idea. Could be configurable in the user or global options.
