### ISSUE TITLE
Search for documents without a folder

### ISSUE THREAD

**Issue by nero82** [eikek/docspell#628]
Hello,

I have just noticed that it is not possible to search for documents that are not in a folder. I noticed this when I was looking for a document that I had forgotten to assign to a folder.

So it would be nice if you could search for documents without a folder. It would be even better if you could search for documents that are not in a folder, as with the keywords.

For example, searching for documents with the keyword "business trip request" that are not in the "work" folder.

**Comment by eikek** [comment]
Yes I agree that this is useful. It seems a duplicate for #379 ?

**Comment by eikek** [comment]
Ah, just noticed a subtle difference. This is also asking to search for items not in a specific folder.

**Comment by nero82** [comment]
Should have searched the issues beforehand. And yes, it is an extension of #379.

**Comment by eikek** [comment]
Next version allows to do this via a query: `folder!=work` or `!exist:folder`.
