### ISSUE TITLE
Tag Category Colors settings disappear / are only available in one session

### ISSUE THREAD

**Issue by highball-it** [eikek/docspell#630]
I added some colors for my tags and after some time the settings diesappered. Now I checkd from two devices (PC/iPad) and on the iPad (Safari) colors and settings are still there/save but on PC (Firefox/Chrome) they are gone and the settings are no where to be found.

I'm a bit confused.

**Comment by eikek** [comment]
The settings are saved in the browser's local storage. It is currently not possible to store them on the server. Did you maybe set the colors not on both devices?

You can also check the settings in Chrome and Firefox: Open "Dev Tools" (it's sometimes on F12) and click the "Application" tab. There you'll see a "Local Storage" entry that should then show the settings data as JSON. If there is nothing, try to store some settings. They should appear then.

**Comment by vakilando** [comment]
hmmm, isn't it possible to store these settings in the database? That would be great!
I use more than one browser an and more than one computer......

**Comment by eikek** [comment]
It's possible, of course, only needs to be done :) There is this issue to track it: #565 

Some settings should be stored in the database (like colors maybe), but others are better stored at the device, when they are device dependent (maybe preview image size).

**Comment by highball-it** [comment]
Most of my browsers will be cleared after closing. So these settings get deleted all the time. Maybe these settings (for tags especally) should be collectionsettings?

**Comment by eikek** [comment]
I also let the browser clear everything when closing, but have exceptions for a few sites that I trust.

I think colors are very personal, so I'd associate them to a single user rather to all users of a collective?

**Comment by highball-it** [comment]
> I think colors are very personal, so I'd associate them to a single user rather to all users of a collective?

I don't know. I was thinking telling my wife to look for the red tags.

**Comment by eikek** [comment]
I see, hmm difficult decision.

**Comment by eresturo** [comment]
+1 for the collective setting in database

**Comment by eikek** [comment]
Hi @eresturo - not sure if I understand: the collective settings are in the database. The user profile stuff is not (like what colors for tags and how to render the pdf). I guess you mean the latter? The issue for this is #565 – it needs to be decided what to store in the browser and what in the db.

**Comment by eresturo** [comment]
What I want to say: +1 for moving text color settings to collective settings in database.

And for other browser settings: I use several browsers on several devices, so browser settings are never useful for me.

**Comment by eikek** [comment]
Thanks for the clarification @eresturo – I have to think about this user/collective settings stuff. Regarding browser: I think at least the "render pdf via browser or viewerjs" is only sensible to store in the browser.  I do allow the browser to store settings/cookies for a few sites. I kind of like it to have different settings for the phone and the "huge-screen" device. But yeah, if one as a lot of devices, it gets inconvenient.

**Comment by eikek** [comment]
I think the immediate issue here is fixed now with #565. The settings are still per user and not collective, though. I create a separate issue for having settings per collective, too.
