### ISSUE TITLE
FR: Correspondent Option "Not for suggestions"

### ISSUE THREAD

**Issue by eresturo** [eikek/docspell#659]
Hello,
I have the case with some corresponding contacts and organizations that I have a lot of documents, but definitely no new ones will be added. For example, the contact details of the bank whose account I canceled.

It would be handy here to have an option "Not for suggestions". So I could continue to have the documents sorted by it and search for them without getting wrong suggestions in the future. (E.g. confusion with my new bank).

What do you think about this?

Sheers
Eresturo

**Comment by eikek** [comment]
Yes, good idea! This should then apply to all this data.
