### ISSUE TITLE
Access issues from local clients on fresh docker install

### ISSUE THREAD

**Issue by kidfrostbite** [eikek/docspell#662]
Following the instructions for most basic  x86 docker install and then trying to access from another client on my LAN (that is, going to docspell.local:7880 instead of localhost:7880) I see the following in the logs:

docspell-restserver | [ioapp-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 403 Forbidden
docspell-restserver | [ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 GET /api/v1/sec/folder?q=
docspell-restserver | [ioapp-compute-3] INFO  o.h.s.m.Logger - HTTP/1.1 403 Forbidden
docspell-restserver | [ioapp-compute-2] INFO  o.h.s.m.Logger - HTTP/1.1 GET /api/v1/sec/tag?q=
docspell-restserver | [ioapp-compute-2] INFO  o.h.s.m.Logger - HTTP/1.1 403 Forbidden
docspell-restserver | [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 GET /api/v1/sec/tag?q=
docspell-restserver | [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 403 Forbidden
docspell-restserver | [ioapp-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 GET /api/v1/sec/tag?q=
docspell-restserver | [ioapp-compute-1] INFO  o.h.s.m.Logger - HTTP/1.1 403 Forbidden

And corresponding 403 errors in my browsers web tools.
After this I didn't see consistent behavior when creating an account (failed a few times, worked a few times) but even when account creation *seemed* to work login would fail with those credentials.

**Comment by eikek** [comment]
Hi, 

what is the config you are using (i.e. the base-url setting)? Is this the docker-compose setup from this repo?

The 403 are normal, if the page is first loaded. It tries to initialize, but due to the 403 redirection to the login page happens.

When creating an account worked, you should be redirected to the login page. If that didn't happen, something is not working as expected. Can you maybe let the dev-tools open when creating an account? There should be a POST request to the same url as in the address bar (or whatever base-url is set to).

**Comment by kidfrostbite** [comment]
I'm using the vanilla config - no changes at all to docspell.conf or .env. I do get the same batch of 403s on subsequent page reloads, fwiw.

I just tried again, this time making the collective name and user name the same and that worked! Seems like maybe a collective needs to created with a user of the same name to get started? I'll keep tinkering.

Is it safe to customize settings like DB credentials in .env?

**Comment by kidfrostbite** [comment]
OK, I think that was throwing me was that on my first pass with trying to create an account I tried to use my email address and that fails but also doesn't return an actionable message to the user. So after all of this maybe *that* is a bug. Thx for your help!

**Comment by eikek** [comment]
Oh yes, this is definitely a bug. I just tried it - it doesn't give any message. Really bad! It should say something informative. Sorry for this and thanks for telling!

**Comment by eikek** [comment]
Closing this now. Feel free to reopen or use new issues any time.
