### ISSUE TITLE
Please specify CONSUMEDIR_ENDPOINT

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#664]
After the update from v0.19 > v0.20 I realized that the consumedir container stopped working and the docker log only shows:

_Please specify CONSUMEDIR_ENDPOINT
Please specify CONSUMEDIR_ENDPOINT  
Please specify CONSUMEDIR_ENDPOINT  
Please specify CONSUMEDIR_ENDPOINT_

I have three docker containers on my Unraid Server: joex, restserver, consumedir (they start in this sequence).
I don't know when exactly the consumedir container stopped working but I used it before the update to docspell v0.20. But it may stopped working before the update 0.19>0.20.

The relevant config part in _docspell.conf_ should be:

_docspell.server {
  app-name = "Docspell"
  base-url = "https://blabla.my.domain.com"
  bind {  
    address = "0.0.0.0"
  }
  integration-endpoint {
    enabled = true
    ## The priority to use when submitting files through this endpoint.
    priority = "low"
    ## The name used for the item "source" property when uploaded
    ## through this endpoint.
    source-name = "integration"
    ## Requests are expected to supply some specific header when
    ## uploading files.
    http-header {
      enabled = true
      header-value = my-blabla-header-value
    }
  }_

My relevant Docker config for the consumedir container is:
![consumedir](https://user-images.githubusercontent.com/36138919/108887165-2bb58900-760a-11eb-9f9c-f2d285272dc0.png)

Can you tell my what's wrong?

**Comment by eikek** [comment]
Hi @vakilando , sorry for this. I assume this somehow relates to #603, but I'm not sure right now what exactly the problem here. A new entrypoint script is now used. You can use the consumedir-image of v0.19.0 for the time being until this is fixed.

**Comment by eikek** [comment]
Ah, maybe try setting `CONSUMEDIR_INTEGRATION=y` as an env variable. Do you use the provided `.env` file?

**Comment by vakilando** [comment]
> Ah, maybe try setting `CONSUMEDIR_INTEGRATION=y` as an env variable. Do you use the provided `.env` file?

yeah, setting this variable worked!

![consumedir_var](https://user-images.githubusercontent.com/36138919/108904177-7a6d1e00-761e-11eb-82e6-ec5e8fa4dd1b.png)

I'll update my repository at [https://github.com/vakilando/unraid-docker-templates](https://github.com/vakilando/unraid-docker-templates)

Thank you very much!
...and by the way...version v0.20 is great, like it very much!
