### ISSUE TITLE
Need some help to provide easier startup experience

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#675]
For context: #669 

Docspell is a very flexible tool on purpose. It should be possible to adopt to your workflow, hardware etc. As a result, installing can be difficult, due to choice/config paralysis and requiring basic know how about computers and networking.

My thoughts were that it would be enough to describe a simple "try it out" scenario, for example with docker-compose. Then if people run something else, they probably know better than I how to proceed. There are zip files to just unpack and run and deb files for installing on debian based distros. But obviously, this is only half the way – you need to configure it yourself.

It is quite difficult for me to know how people want to use it and what they expect. As an example, I'm using it like this:

- joex, restserver, postgres and solr run on a sbc ([this one](https://up-board.org/up/specifications/)) that has 4G RAM. It runs very well on this. This board much more powerful than the pi. There is nothing else running on this machine. It also runs on the pi, I tested it [here](https://github.com/docspell/rpi-scripts).
- the consumerdir runs on the NAS where the scanner puts its files, which then get into docspell
- then there are consumedir's running on all our laptops to be able to download files into some directory to get them easily into docspell
- I also added a shortcut to my mail client to upload mails with one key stroke
- when I was importing a lot of documents, I started more joex on the laptops to help with processing

I thought that this is probably a common setup. But it obviously requires some know-how in setting up and networking basics. But there are many other ways possible.

I want to ask for your help. Do the current docs help you? What would you like to see in the docs? What are your setups? What would you expect? What do you need to go forward?

For example, someone mentioned to put everything into one docker image – would this help someone? Another point is that I cannot actively support all kind of setups. So I was thinking about creating one or two simple ones – one idea was to create an image for the RPI that you could `dd` onto a flash card. But is this already too much "computer stuff"? Unfortunately, I'm not used to things like unraid, portainer, synology etc and I won't have the time to look into any of it. But I would try to support one or two such setups if someone could help me with this and explain it to me :-). Luckily there is already support by very nice people for instance for [unraid](https://github.com/vakilando/unraid-docker-templates) and as I just found out for arch (thanks luki!).

Any suggestions  and ideas to improve this are very welcome! I'll see what it takes and if I can provide this by myself given the limited time. Should other people want to offer help here, that'd great of course! Thanks!

**Comment by vakilando** [comment]
Ok, I'll do some brainstorming.... ;-)

More:

- I've updated my [unraid templates](https://github.com/vakilando/unraid-docker-templates) to be ready for version 0.20.0 
  (added variable CONSUMEDIR_INTEGRATION)

- I've added a third installation variant "br0 network".
So now it covers 
  - **br0** networking
  - **vlan** networking
  - **custom network**

**Comment by eikek** [comment]
Hi @vakilando, oh great – thank you a lot for all your efforts in unraid! If anything gets strange, I'm here or on gitter/matrix and glad to help out.

**Comment by tobru** [comment]
I've deployed Docspell in Kubernetes. If you (or someone else) is interested in how I've done it, here are all the YAML files in my GitOps repository: https://git.tbrnt.ch/tobru/gitops-tbrnt/src/branch/master/docspell (these are actually the live YAMLs).

Running Docspell in Kubernetes might not be that beginner friendly. One way to make it much more one-click getting started would be to provide a Cloudron app, which e.g. could be discussed here: https://forum.cloudron.io/topic/4152/docspell-document-management-system. 

And as a small hint: It would make deployment much easier and more best-practice to provide an image per component, rather than distinguish between them by using image tags. Docspell images could be made available in it's own Docker Hub organization and this organization could then asked to be marked as Open Source project: https://www.docker.com/community/open-source/application

**Comment by eikek** [comment]
Hi @tobru this is great, thank you! If you don't mind I could link to your yml files from the website? It's not a commitment to anything, just meant as some links to check out if other's come across this.

Thanks for the cloudron link; that would be nice of course. I have no clue how cloudron and its packaging works. I'm going to look at this thread from time to time.

Your third point is interesting, thanks for that hint! The current state is all due to my lack of experience wrt docker and k8s. I just thought tags are good enough to mark different images in a repository. From your words I conclude that a repository shouldn't contain multiple images–only multiple versions of an image? I'm going to check this organization thing on dockerhub, that doesn't seem like a lot to change to the naive me. If that helps, then great :). Created #687 for this.

**Comment by tobru** [comment]
> If you don't mind I could link to your yml files from the website?

I'd rather copy these files into a `contrib/` folder in this project, as my GitOps repository can change any time and the link can get outdated any time. Another thought I had is to create a Helm Chart for Docspell (Helm Chart are a way to package a deployment in way which makes it very easy to deploy applications to Kubernetes). Hopefully I find some time to do it.

> I have no clue how cloudron and its packaging works.

Cloudron is distributing Docker images for the applications. It isn't that hard (https://docs.cloudron.io/custom-apps/tutorial/) but of course it takes some time to get it done. Maybe someone from the Cloudron community will do it.

> From your words I conclude that a repository shouldn't contain multiple images–only multiple versions of an image?

Each application should be in its own Docker image. Tags are a way to version the image, not to distinguish between different applications. A Docker Hub repository should only contain one application.

If you need any help, just ping me on Matrix/Gitter. I'm happy to help :+1:

**Comment by eikek** [comment]
Hi @tobru thanks a lot for your reply. You're right, this repo reflects your complete system, this might not be a good idea to link to it. I'm a bit reluctant to add your files to this repo, because it's one more thing that I can't really maintain. The docker setup alone is quite enough already :-) 

Ok, got that with the tags now, thanks. I thought that "application" means "all that's to it", so it's more than one component for docspell and so I put them into one repo; and because I didn't wont to create multiple accounts (registering is so annoying…). I like your idea with the organization, then (I guess) I don't need to manage multiple accounts, but just one.

I'm going to ping you when I'm drowning in these deployment things :) Thanks!

**Comment by eikek** [comment]
I reworked the docker setup now and added more documentation for this, too, and added links to the unraid forum for example. Hope this helps. I'll close this now. If always: new issues for feedback are always welcome!
