### ISSUE TITLE
Add Latvian language

### ISSUE THREAD

**Issue by lord-lawnmower** [eikek/docspell#679]
Could the Latvian language be added for tesseract ocr - short code - lav

**Comment by eikek** [comment]
Yes sure!

Docspell has a date extractor that looks for month names of all languages to get dates like "23. september 2019" – would it be possible maybe for you to provide me these names? And while I'm at it :) maybe also what date format is most used, like `dd.mm.yyyy` or a different one? That would make it easier for me to add support for these patterns in latvian for date extraction. Thank you!

**Comment by lord-lawnmower** [comment]
These would be the month names:

English - Latvian - Latvian short (with the dot at the end)

January - Janvāris - janv.
February - Februāris - febr.
March - Marts
April - Aprīlis - apr.
May - Maijs
June - Jūnijs - jūn.
July - Jūlijs - jūl.
August - Augusts - aug.
September - Septembris - sept.
October - Oktobris - okt.
November - Novembris - nov.
December - Decembris - dec.

Regarding the date format, the most widely used short date format would be `dd.mm.yyyy` and long format `YYYY. [gada] D. MMMM` ('gada' means 'year' (in specific conjugation) and it is common to include it in full format for date in Latvia.)like this:

2020. gada 30. jūlijs
2020.gada 30.oktobris
2018. gada 10. maijs

https://www.localeplanet.com/icu/lv-LV/index.html

**Comment by eikek** [comment]
That's great! Thank you very much!
