### ISSUE TITLE
Content/OCR Search of all documents

### ISSUE THREAD

**Issue by LostSoulfly** [eikek/docspell#69]
It's great to have the tagging features, but what if I am looking for every document containing a string of characters in all documents? For example, what if I'm looking for all documents with an SSN on them?

This can be implemented in multiple ways. Indexing document contents when processing would be best but that would likely add a lot of extra data to the database. And I imagine it would certainly be complex to implement. A slower, perhaps easier, approach might be to search each document on demand. This could be sped up by filtering by certain tags or other criteria first.

**Comment by eikek** [comment]
Thanks for sharing your thoughts! I know the content search feature cannot be replaced by auto-tagging. Even if it is going further (which is my plan in the long run). For the SSN example I could imagine to be included in auto-tagging some day. But, of course, this will only make people want to search for something else :-).

Maybe it can be implemented as you said on a first step. The results are currently already limited to some fixed number (I think 100 or 200) – which is also something to improve. We could simply go through all and do a substring search in the extracted texts. For a better impl, I guess something like elasticsearch or solr is required to make it work in a distributed environment. This would complicate the setup with another component; while it may be possible to provide a simpler solution for deployments with one rest server.

**Comment by LostSoulfly** [comment]
Perhaps take a look at something like https://github.com/AnalogJ/lodestone
-- I haven't used it but it claims full text search and appears to use
elasticsearch. Additional components aren't a big issue when providing a
docker-compose for new users.

**Comment by eikek** [comment]
Thanks for the hint. I tried lodestone the other day, and I found it is really nice! It uses elasticsearch.

It's true that docker-compose can hide a lot of complexity, but only for those that use it. Others need to deal with it, too. An additional rather resource hungry component will make it harder to run on platforms like the pi. Otoh I think that something like elasticsearch or solr is the way to go when making a serious attempt on implementing this. Maybe one can provdie an embedded version for small setups….

**Comment by rklueber** [comment]
+1 for the full text search. With this the syste would be fullfilling my dreams to get rid of paper. Have you had a look into this "walk-through"?

https://blog.logrocket.com/full-text-search-with-node-js-and-elasticsearch-on-docker/

**Comment by eikek** [comment]
@rklueber thank you for the link.  At least I can say that fulltext search is now definitely on my list for the "next big thing" to work at :-). But it could take a while until there is something to show. The problem is not so much to start elasticsearch using docker, but more to efficiently integrate it into the application (how to query, what to store at the index, how to have both dbs in sync etc). I'm currently more in favor to use solr. It would also be possible to use postgres, but then docspell would require postgres and looses support for mariadb and h2. I also want it to work using the "download, unpack, run" model, i.e. without docker and also without postgres….

**Comment by eikek** [comment]
Now that 0.7.0 is out, I'll be working on adding fulltext search. I like the idea to make it optional.
