### ISSUE TITLE
Scan Mail - tasks names

### ISSUE THREAD

**Issue by voarsh2** [eikek/docspell#712]
I'd like to request names for tasks.

I might target the same email folder and want to process it differently and the only filtering I can see is the target folder, inbox and other small details.

If you have multiple tasks for processing complex inboxes, not showing more details about the task, or a name (visual cue), it's pretty time consuming to check what each task does each time.

**Comment by voarsh2** [comment]
Amazing, can't wait to test! 🎆
Is this on snapshot? Am I able to test pretty soon?

**Comment by eikek** [comment]
Yes, it's in current SNAPSHOT - you could test it there.  Just be aware, that it's not possible to go back to the LATEST version until this is released. (might want to backup the db)
