### ISSUE TITLE
How to upgrade to newest version?

### ISSUE THREAD

**Issue by TheNomad11** [eikek/docspell#715]
Hi again stupid questions from my side. As often I struggle with the documentation and cannot find answers to basic stuff that most people know already. So how can I update or upgrade to the newest version via docker?  Thanks a lot!

**Comment by eikek** [comment]
The docker images are at dockerhub and their tags define the version. Then there is a tag `LATEST` (case sensitive) which always points to the latest release. If you use it, then you only need to do an upgrade, without changing a file. How "to do an upgrade" depends on your machinery; these docker setups tend to get quite complex…. If you use docker-compose, I think you can do `docker-compose up --force-recreate --build -d` (caution, pasted it from some stackoverflow post…) – but if you're not using docker-compose, I have no idea.  Can you give more details about your setup? Maybe someone else can help out.

**Comment by TheNomad11** [comment]
I used the standard docker-compose setup as described here https://docspell.org/#get-started . After `docker-compose up --force-recreate --build -d` I am still on 0.20 How did you upgrade?

**Comment by eikek** [comment]
Well, I'm not using docker, so it's simpler for me I guess. Also, I'm not a docker expert :(

But, we should still get this solved! If you use the standard setup, then there is the LATEST tag used. So I think we are almost there. Maybe try to shut everything down first via `docker-compose down`, then pull explicitly via `docker-compose pull` and last try the command from above.

**Comment by TheNomad11** [comment]
Yes, now the upgrade worked and I am excited about the scroll bars!!! But at the same time everything was erased.  I was not able to login and had to sign up again (with the same user name and password). All docs were erased. So maybe one upgrade step was missing? Anyway, it does not matter so much as I am just testing Docspell and some other apps. 

So I thought Docker Compose was recommended as the easiest way to get started. Seems to be more complex, then. So how did you set up Docspell?  Maybe I should try your way?

**Comment by voarsh2** [comment]
Skim reading here.
You can use watchtower, or (make things super simple), as @eikek says, stop all containers, update the docker-compose file to a specific version you which to use, and docker-compose up -d and it'll recreate it.

**Comment by eikek** [comment]
> But at the same time everything was erased.

Oh what?? This is very surprising. The volumes should not get touched at all. I really have no idea how that could happened with these steps. I tried them on my machine without this outcome. Did you maybe removed/pruned something?


> So I thought Docker Compose was recommended as the easiest way to get started.

Yes, this is still true. It allows to start everything with one command to quickly try it out. After that, people tend to have very different setups and environments, I cannot help there really. Should you use keep using docker-compose, the above steps should work – or even better try out watchtower as @voarsh2 suggested, that sounds like what you want. All this is a bit out of scope of this project; but I'm trying to help as far as I can; maybe we can ping others for help.

And you're right: there is documentation missing to tell about how to upgrade – I will add that.


> So how did you set up Docspell? Maybe I should try your way?

Was a bit twinkling :) Not sure if my way is simpler for all; I'm using [nixos](https://nixos.org/) and the setup in the `/nix` folder.  I'm using this distro for a few years now (on all machines) and it is just great! But requires some learning curve to feel comfortable. Once that is overcome, you don't want to go back :-).

**Comment by voarsh2** [comment]
> > 
> 
> Oh what?? This is very surprising. The volumes should not get touched at all. I really have no idea how that could happened with these steps. I tried them on my machine without this outcome. Did you maybe removed/pruned something?
> 
> > So I thought Docker Compose was recommended as the easiest way to get started.
> 
> Yes, this is still true. It allows to start everything with one command to quickly try it out. After that, people tend to have very different setups and environments, I cannot help there really. Should you use keep using docker-compose, the above steps should work – or even better try out watchtower as @voarsh2 suggested, that sounds like what you want. All this is a bit out of scope of this project; but I'm trying to help as far as I can; maybe we can ping others for help.

Yes, I'm very surprised that content has been erased. I can only think that something is pruned, or a volume hasn't correctly setup. Hopefully you didn't have anything important in there yet.

I use docker a lot and I'd be happy to help you set it up outside this issue. Let me know.

**Comment by TheNomad11** [comment]
Thanks a lot @eikek and @voarsh2  . I will need to learn more about Docker first, it seems. Just learning by doing does not always work. Nothing important was there as I was only testing. I suppose the errors were on my end, so don't take this issue seriously. Will need some sleep now and have a look again tomorrow

**Comment by eikek** [comment]
Solved here: #718 !

Closing this now. Feel free to reopen or use new issues any time.
