### ISSUE TITLE
My (easy) way to install with docker-compose

### ISSUE THREAD

**Issue by papaloewe** [eikek/docspell#718]
There is absolutly no need to build the docspell container yourself, nor to git clone all files.
You just need a few files from eikek git repository.

This is my way tio install docspell:
Suggestion: You have a working docker environment with docker-compose installed.

`mkdir docspell
cd docspell
wget https://raw.githubusercontent.com/eikek/docspell/master/docker/docker-compose.yml
wget https://raw.githubusercontent.com/eikek/docspell/master/docker/docspell.conf
wget https://raw.githubusercontent.com/eikek/docspell/master/docker/.env

nano docspell.conf
(Put the IP-Adress here: base-url = "http://xxx.xxx.xxx.xxx:7880" )
nano .env
(for setting the secret an other options)
nano docker-compose.override.yml
(For own volume mappings)
docker-compose up -d`

To update:
`docker-compose down \
docker-compose pull \
docker-compose up -d`

**Comment by eikek** [comment]
Thank you! I'm just about to add the upgrade instructions. I'm copying your notes, too, if that's ok. I wasn't aware of the `docker-compose.override.yml`, thanks!

**Comment by papaloewe** [comment]
Sure, that's what I wrote there for.
the ovverride.yml is an elegant way to make your own customizations in the docker stack without touching the original file.

e.g. my docker-compose.override.yml looks like this now:
`version: '3.7'

services:
  consumedir:
    volumes:
      - importdocs:/opt/docs

volumes:
  docspell-postgres_data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.0.5,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/FreeNas/docker_vol1/docspell/postgres_data"
      
  docspell-solr_data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.0.5,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/FreeNas/docker_vol1/docspell/solr_data"

  importdocs:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.0.5,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/FreeNas/archiv/gescannt/output"`

**Comment by TheNomad11** [comment]
Great! Worked perfectly, thanks  @papaloewe I had to replace the IP with the domain name in docspell.conf, though
Email import worked flawlessly as well. thanks for your work, @eikek

**Comment by eikek** [comment]
I incorporated your steps into the documentation, the documentation about docker and docker-compose has just been rewritten (see [here](https://docspell.org/docs/install/docker/#docker-compose).
