### ISSUE TITLE
[Feature] export-files.sh - Tags as symlinks

### ISSUE THREAD

**Issue by TheOneValen** [eikek/docspell#725]
Hi!

I would like to propose that the export-files.sh script shall create a folder "tags" which contains all tags as folders. Maybe also ```tags/<category>/<tag>```.

Each tag folder contains all documents which have this tag as symbolic link to the file(s) which were exported via the script.

Maybe configurable via switch ```y/n```

If something in the direction of FUSE (#717) is in the works, I think the same approach might work there, too.

Greetings!

**Comment by eikek** [comment]
Hi! I like the idea, but I'm afraid, this is out of scope for this script. It is only meant to have a way to get the original files out of docspell. Later, I'd like to have a proper CLI tool (#345) which is the right place for this idea (there will be more options for downloading) But this might take a while until I can work on this :/.

**Comment by eikek** [comment]
HI @TheOneValen you can check out the new [cli tool](https://github.com/docspell/dsc), which has now this feature in its `export` command.
