### ISSUE TITLE
Better public upload page

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#758]
For sources, there exists an upload page that is public, if you know the link. This page currently is just a copy of the upload page as seen by logged in users. 

The public upload page should not allow to set any metadata, as that is defined by the user who created the source url.

**Comment by sanbroz** [comment]
Public upload page should show name, description & other metadata of source

**Comment by eikek** [comment]
Hi @sanbroz I'm afraid I have no idea what you mean :) - could you elaborate? Also if it's something new to do, you can just create a new issue. It's easier to track for me. Thanks!

**Comment by sanbroz** [comment]
I suggest to add (display only) name and description of source just above the upload box so that the person uploading has more clearly about the upload metadata.
