### ISSUE TITLE
version tag of 0.22.0 is mangled on docker hub

### ISSUE THREAD

**Issue by whysthatso** [eikek/docspell#765]
images are tagged with v.22.0 whereas i think it is expected to be v0.22.0

**Comment by eikek** [comment]
Ah yes, sorry. That's some bash script that's gone crazy :-) I'm going to push new tags in a minute. The images itself are ok, only the tag names are messed up.

**Comment by eikek** [comment]
Hi @whysthatso - just pushed the correct tags. Thanks for letting me know!
