### ISSUE TITLE
0.22:  Display bug? "0 documents" Tags disappeared

### ISSUE THREAD

**Issue by TheNomad11** [eikek/docspell#772]
After updating from 0.21 to 0.22 my tags in the side menu disappeared, but they are still there and are displayed in the document cards and in "Manage data". Maybe this is a display bug? On the front page it says "0 documents" although all the documents are still there.

**Comment by eikek** [comment]
Hi @TheNomad11 , this sounds like #759 . Do you have any tags that have no category? I'm sorry for this … you need to assign a category for now. It is fixed in the next release.

**Comment by TheNomad11** [comment]
That*s true. Thanks!

**Comment by vakilando** [comment]
same here after updating from 0.21 to 0.22. 
I had only two tags without category and the tags in the side menu behaved quite strange...
Assigned a dummy category. This post saved my day!
I think it can be closed?

**Comment by eikek** [comment]
Yes could be closed from my side. I was just about to hit that button when I thought it might be good to be not hidden away for others who run into it? Or well, I could just add it to the release notes… but at least *I* would first check the issues :-)

**Comment by eikek** [comment]
Fixed in 0.23.0
