### ISSUE TITLE
docspell icon

### ISSUE THREAD

**Issue by after99** [eikek/docspell#780]
have u [icon for homer](https://github.com/NX211/homer-icons)?

**Comment by eikek** [comment]
Hi @after99  that's great, didn't know about this repo! It happens that I'm using homer myself. I'm using this url currently:
"https://raw.githubusercontent.com/eikek/docspell/master/artwork/logo-96.png"

I can make a pr to the icons repo adding this image. I'm currently a bit under water, so it might take a while; but you can just grab and add it if you like.

**Comment by eikek** [comment]
Guess this can be closed, since your pr NX211/homer-icons#5 takes care. Thanks for your effort!
