### ISSUE TITLE
400 Bad Request on "Search in names"

### ISSUE THREAD

**Issue by CoLumc** [eikek/docspell#822]
Im running the recompiled zip Version of Docspell with Apache Solr behind a nginx.
The content search with Apache Solr runs fine but the "Search in Names" show this in the log:

> [blaze-selector-2] INFO  o.h.b.c.n.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:36056  
> [blaze-selector-3] INFO  o.h.b.c.n.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:36060  
> [ioapp-compute-2] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchStats  
> [ioapp-compute-2] INFO  o.h.s.m.Logger - HTTP/1.1 400 Bad Request  
> [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/search  
> [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 400 Bad Request  

If I access Docspell direct without nginx the problem is still the same, even if I disable Solr.

**Comment by eikek** [comment]
Hi @CoLumc  thanks for reporting! This is a bug, I also discovered a minute ago. Actually, I just came here to create an issue for this and a similar one.

The "search in names" is not searching at solr, though. If you want to search solr, you'd need to use "Content search". Now, this is also broken a bit, but if you don't have too many documents, you shouldn't notice it.

**Comment by CoLumc** [comment]
I just installed Solr so I first thought it has something to do with that so I disabled it again.
Alright, so not a configuration issue, nice.

Solr is working fine for me, I think.

Thank you! Im going to get paperless with your project and its just amazing.

**Comment by eikek** [comment]
Thanks :)! As for now, a workaround for this issue would be to enable "power search" in the user settings. Then the "name search" could be done via `names:<your query here>` (you then only have a single search box). You'd need to put the query in quotes should it contain whitespace.

Unfortunately, the client sends the wrong query when using the other field.
