### ISSUE TITLE
Updating Docker Postgresql Version Issue

### ISSUE THREAD

**Issue by danny91** [eikek/docspell#826]
Hi, Hoping you can help i'm trying to upgrade my install which is currently running on image: postgres:11.7

The most recent is image: postgres:13.3

So when docker-compose starts the images I get the following error from the postgresql container

`
PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-05-24 10:22:21.815 UTC [1] FATAL:  database files are incompatible with server
2021-05-24 10:22:21.815 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 13.3 (Debian 13.3-1.pgdg100+1).
`

Have I missed something?

Thanks

**Comment by eikek** [comment]
Hi @danny91 , unfortunately this is a bit involved. Sometimes, Postgres has helper tools to convert the data into the new storage format. But  in my opinion, the best way is to dump all databases and import them into the new version. So I'd stop all applications connected to the postgres server and execute the `pg_dumpall` command on the current container. Then start a new container with a new empty database directory and postgres 13 and import (via `pg_restore`) the dump(s).
The good thing with this approach is that you don't break existing stuff. If the new db container doesn't work right away, you can always stay on the current version. Docspell doesn't use advanced features of postgresql, so in that regard you can also stay on version 11.

**Comment by danny91** [comment]
@eikek Ah great thanks for the response. If i can stay on 11 I'll do that for now.

Thanks
