### ISSUE TITLE
customfield (boolean) not added to item when not changed once

### ISSUE THREAD

**Issue by monnypython** [eikek/docspell#842]
I use a Customfield for a true / false information. If the field is added and the status should be false, so the checkbox is unchecked, the field will not be added after leaving the item. It is only added when the checkbox is true once and then false is set.
I think the field of type Boolean should be added after adding basically first as false because no further user action is required, whether true or false.

**Comment by eikek** [comment]
Ah yes, good point. The boolean field is different than the other types here.
