### ISSUE TITLE
Cannot upload files manually: "There were errors uploading some files."

### ISSUE THREAD

**Issue by TheAnachronism** [eikek/docspell#862]
I recently updated docspell but I'm note sure if it's because of the update but:
When I try to submit those documents or even just a single file I get the error
`There were errors uploading some files.`
Having a look into the browser console I get two errors and one warning stating:
![image](https://user-images.githubusercontent.com/32616088/121244400-1bff3f00-c89f-11eb-9417-bbda13d9c435.png)

I'm running the entire thing in docker containers and behind a nginx reverse proxy but that never was a problem until now.
I also had a look into all the live logs of those containers but none of them really gave out something...

What's wrong here?

**Comment by eikek** [comment]
Hm, not sure either. You could try with clearing the browser cache (like using a private window), if not done already. This is the upload via the webapp or all uploads? Could you try to upload a file using this `ds.sh` script?

**Comment by TheAnachronism** [comment]
This is upload via the web app.
Yes I've already cleared the browser cache and that didn't fix it.
With the ds.sh script I first need to learn how that works with docker^^
But I'll try it out.

**Comment by eikek** [comment]
It's not different for docker, it is only a bash script that uploads a file. You can use it like `ds.sh /path/to/some/document.pdf` for example.

**Comment by TheAnachronism** [comment]
Oof this script isn't available inside the ./docker directory?
I'm running the entire thing inside of yacht so I don't have the entire git repo cloned -.-

**Comment by TheAnachronism** [comment]
Mhh ok
via the script it worked...

**Comment by eikek** [comment]
Hm.. ok; so it's the webapp. Can't remember any changes there. Since I have no other idea, I'd still focus on the browser cache once more. Just to be sure, could you open dev-tools again. There is the "Storage" Tab. If there is anything under "Cache Storage", could you try to remove it by hand and then do a hard-reload (I use firefox, and do it with Ctrl-Shift-R)? While the reload is running are any errors printed to the "Console" tab?



![Selection_228](https://user-images.githubusercontent.com/701128/121250433-00e3fd80-c8a6-11eb-8da6-ca72de1feee3.png)

**Comment by TheAnachronism** [comment]
alright:
![image](https://user-images.githubusercontent.com/32616088/121250967-a39c7c00-c8a6-11eb-9f66-bb79e62d3cbb.png)
These are the errors / warnings I'm getting here
About the service worker I'm not sure if that might be the problem.

**Comment by eikek** [comment]
Oh that's interesting.  The warning is not relevant, but the error about the service-worker could be related. Also interesting that it tried a post request to "about:blank" :-). I dont have this in my browser …hm. Does you reverse-proxy add some headers to the response? Could you look into the responses in the network tab?

Or just came to my mind: Do you have a browser extension active? I once had problems with such an extension that modified the site a bit.

**Comment by TheAnachronism** [comment]
Mhh I just tried it with a private browser window which has no extensions active and it still doesn't work...
`
server {
    listen                  443 ssl;
    server_name            XXX;

    location / {
        proxy_pass                  http://127.0.0.1:38050;
        proxy_set_header            Host $host;
        proxy_set_header            X-Real-IP $remote_addr;
        proxy_set_header            X-Scheme $scheme;
        proxy_set_header   		    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   		    X-Forwarded-Proto $scheme;
        proxy_connect_timeout       1;
        proxy_send_timeout          30;
        proxy_read_timeout          30;
    }
}
`

This is my configuration for nginx
of course `XXX` is replaced by my domain and so on but that's it.
I don't think those headers are a problem but I don't know.

**Comment by vakilando** [comment]
to exclude the reverse proxy config.....what happens if you try uploading a document by using the IP address instead of the fqdn?

By the way, this is my nginx reverse proxy config:

server {
	listen 443 ssl;
	include /config/nginx/ssl.conf;
	server_name blahblah-my-fqdn.domain.net;
	client_max_body_size 0;

	location / {
		include /config/nginx/proxy.conf;
        proxy_pass http://the.ip.add.ress.:7880;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
	}
}

**Comment by TheAnachronism** [comment]
Alright weird...
Using just the IP-Address it works.
But for that I had to expose the port directly which I specified in the docker-compose.yml and changed the base_url in docspell.conf.

**Comment by vakilando** [comment]
> Is there anything wrong with this?

no, I think it looks good.

I have the IP addresses instead of the container names (like http://solr:8983/) and I have no variables like you in the jdbc url, but this should not be the problem. I replaced them because I had difficulties getting docspell up and running in the beginning and never tried to revert this working configuration. So my conf is not as it shoud be....

**Comment by eikek** [comment]
Really strange! I don't see anything wrong in the config either. It's only the upload that is not working, right? I recorded a short gif, could you maybe do these steps too? I'd like to see what the browser really gets as response and how the request looks like. You only need to go to the network tab, clear from everything and then submit a file.

https://user-images.githubusercontent.com/701128/121407057-34369300-c95f-11eb-8497-cafe6598deff.mp4

**Comment by TheAnachronism** [comment]
Ah because of your gif I finally found out what the problem is.
My nginx reverse proxy gives back a 413 - Request entity too large.
So I guess I have to adjust something for the proxy settings.

**Comment by eikek** [comment]
Ah right! it's even in your first screenshot! I didn't pay attention enough back then as well :)

**Comment by TheAnachronism** [comment]
Yeah I didn't know 413 was the HTTP Response error code for too large files but well.
At least I learned something new^^
