### ISSUE TITLE
Can not set different languages on upload sources

### ISSUE THREAD

**Issue by dkaparis** [eikek/docspell#877]
I have defined a couple of upload url's (sources) in collective settings.

Though the configuration allows setting tags and other settings separately for each, it appears that setting language on one sets the same on the other as well.

**Comment by eikek** [comment]
Hi @dkaparis , thank you very much for reporting this! From a quick look it seems to be a webui only problem … the language is stored correctly in the db, so the documents should get processed with the corresponding language. Unfortunately, the ui is broken here…
