### ISSUE TITLE
Tag Category Filter not working

### ISSUE THREAD

**Issue by CoLumc** [eikek/docspell#879]
I found a new Bug with the Filter on Tag Categories. Filtering Tags works fine, but the Categories not.
No Error in the log

> [blaze-selector-3] INFO  o.h.b.c.n.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:57280
> [blaze-selector-4] INFO  o.h.b.c.n.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:57282
> [ioapp-compute-0] DEBUG d.b.o.OSimpleSearch - Using sql only search with tags: Query(Fix(AccountId(Ident(blablabla),Ident(blablabla)),Some(ValidItemStates),None),QueryExpr(Some(TagCategoryMatch(AllMatch,NonEmptyList(blablabla))))) / None
> [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/search
> [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK
> [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 POST /api/v1/sec/item/searchStats
> [ioapp-compute-0] INFO  o.h.s.m.Logger - HTTP/1.1 200 OK

**Comment by eikek** [comment]
Hi @CoLumc , thanks for reporting! Which version are you using? There is #849 which may be related - this would be fixed in the next release (is available via current SNAPSHOT version).

**Comment by CoLumc** [comment]
Im using 0.23.0.
Tried it and yes, its exact the same Issue! Thanky you!

**Comment by eikek** [comment]
Ah great :) I then close it. I hope to make a release in the next couple of days.
