### ISSUE TITLE
Feature request: consumedir.sh option to include/exclude filetypes

### ISSUE THREAD

**Issue by mp68** [eikek/docspell#885]
Hi,
I think an option to exclude/include certain filetypes in consumedir.sh would be nice. When running consumedir.sh using the integration flag, the recursive option includes and uploads metadata files to docspell. In my case I'm running it on a Synology DiskStation which creates meta data files for every file uploaded to a shared folder via network share. Those files are added to docspell and have to be deleted manually. An option to allow or disallow certain filetypes would help in such an environment 😊

**Comment by eikek** [comment]
Yes good idea, thanks. Would it suffice in your case to specify one glob pattern, like `--exclude "*.metadata"` (same for include)?

**Comment by eikek** [comment]
It's been added. Files can be excluded and included, example: `consumedir.sh --include "*.pdf" --exclude "but-not-this.pdf" …`

**Comment by mp68** [comment]
That's perfect! Thanks a lot!
