### ISSUE TITLE
Feature request: better preview size (use whole width, less hight of document)

### ISSUE THREAD

**Issue by lopiuh** [eikek/docspell#911]
the preview size shows the hole page (in small) left and right are blank areas. Paperless-ng does a trick, that it shows the top 2/3 of  the document and fills the whole width of the preview pane. In doing this you get a better picture of the document, because seing the top part of the document someway bigger is "better" than seeing the whole document in tiny format (IMHO).

I try to add a screenshot

Thanks

lopih

**Comment by lopiuh** [comment]
![docspell](https://user-images.githubusercontent.com/24194715/124363620-a5a2f200-dc3c-11eb-8de4-6c24d63f1e54.png)


Docspell

**Comment by lopiuh** [comment]
![paperless](https://user-images.githubusercontent.com/24194715/124363768-7c369600-dc3d-11eb-9a20-ef547a2cfbc8.png)


paperless

**Comment by eikek** [comment]
Hi @lopiuh , I think this is possible already, if I understood correctly. You can click on the icon next to the search bar to toggle between "full page" and "full width" previews.

https://user-images.githubusercontent.com/701128/124365728-1d2b4e00-dc4a-11eb-98fb-2a4737a261fc.mp4

**Comment by lopiuh** [comment]
Hi, thanks,

that looks good, I maybe have to enlarge thumbnail resolution to get a sharper view, but the feature is indeed how I thought about.

**Comment by eikek** [comment]
Great! Yes, you can change the dpi size in the configuration file and then run a job to regenerate all previews (relevant [doc page](https://docspell.org/docs/tools/regenerate-previews/)).
