### ISSUE TITLE
Help. Not wokring install

### ISSUE THREAD

**Issue by ToshaEssential** [eikek/docspell#937]
I followed the instructions from the website dockspell. Didn't work. I did these steps. Help.
```
Docspell consists of several components. The easiest way to get started is probably to use docker and docker-compose.

    Clone the github repository

    $ git clone https://github.com/eikek/docspell

    Alternatively, download the sources and extract the zip file.
    Change into the docker directory:

    $ cd docspell/docker/docker-compose

    Run docker-compose up:

    $ export DOCSPELL_HEADER_VALUE="my-secret-123"
    $ docker-compose up

    The environment variable defines a secret that is shared between some containers. You can define whatever you like. Please see the consumedir.sh docs for additional info.

    Goto http://localhost:7880, signup and login. When signing up, choose the same name for collective and user. Then login with this name and the password.

    (Optional) Create a folder ./docs/<collective-name> (the name you chose for the collective at registration) and place files in there for importing them.

```
OS - ubuntu 20.04 
ERROR:
anton@docspell:~/docspell/docker/docker-compose$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by eikek** [comment]
It seems your version of docker-compose is too old. Can you post `docker-compose --version`?

**Comment by ToshaEssential** [comment]
> 
> 
> It seems your version of docker-compose is too old. Can you post `docker-compose --version`?

docker-compose version 1.25.0, build unknown

**Comment by eikek** [comment]
This version is almost 2 years old (https://docs.docker.com/compose/release-notes/#1250). Try upgrading to a newer version. You can also try to set the version down to some that is supported by 1.25.0 in the docker-compose file and see if that works.

**Comment by ToshaEssential** [comment]
> 
> 
> This version is almost 2 years old (https://docs.docker.com/compose/release-notes/#1250). Try upgrading to a newer version. You can also try to set the version down to some that is supported by 1.25.0 in the docker-compose file and see if that works.

I updated the version and everything worked!!! Thanks!!!

**Comment by eikek** [comment]
Great! You're welcome!

**Comment by eikek** [comment]
I think it can be closed. Just reopen, if something is missing.
