### ISSUE TITLE
Where are the documents stored?

### ISSUE THREAD

**Issue by sortedcord** [eikek/docspell#946]
I wanted to clean the storage of my hard drive and do a reinstallation, for that I wanted to know where Docspell stores all of the documents as downloading individually would be very inconvenient.

**Comment by eikek** [comment]
They are stored in the database. If you drop the database, your documents are gone, too. You can your the [export-files script](https://docspell.org/docs/tools/export-files/) to download all data if you want that.

**Comment by sortedcord** [comment]
Ahh that was what I was looking for. Thanks
