### ISSUE TITLE
handling with big tag collection

### ISSUE THREAD

**Issue by monnypython** [eikek/docspell#960]
My tag collection has now grown to almost 100 and slowly I can't remember all of them;). I have 2 ideas to make working with large tag collections a little easier:

## 1. Edit mode
In edit mode, you can only select from all tags without any obvious categorization. Here it might make sense to be able to make a preselection (similar to the sidebar) because I can remember the category better and then search for the tags within and assign them to the document.

Maybe like:
![image](https://user-images.githubusercontent.com/42573701/127270753-d98890a7-8002-4791-bf2b-6261a387b81a.png)

## 2. Manage data
It would sometimes be helpful if you could sort by categories in order to be able to see all tags of a category.

**Comment by eikek** [comment]
Yes, I can understand this! The idea with the colored circles is neat! I'm just a bit unsure if that scales to many categories? 

I thought about the following: add the category next to the tag in the menu and allow to search for the category as well. This should also reduce the confusion - have to experiment with this though

**Comment by monnypython** [comment]
The selection of the category via a dropdown (as in the properties window of the main view) is of course easy to understand for the familiar user and can also be safely implemented with less effort.

Since I actually think the idea with the dots is really cool, a few thoughts on this :
- I imagine the preselection to be a little more fluid. I spend a lot of time tagging, but that's certainly very subjective. In my opinion it makes even more sense in connection with the "Offtopic" topic (below)
- Since there are currently only 13 colors, the selection is limited here. If several categories have the same color, the description could be displayed in the tooltip. The user still knows roughly what the colors mean. The preselection would still be quite good.

Offtopic:
At the moment I find the selection of tags via the drop-down list not so optimal because I have just accumulated a lot of tags although I have really tried to stay as specific as possible so that the autotagging works well.
For manual "post-tagging", especially with larger collections, something like this might make sense (since I'm not a great programmer, of course I can't say how time-consuming something like this is):
https://github.com/zekunyan/TTGTagCollectionView

**Comment by eikek** [comment]
I think we can have both. The colored dots are a nice idea! We could show the first maybe 5-8 cateogries (ordered by number of tagged items). Only thing to think about is to make it useful on smaller devices when there is no tooltip etc available. But we could also just remove it on mobile devices… not sure.

Thanks for the offtopic thougts :-) I also thought about removing the dropdown and rendering a similar view as in the search menu. I actually forgot why I didn't make progress there, maybe just time constraints. But in general I'm open to replace the dropdown with something more appropriate for selecting tags. This is a time consuming task (as all ui things are), but brings good value.
