### ISSUE TITLE
Sending an email with an address that is not in the address book does not work

### ISSUE THREAD

**Issue by monnypython** [eikek/docspell#969]
The documentation says: "You can type in any address, of course, it doesn't need to match a proposal."
But it doesn't work.

- After entering an email address that is not in the address book, the "Send" button remains grayed out after all required fields have been entered.
- You cannot see the full email address.

<img src="https://user-images.githubusercontent.com/42573701/127615238-832334a6-3f90-4c29-976e-626c4be6f456.png" alt="Your image title" width="450"/>

**Comment by eikek** [comment]
I think this is an usability issue…. You need to confirm the e-mail with ENTER. It should look like when you confirmed the mail from the address book.

**Comment by monnypython** [comment]
Ah ok. I didn't realize that. The note should be in the documentation or?

**Comment by eikek** [comment]
Yes, that would be good of course! It's not mentioned explicitly for the "non-addressbook" case and so confusing.

**Comment by monnypython** [comment]
Or is it perhaps possible to generate the confirmation automatically when the field is left? ENTER or leave the field is basically the same.

**Comment by eikek** [comment]
Maybe I can do that. I can remember having problems with the onfocus events. But haven't tried for a while

**Comment by eikek** [comment]
I created a new issue #987 for improving this situation.
