### ISSUE TITLE
[Bug, UI] Recursive display of UI instead of document

### ISSUE THREAD

**Issue by floli** [eikek/docspell#975]
Hello,

best explained with a picture:

![docspell_recursive](https://user-images.githubusercontent.com/1028028/127763616-490afe6c-bab2-4103-ad07-76d69247fb0e.png)

It even goes one, when I select the document in the sub-portion of the window it is again displayed like that, i.e., entire UI is rendered in a sub-sub-portion...

When I enable "Render PDF in browser", everything is fine.

It happens with Chromium and Firefox, both recent version. The issue is fairly new for me, wasn't there two weeks ago.

Installation is from a the repo's docker-compose file, most recently pulled.

**Comment by vakilando** [comment]
Yes, same proplem here with Firefox and Vivaldi on Linux. 
I've upgraded my old docspell v0.23 to v0.25.1 including a postgresql upgrade from version 11.7 to 13.3.
It affects my test docker installion on a Debian vm and my production install on unraid as docker.

**Comment by eikek** [comment]
yeah, thanks! I also realized it yesterday evening. how sad! I think this was the dependency upgrade of viewer.js. for mobile this is bad, on desktop browsers it's recommended to use the browsers pdf viewer. this can be set globally in user settings.
