### ISSUE TITLE
 [Feature Request] Update-Checker

### ISSUE THREAD

**Issue by CoLuxe** [eikek/docspell#990]
Im currently using the Zip-Packages and have manually check for updates here on Github.

An implemented Update-Checker would be amazing.
I would do it that way:
Because there is already an option in den Interface to setting up IMAP (Edit: SMTP, not IMAP), maybe only add an option in the config file, where you can fill in the username, where the Notification send to.
And then check everyday for a new Release on Github and then send the E-Mail out.

Thanks!

**Comment by eikek** [comment]
Ah nice idea, thank you! I also think an email address in the config file is good enough, it should be only interesting to the admin and not all users.

**Comment by CoLuxe** [comment]
Yes, thats why using the SMTP settings you have already done maybe useful. 
But for more flexbility it would be nice to configure the SMTP Server (and "From" and "To"-Mail Adress) in the config file so its completely indepent from the users.

**Comment by eikek** [comment]
Yes, you're right. I can see that both is useful. Hm, since this is meant to be a personal tool, I guess most of the time, the "admin" is also using it as a user. So it might be a good first start to be able to specify an account to use for this. But I'll see if both options could be provided.

**Comment by CoLuxe** [comment]
Nice! Thank you!
