### ISSUE TITLE
File download for non-ascii file names returns empty filename

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#991]
Reported here: https://app.element.io/#/room/#eikek_docspell:gitter.im/$3ghPsyulhxf71UJJMxQ9qAbecaWkys6wTXNONm2vA_U

When using for example cyrillic letters for filenames, docspell won't return them when downloading the file. The `Content-Disposition` header contains an empty filename.

**Comment by eikek** [comment]
The database contains no file name, so the server cannot return anything. It seems an issue with the http librrary, I could create an example which I reported upstream here: http4s/http4s#5053 - docspell seems not to get the filename in the first place.

**Comment by eikek** [comment]
Sorry, I can't do much about this right now. Need to wait for some response to the upstream issue. Until then cyrillic filenames only work with 0.24.0 :/

**Comment by wallace11** [comment]
When you upload files with non-ascii characters in their names through the web uploader, they get the following name "webapp: No files supplied". I'm pretty sure it's related...
